# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build: .
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - 8000:8000
    env_file:
      - ".env.docker"
      - path: ".env"
        required: false
    depends_on:
      db-backup:
        condition: service_healthy
  frontend:
    build:
      context: frontend
    image: ma-cantine-front
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
    env_file:
      - ".env.docker"
      - path: ".env"
        required: false
  2024-frontend:
    build:
      context: 2024-frontend
    image: ma-cantine-2024-front
    volumes:
      - "./2024-frontend:/app/2024-frontend"
      - "/app/2024-frontend/node_modules"
    ports:
      - 5173:5173
    env_file:
      - ".env.docker"
      - path: ".env"
        required: false
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ma-cantine
      PGPORT: 3306
      POSTGRES_PASSWORD: password
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  db-backup:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./:/app"
    environment:
      POSTGRES_DB: ma-cantine-restore
      PGPORT: 3308
      POSTGRES_PASSWORD: password
    ports:
      - 3308:3308
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  # it's normal that this is empty, it simply defines the existance of persistent storage
  db-data:
