from django.conf import settings
from django.db import models
from django.db.models import Count, IntegerField, OuterRef, Subquery
from django.db.models.functions import Coalesce
from django.db.models.signals import post_save
from django.dispatch import receiver


class Oauth2ProviderApplicationExtra(models.Model):
    """
    Extra fields for the django-oauth-toolkit Application model
    """

    application = models.OneToOneField(
        settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
        on_delete=models.CASCADE,
        related_name="extra",
        verbose_name="Application Oauth2 (API)",
    )
    company_name = models.CharField(max_length=255, blank=True, verbose_name="nom de l'entreprise")

    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Application Oauth2 (API) : informations complémentaires"
        verbose_name_plural = "Applications Oauth2 (API) : informations complémentaires"

    def __str__(self):
        return f"{self.application} ({self.company_name})" if self.company_name else str(self.application)


def get_application_created_count_managers():
    """
    {annotation name: manager} of the objects created via the API (creation_source_api_oauth2_application)
    - deleted canteens & purchases included (all_objects)
    - diagnostics generated by the platform (1td1site) excluded
    """
    from data.models import Canteen, Diagnostic, Purchase, WasteMeasurement

    return {
        "canteens_created_count": Canteen.all_objects,
        "diagnostics_created_count": Diagnostic.objects,
        "purchases_created_count": Purchase.all_objects,
        "waste_measurements_created_count": WasteMeasurement.objects,
    }


def annotate_with_created_counts(application_queryset):
    """
    Annotate an Application queryset with the number of objects created by each application
    (one subquery per model: avoids the count inflation of multiple joins)
    """
    return application_queryset.annotate(
        **{
            name: Coalesce(
                Subquery(
                    manager.filter(creation_source_api_oauth2_application=OuterRef("pk"))
                    .order_by()
                    .values("creation_source_api_oauth2_application")
                    .annotate(count=Count("id"))
                    .values("count"),
                    output_field=IntegerField(),
                ),
                0,
            )
            for name, manager in get_application_created_count_managers().items()
        }
    )


@receiver(post_save, sender=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)
def create_oauth2_provider_application_extra(sender, instance, created, raw=False, **kwargs):
    """
    On application creation, create its (empty) extra
    """
    if created and not raw:
        Oauth2ProviderApplicationExtra.objects.get_or_create(application=instance)
