# Generated by Django 3.2.3 on 2021-06-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210601_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='Diagnostic',
        ),
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'verbose_name': 'diagnostic', 'verbose_name_plural': 'diagnostics'},
        ),
    ]
