# Generated by Django 3.2.3 on 2021-06-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210602_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='comunicates_on_food_plan',
            new_name='communicates_on_food_plan',
        ),
    ]
