# Generated by Django 3.2.3 on 2021-06-11 14:08

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_diagnostic_has_waste_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='bread_leftovers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='reste de pain kg/an'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='communicates_on_food_quality',
            field=models.BooleanField(null=True, verbose_name='Communique sur les démarches qualité/durables/équitables'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='communication_frequency',
            field=models.CharField(blank=True, choices=[('REGULARLY', 'Régulièrement au cours de l’année'), ('YEARLY', 'Une fois par an'), ('LESS_THAN_YEARLY', "Moins d'une fois par an")], max_length=255, null=True, verbose_name='fréquence de communication'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='donation_food_type',
            field=models.TextField(blank=True, null=True, verbose_name='type de denrées données'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='donation_frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='fréquence de dons dons/an'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='donation_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='quantité des denrées données kg/an'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='has_waste_measures',
            field=models.BooleanField(null=True, verbose_name='réalise des mesures de gaspillage alimentaire'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='other_communication_support',
            field=models.TextField(blank=True, null=True, verbose_name='autre communication utilisée'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='other_waste_action',
            field=models.TextField(blank=True, null=True, verbose_name='autre action contre le gaspillage alimentaire'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='other_waste_comments',
            field=models.TextField(blank=True, null=True, verbose_name='autres commentaires (gaspillage)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='served_leftovers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='reste plateau kg/an'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='side_leftovers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='reste de composantes kg/an'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='unserved_leftovers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='reste en production (non servi) kg/an'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='vegetarian_menu_bases',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('GRAIN', 'Légumes secs et céréales'), ('READYMADE', "Plats prêts à l'emploi")], max_length=255), blank=True, null=True, size=None, verbose_name='bases de menu végétarien'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='communication_supports',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('EMAIL', "Envoi d'e-mail aux convives ou à leurs représentants"), ('DISPLAY', 'Par affichage sur le lieu de restauration'), ('WEBSITE', 'Sur site internet ou intranet (mairie, cantine)'), ('OTHER', "Autres moyens d'affichage et de communication électronique"), ('DIGITAL', 'Par voie électronique')], max_length=255), blank=True, null=True, size=None, verbose_name='Communication utilisée'),
        ),
    ]
