# Generated by Django 3.2.3 on 2021-06-10 15:17

from django.db import migrations, models

def migrate_email_confirmed(apps, schema_editor):
    User = apps.get_model('data', 'User')
    for user in User.objects.all():
        user.email_confirmed = user.is_active
        user.save()

def undo_migrate_email_confirmed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_canteen_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default='False', verbose_name='adresse email confirmée'),
        ),
        migrations.RunPython(migrate_email_confirmed, undo_migrate_email_confirmed),
    ]
