# Generated by Django 3.2.3 on 2021-06-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_add_diagnostic_fields'),
        ('data', '0007_user_email_confirmed'),
    ]

    operations = [
    ]
