# Generated by Django 3.2.3 on 2021-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_merge_20210611_1700'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diagnostic',
            constraint=models.UniqueConstraint(fields=('canteen', 'year'), name='annual_diagnostic'),
        ),
    ]
