# Generated by Django 3.2.4 on 2021-06-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_diagnostic_annual_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image principale'),
        ),
    ]
