# Generated by Django 3.2.3 on 2021-07-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_canteen_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.canteen')),
            ],
            options={
                'verbose_name': 'nouveau gestionnaire',
                'verbose_name_plural': 'nouveaux gestionnaires',
            },
        ),
        migrations.AddConstraint(
            model_name='managerinvitation',
            constraint=models.UniqueConstraint(fields=('canteen', 'email'), name='deduplicate_manager'),
        ),
    ]
