# Generated by Django 3.2.4 on 2021-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_canteen_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='deletion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de suppression par l'utilisateur"),
        ),
    ]
