# Generated by Django 3.2.4 on 2021-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_canteen_deletion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='city_insee_code',
            field=models.TextField(blank=True, null=True, verbose_name='Code INSEE'),
        ),
    ]
