# Generated by Django 3.2.3 on 2021-07-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_create_manager_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='production_type',
            field=models.CharField(blank=True, choices=[('central', 'Cuisine centrale'), ('site', 'Cuisine-site')], max_length=255, null=True, verbose_name='mode de production'),
        ),
    ]
