# Generated by Django 3.2.3 on 2021-07-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_canteen_production_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='public_contact',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact public'),
        ),
    ]
