# Generated by Django 3.2.3 on 2021-07-07 13:59

from django.db import migrations, models

def migrate_publication_status(apps, schema_editor):
    Canteen = apps.get_model('data', 'Canteen')
    for canteen in Canteen.objects.all():
        if canteen.data_is_public:
            canteen.publication_status = "published"
            canteen.save()

def undo_migrate_publication_status(apps, schema_editor):
    Canteen = apps.get_model('data', 'Canteen')
    for canteen in Canteen.objects.all():
        if canteen.publication_status == "published":
            canteen.data_is_public = True
            canteen.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_canteen_production_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='publication_status',
            field=models.CharField(choices=[('draft', '🔒 Non publié'), ('pending', '❓ En attente de vérification'), ('published', '✅ Publié')], default='draft', max_length=50, verbose_name='état de publication'),
        ),
        migrations.RunPython(migrate_publication_status, undo_migrate_publication_status),
        migrations.RemoveField(
            model_name='canteen',
            name='data_is_public',
        ),
        migrations.RemoveField(
            model_name='canteen',
            name='published',
        ),
    ]
