# Generated by Django 3.2.5 on 2021-07-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteen',
            options={'ordering': ['-creation_date'], 'verbose_name': 'cantine', 'verbose_name_plural': 'cantines'},
        ),
    ]
