# Generated by Django 3.2.5 on 2021-07-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_canteen_publication_status'),
        ('data', '0016_alter_canteen_options'),
    ]

    operations = [
    ]
