# Generated by Django 3.2.3 on 2021-07-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_merge_20210722_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='central_producer_siret',
            field=models.TextField(blank=True, null=True, verbose_name='siret de la cuisine centrale'),
        ),
    ]
