# Generated by Django 3.2.3 on 2021-07-30 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_canteen_central_producer_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2100)], verbose_name='an'),
        ),
    ]
