# Generated by Django 3.2.3 on 2021-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_diagnostic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='communicates_on_food_plan',
            field=models.BooleanField(blank=True, null=True, verbose_name='Communique sur le plan alimentaire'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='communicates_on_food_quality',
            field=models.BooleanField(blank=True, null=True, verbose_name='Communique sur les démarches qualité/durables/équitables'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='cooking_plastic_substituted',
            field=models.BooleanField(blank=True, null=True, verbose_name='contenants de cuisson en plastique remplacés'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='has_diversification_plan',
            field=models.BooleanField(blank=True, null=True, verbose_name='plan de diversification en place'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='has_donation_agreement',
            field=models.BooleanField(blank=True, null=True, verbose_name='propose des dons alimentaires'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='has_waste_diagnostic',
            field=models.BooleanField(blank=True, null=True, verbose_name='diagnostic sur le gaspillage réalisé'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='has_waste_measures',
            field=models.BooleanField(blank=True, null=True, verbose_name='réalise des mesures de gaspillage alimentaire'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='has_waste_plan',
            field=models.BooleanField(blank=True, null=True, verbose_name="plan d'action contre le gaspillage en place"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='plastic_bottles_substituted',
            field=models.BooleanField(blank=True, null=True, verbose_name='bouteilles en plastique remplacées'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='plastic_tableware_substituted',
            field=models.BooleanField(blank=True, null=True, verbose_name='ustensils en plastique remplacés'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='serving_plastic_substituted',
            field=models.BooleanField(blank=True, null=True, verbose_name='contenants de service en plastique remplacés'),
        ),
    ]
