# Generated by Django 3.2.5 on 2021-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_diagnostic_blank_booleans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='année'),
        ),
    ]
