# Generated by Django 3.2.6 on 2021-08-17 09:45

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_diagnostic_year'),
    ]

    operations = [
        UnaccentExtension()
    ]
