# Generated by Django 3.2.6 on 2021-08-25 16:57

import data.models.canteen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20210817_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='diversification_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure diversification'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='information_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure information'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='plastics_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure plastiques'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='publication_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='commentaires de publication'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='quality_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure appro'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='waste_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure gaspillage'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='central_producer_siret',
            field=models.TextField(blank=True, null=True, validators=[data.models.canteen.validate_siret], verbose_name='siret de la cuisine centrale'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='siret',
            field=models.TextField(blank=True, null=True, validators=[data.models.canteen.validate_siret]),
        ),
    ]
