# Generated by Django 3.2.6 on 2021-08-26 08:24

import data.models.canteen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20210817_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='central_producer_siret',
            field=models.TextField(blank=True, null=True, validators=[data.models.canteen.validate_siret], verbose_name='siret de la cuisine centrale'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='siret',
            field=models.TextField(blank=True, null=True, validators=[data.models.canteen.validate_siret]),
        ),
    ]
