# Generated by Django 3.2.6 on 2021-08-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20210826_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teledeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='année')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Télédéclaré'), ('CANCELLED', 'Annulé')], max_length=255, verbose_name='status')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.canteen', verbose_name='cantine')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.diagnostic', verbose_name='diagnostic source')),
            ],
            options={
                'verbose_name': 'télédéclaration',
                'verbose_name_plural': 'télédéclarations',
            },
        ),
    ]
