# Generated by Django 3.2.6 on 2021-08-30 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_teledeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teledeclaration',
            name='canteen_siret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teledeclaration',
            name='fields',
            field=models.JSONField(default={}, verbose_name='Champs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teledeclaration',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='demandeur'),
        ),
        migrations.AlterField(
            model_name='teledeclaration',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.canteen', verbose_name='cantine'),
        ),
        migrations.AlterField(
            model_name='teledeclaration',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.diagnostic', verbose_name='diagnostic source'),
        ),
    ]
