# Generated by Django 3.2.6 on 2021-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_canteen_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='diversification_comments',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure diversification'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='information_comments',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure information'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='plastics_comments',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure plastiques'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='publication_comments',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='commentaires de publication'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='quality_comments',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure appro'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='waste_comments',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='commentaires de mesure gaspillage'),
        ),
    ]
