# Generated by Django 3.2.6 on 2021-08-31 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_canteen_department'),
        ('data', '0026_auto_20210830_1558'),
    ]

    operations = [
    ]
