# Generated by Django 3.2.6 on 2021-09-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_add_publication_comments'),
        ('data', '0028_auto_20210901_1349'),
    ]

    operations = [
    ]
