# Generated by Django 3.2.6 on 2021-09-07 07:55

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_merge_20210902_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='diversification_plan_actions',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('PRODUCTS', 'Agir sur les plats et les produits (diversification, gestion des quantités, recette traditionnelle, gout...)'), ('PRESENTATION', 'Agir sur la manière dont les aliments sont présentés aux convives (visuellement attrayants)'), ('MENU', 'Agir sur la manière dont les menus sont conçus ces plats en soulignant leurs attributs positifs'), ('PROMOTION', 'Agir sur la mise en avant des produits (plats recommandés, dégustation, mode de production...)'), ('TRAINING', 'Agir sur la formation du personnel, la sensibilisation des convives, l’investissement dans de nouveaux équipements de cuisine...')], max_length=255), blank=True, null=True, size=None, verbose_name='actions inclus dans le plan de diversification des protéines'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='vegetarian_menu_bases',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('GRAIN', 'De céréales et/ou les légumes secs (hors soja)'), ('SOY', 'De soja'), ('CHEESE', 'De fromage'), ('EGG', 'D’œufs'), ('READYMADE', "Plats prêts à l'emploi")], max_length=255), blank=True, null=True, size=None, verbose_name='bases de menu végétarien'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='vegetarian_menu_type',
            field=models.CharField(blank=True, choices=[('UNIQUE', 'Un menu végétarien en plat unique'), ('SEVERAL', 'Un menu végétarien composé de plusieurs plats végétariens'), ('ALTERNATIVES', 'Un menu végétarien en plus d’autres menus non végétariens')], max_length=255, null=True, verbose_name='Menu végétarien proposé'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='vegetarian_weekly_recurrence',
            field=models.CharField(blank=True, choices=[('LOW', "Moins d'une fois par semaine"), ('MID', 'Une fois par semaine'), ('HIGH', "Plus d'une fois par semaine"), ('DAILY', 'De façon quotidienne')], max_length=255, null=True, verbose_name='Menus végétariens par semaine'),
        ),
    ]
