# Generated by Django 3.2.8 on 2021-10-08 10:58

from django.db import migrations, models
from data.utils import get_region


def add_region(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")
    for canteen in Canteen.objects.all():
        canteen.region = get_region(canteen.department)
        canteen.save()


def undo_add_region(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0031_diagnostic_add_pat_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="region",
            field=models.TextField(
                blank=True,
                choices=[
                    ("01", "01 - Guadeloupe"),
                    ("02", "02 - Martinique"),
                    ("03", "03 - Guyane"),
                    ("04", "04 - La Réunion"),
                    ("06", "06 - Mayotte"),
                    ("11", "11 - Île-de-France"),
                    ("24", "24 - Centre-Val de Loire"),
                    ("27", "27 - Bourgogne-Franche-Comté"),
                    ("28", "28 - Normandie"),
                    ("32", "32 - Hauts-de-France"),
                    ("44", "44 - Grand Est"),
                    ("52", "52 - Pays de la Loire"),
                    ("53", "53 - Bretagne"),
                    ("75", "75 - Nouvelle-Aquitaine"),
                    ("76", "76 - Occitanie"),
                    ("84", "84 - Auvergne-Rhône-Alpes"),
                    ("93", "93 - Provence-Alpes-Côte d'Azur"),
                    ("94", "94 - Corse"),
                ],
                null=True,
                verbose_name="région",
            ),
        ),
        migrations.RunPython(add_region, undo_add_region),
    ]
