# Generated by Django 3.2.7 on 2021-10-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20211006_1055'),
        ('data', '0032_canteen_region'),
    ]

    operations = [
    ]
