# Generated by Django 3.2.8 on 2021-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_merge_0032_auto_20211006_1055_0032_canteen_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='diversification_comments',
            field=models.TextField(blank=True, null=True, verbose_name='commentaires de mesure diversification'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='information_comments',
            field=models.TextField(blank=True, null=True, verbose_name='commentaires de mesure information'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='plastics_comments',
            field=models.TextField(blank=True, null=True, verbose_name='commentaires de mesure plastiques'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='publication_comments',
            field=models.TextField(blank=True, null=True, verbose_name='commentaires de publication'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='quality_comments',
            field=models.TextField(blank=True, null=True, verbose_name='commentaires de mesure appro'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='waste_comments',
            field=models.TextField(blank=True, null=True, verbose_name='commentaires de mesure gaspillage'),
        ),
    ]
