# Generated by Django 3.2.8 on 2021-10-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_publication_comments_no_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='economic_model',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Privé')], max_length=50, null=True, verbose_name='Secteur économique'),
        ),
    ]
