# Generated by Django 3.2.8 on 2021-10-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_canteen_economic_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='value_label_aoc_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur label AOC/AOP/IGP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_label_hve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur label HVE'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_label_rouge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur label rouge'),
        ),
    ]
