# Generated by Django 3.2.8 on 2021-10-25 09:06

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_user_law_awareness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='law_awareness',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('NONE', 'Je n’ai pas une connaissance détaillée de l’article 24 de la loi EGAlim'), ('AIMS_DEADLINES', 'Je connais les objectifs et les échéances'), ('ELIGIBLE_LABELS', 'Je connais la liste des labels éligibles et mentions valorisantes'), ('MY_LABELS', 'J’ai accès aux informations ou mon prestataire me fournit les informations sur les labels éligibles et mentions valorisantes concernant mes achats'), ('SYSTEM', 'J’ai un système de saisie formalisé (SI, Excel, papier) permettant de calculer et reporter le montant annuel de mes achats répondants aux exigences de l’article 24 de la loi EGALIM (N/A en gestion concédée)'), ('TAKEN_STOCK', 'J’ai réalisé un état des lieux précis de mes approvisionnements'), ('OPTION_DIAGNOSTIC', 'J’ai réalisé un diagnostic de l’offre (disponibilité et caractéristiques de l’offre des différents fournisseurs sur l’ensemble des catégories d’achats)'), ('ACTION_PLAN', 'J’ai établi un plan d’actions pour tendre vers les objectifs de la loi EGALim, définissant notamment : le niveau d’ambition global et par catégories d’achats ; les échéances de renouvellement de contrat avec clauses EGALim ; le phasage de la progression des indicateurs EGAlim'), ('QUALITY_ACHIEVED', "J'ai atteint les objectifs de l’article 24 de la loi EGAlim de porter la part de produits de qualité et durables à 50 % dont au moins 20 % de produits issus de l'agriculture biologique")], max_length=255), blank=True, null=True, size=None, verbose_name='Parmi ces affirmations, lesquelles correspondent le plus à votre situation :'),
        ),
    ]
