# Generated by Django 3.2.8 on 2021-10-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_diagnostic_label_values'),
        ('data', '0037_alter_user_law_awareness'),
    ]

    operations = [
    ]
