# Generated by Django 3.2.9 on 2021-11-16 13:35

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_alter_user_law_awareness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='law_awareness',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('NONE', 'Je n’ai pas une connaissance détaillée de l’article 24 de la loi EGAlim'), ('AIMS_DEADLINES', 'Je connais les objectifs et les échéances'), ('ELIGIBLE_LABELS', 'Je connais la liste des labels éligibles et mentions valorisantes'), ('MY_LABELS', 'J’ai accès aux informations ou mon prestataire me fournit les informations sur les labels éligibles et mentions valorisantes concernant mes achats'), ('SYSTEM', 'J’ai un système de saisie formalisé (SI, Excel, papier) permettant de calculer et reporter le montant annuel de mes achats répondants aux exigences de l’article 24 de la loi EGAlim (Non applicable en gestion concédée)'), ('TAKEN_STOCK', 'J’ai réalisé un état des lieux précis de mes approvisionnements'), ('OPTION_DIAGNOSTIC', 'J’ai réalisé un diagnostic de l’offre (disponibilité et caractéristiques de l’offre des différents fournisseurs sur l’ensemble des catégories d’achats)'), ('ACTION_PLAN', 'J’ai établi un plan d’actions pour tendre vers les objectifs de la loi EGAlim, définissant notamment : le niveau d’ambition global et par catégories d’achats ; les échéances de renouvellement de contrat avec clauses EGAlim ; le phasage de la progression des indicateurs EGAlim'), ('QUALITY_ACHIEVED', "J'ai atteint les objectifs - 50% et 20%, de l’article 24 de la loi EGAlim")], max_length=255), blank=True, null=True, size=None, verbose_name="Les affirmations suivantes concernent l'article 24 de la loi EGAlim, encadrant les objectifs d'approvisionnements (50% de produits durables et de qualité dont 20% de bio). Parmi ces affirmations, plusieurs choix sont possibles. Choisissez celles qui correspondent à votre situation :"),
        ),
    ]
