# Generated by Django 3.2.9 on 2022-01-18 09:54

import data.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_user_law_awareness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('provider', models.TextField(blank=True, null=True, verbose_name='Fournisseur')),
                ('category', models.CharField(blank=True, choices=[('VIANDES_VOLAILLES', 'Viandes / volailles'), ('FRUITS_ET_LEGUMES', 'Fruits, légumes'), ('PECHE', 'Pêche'), ('PRODUITS_LAITIERS', 'Produits laitiers'), ('PRODUITS_TRANSFORMES', 'Produits transformés')], max_length=255, null=True, verbose_name='Catégorie')),
                ('characteristics', data.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('BIO', 'Bio'), ('AOCAOP', 'AOC / AOP'), ('RUP', 'RUP'), ('LABEL_ROUGE', 'Label rouge'), ('PECHE_DURABLE', 'Pêche durable'), ('LOCAL', 'Local'), ('HVE', 'HVE'), ('COMMERCE_EQUITABLE', 'Commerce équitable')], max_length=255, null=True, verbose_name='Caractéristique'), blank=True, null=True, size=None, verbose_name='Caractéristiques')),
                ('price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Prix HT')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.canteen')),
            ],
            options={
                'verbose_name': 'achat',
                'verbose_name_plural': 'achats',
                'ordering': ['-date', '-creation_date'],
            },
        ),
    ]
