# Generated by Django 3.2.11 on 2022-01-20 16:55

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_alter_purchase_price_ht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, choices=[('VIANDES_VOLAILLES', 'Viandes, volailles'), ('PRODUITS_DE_LA_MER', 'Produits de la mer'), ('FRUITS_ET_LEGUMES', 'Fruits, légumes, légumineuses et oléagineux'), ('PRODUITS_CEREALIERS', 'Produits céréaliers'), ('ENTREES', 'Entrées et plats composés'), ('PRODUITS_LAITIERS', 'Lait et produits laitiers'), ('BOISSONS', 'Boissons'), ('AIDES', 'Aides culinaires et ingrédients divers'), ('BEURRE_OEUF_FROMAGE', 'Beurre, oeuf, fromage'), ('PRODUITS_SUCRES', 'Produits sucrés'), ('ALIMENTS_INFANTILES', 'Aliments infantiles'), ('GLACES_SORBETS', 'Glaces et sorbets'), ('AUTRES', 'Autres')], max_length=255, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='characteristics',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('BIO', 'Bio'), ('CONVERSION_BIO', 'En conversion bio'), ('LABEL_ROUGE', 'Label rouge'), ('AOCAOP', 'AOC / AOP'), ('ICP', 'Indication géographique protégée'), ('STG', 'Spécialité traditionnelle garantie'), ('HVE', 'Haute valeur environnementale'), ('PECHE_DURABLE', 'Pêche durable'), ('RUP', 'Région ultrapériphérique'), ('FERMIER', 'Fermier'), ('EXTERNALITES', 'Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie'), ('COMMERCE_EQUITABLE', 'Commerce équitable'), ('PERFORMANCE', 'Produits acquis sur la base de leurs performances en matière environnementale'), ('EQUIVALENTS', 'Produits équivalents')], max_length=255, null=True, verbose_name='Caractéristique'), blank=True, null=True, size=None, verbose_name='Caractéristiques'),
        ),
    ]
