# Generated by Django 3.2.11 on 2022-01-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_blog_tags'),
        ('data', '0043_auto_20220120_1755'),
    ]

    operations = [
    ]
