# Generated by Django 3.2.11 on 2022-01-28 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_add_reservation_expe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationexpe',
            name='avg_attendance_count_t0',
        ),
        migrations.RemoveField(
            model_name='reservationexpe',
            name='avg_attendance_count_t1',
        ),
        migrations.RemoveField(
            model_name='reservationexpe',
            name='avg_attendance_count_t2',
        ),
        migrations.AddField(
            model_name='reservationexpe',
            name='avg_attendance_from_evaluation_t0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre moyen d'usagers à partir de l'évaluation"),
        ),
        migrations.AddField(
            model_name='reservationexpe',
            name='avg_attendance_from_evaluation_t1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre moyen d'usagers à partir de l'évaluation"),
        ),
        migrations.AddField(
            model_name='reservationexpe',
            name='avg_attendance_from_evaluation_t2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre moyen d'usagers à partir de l'évaluation"),
        ),
        migrations.AddField(
            model_name='reservationexpe',
            name='has_leader',
            field=models.BooleanField(default=False, verbose_name='Un responsable chargé du pilotage a été désigné'),
        ),
        migrations.AddField(
            model_name='reservationexpe',
            name='has_reservation_system',
            field=models.BooleanField(default=False, verbose_name='a déjà mis en place une solution de réservation de repas'),
        ),
        migrations.AlterField(
            model_name='reservationexpe',
            name='leader_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="prénom du responsable d'expé"),
        ),
        migrations.AlterField(
            model_name='reservationexpe',
            name='leader_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="nom du responsable d'expé"),
        ),
        migrations.AlterField(
            model_name='reservationexpe',
            name='solution_use_rate_t0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Taux d’utilisation de la solution de réservation'),
        ),
    ]
