# Generated by Django 3.2.11 on 2022-01-31 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20220128_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationexpe',
            name='ratio_edible_non_edible_t0',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ratio de la part non comestible (g) rapportée à la part comestible (g)'),
        ),
        migrations.AlterField(
            model_name='reservationexpe',
            name='ratio_edible_non_edible_t1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ratio de la part non comestible (g) rapportée à la part comestible (g)'),
        ),
        migrations.AlterField(
            model_name='reservationexpe',
            name='ratio_edible_non_edible_t2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ratio de la part non comestible (g) rapportée à la part comestible (g)'),
        ),
        migrations.AlterField(
            model_name='reservationexpe',
            name='solution_use_rate_t0',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Taux d’utilisation de la solution de réservation'),
        ),
    ]
