# Generated by Django 4.0.2 on 2022-02-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_auto_20220131_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationexpe',
            old_name='satisfaction_t0',
            new_name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='reservationexpe',
            name='satisfaction_t1',
        ),
        migrations.RemoveField(
            model_name='reservationexpe',
            name='satisfaction_t2',
        ),
    ]
