# Generated by Django 4.0.2 on 2022-02-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_rename_satisfaction_t0_reservationexpe_satisfaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du produit'),
        ),
    ]
