# Generated by Django 4.0.2 on 2022-02-25 10:45

from django.db import migrations, models


def remove_central_production_type(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")
    for canteen in Canteen.objects.all():
        if canteen.production_type == "central":
            canteen.production_type = None
            canteen.save()


def undo_remove_central_production_type(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0050_canteen_satellite_canteens_count_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_central_production_type, undo_remove_central_production_type),
    ]
