# Generated by Django 4.0.2 on 2022-02-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_purchase_local_definition_and_more'),
        ('data', '0051_auto_20220225_1145'),
    ]

    operations = [
    ]
