# Generated by Django 4.0.2 on 2022-02-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_merge_20220225_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='local_definition',
            field=models.CharField(blank=True, choices=[('REGION', 'Région'), ('DEPARTMENT', 'Département'), ('AUTOUR_SERVICE', '200 km autour du lieu de service'), ('AUTRE', 'Autre')], max_length=255, null=True, verbose_name='définition de local'),
        ),
    ]
