# Generated by Django 4.0.2 on 2022-02-28 13:51

import data.models.canteen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_alter_purchase_local_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='central_producer_siret',
            field=models.TextField(blank=True, null=True, validators=[data.models.canteen.validate_siret], verbose_name='siret de la cuisine centrale (si cuisine satellite)'),
        ),
    ]
