# Generated by Django 4.0.3 on 2022-03-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_alter_canteen_central_producer_siret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('sender_name', models.TextField(blank=True, null=True, verbose_name="nom de l'expéditeur")),
                ('sender_email', models.TextField(verbose_name="adresse email de l'expéditeur")),
                ('body', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('SENT', 'Envoyé'), ('BLOCKED', 'Bloqué')], default='PENDING', max_length=255, verbose_name='État')),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('destination_canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.canteen', verbose_name='destinataire')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
