# Generated by Django 4.0.2 on 2022-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='category',
            field=models.CharField(blank=True, choices=[('education', 'Scolaire'), ('health', 'Medical et médico-social')], max_length=50, null=True, verbose_name='catégorie'),
        ),
    ]
