# Generated by Django 4.0.3 on 2022-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_rename_has_used_recipee_documents_t0_vegetarianexpe_has_used_recipe_documents_t0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_no_canteen_first_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de la première relance pour manque de cantines"),
        ),
        migrations.AddField(
            model_name='user',
            name='email_no_canteen_second_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de la première relance pour manque de cantines"),
        ),
    ]
