# Generated by Django 4.0.3 on 2022-04-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_alter_sector_category'),
        ('data', '0057_rename_has_used_recipee_documents_t0_vegetarianexpe_has_used_recipe_documents_t0_and_more'),
    ]

    operations = [
    ]
