# Generated by Django 4.0.3 on 2022-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_user_email_no_canteen_first_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_no_canteen_first_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi du premier email pour manque de cantines"),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_no_canteen_second_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi du second email pour manque de cantines"),
        ),
    ]
