# Generated by Django 4.0.3 on 2022-04-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_merge_20220408_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='category',
            field=models.CharField(blank=True, choices=[('administration', 'Administration'), ('enterprise', 'Entreprise'), ('education', 'Enseignement'), ('health', 'Santé'), ('social', 'Social / Médico-social'), ('leisure', 'Loisirs'), ('autres', 'Autres')], max_length=50, null=True, verbose_name='catégorie'),
        ),
    ]
