# Generated by Django 4.0.3 on 2022-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_merge_20220408_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='line_ministry',
            field=models.TextField(blank=True, choices=[('premier_ministre', 'Service du premier ministre'), ('affaires_etrangeres', 'Ministère de l’Europe et des Affaires étrangères'), ('ecologie', 'Ministère de la Transition écologique'), ('jeunese', 'Ministère de l’Education nationale et de la Jeunesse et des Sports'), ('economie', 'Ministère de l’Economie, de la Finance et de la Relance'), ('armee', 'Ministère de l’Armée'), ('interieur', 'Ministère de l’Intérieur'), ('travail', 'Ministère Travail, de l’Emploi et de l’Insertion'), ('outre_mer', 'Ministère des Outre-mer'), ('territoires', 'Ministère de la Cohésion des territoires et des relations avec les collectivités territoriales'), ('justice', 'Ministère de la Justice'), ('culture', 'Ministère de la Culture'), ('sante', 'Ministère des Solidarités et de la Santé'), ('mer', 'Ministère de la Mer'), ('enseignement_superieur', 'Ministère de l’Enseignement supérieur et de la Recherche et de l’Innovation'), ('agriculture', 'Ministère de l’Agriculture et de l’Alimentation'), ('transformation', 'Ministère de la Transformation et de la Fonction publiques'), ('autre', 'Autre')], null=True, verbose_name='Ministère de tutelle'),
        ),
        migrations.AddField(
            model_name='sector',
            name='has_line_ministry',
            field=models.BooleanField(default=False, verbose_name='Afficher le champ « Ministère de tutelle »'),
        ),
    ]
