# Generated by Django 4.0.3 on 2022-04-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_alter_sector_category'),
        ('data', '0059_canteen_line_ministry_sector_has_line_ministry'),
    ]

    operations = [
    ]
