# Generated by Django 4.0.3 on 2022-04-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_alter_user_email_no_canteen_first_reminder_and_more'),
        ('data', '0061_alter_canteen_line_ministry'),
    ]

    operations = [
    ]
