# Generated by Django 4.0.4 on 2022-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_alter_canteen_line_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro téléphone'),
        ),
    ]
