# Generated by Django 4.0.4 on 2022-04-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_merge_20220414_1128'),
        ('data', '0062_user_phone_number'),
    ]

    operations = [
    ]
