# Generated by Django 4.0.4 on 2022-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0064_canteen_creation_campaign"),
    ]

    operations = [
        migrations.RenameField(
            model_name="canteen",
            old_name="creation_campaign",
            new_name="import_source",
        ),
        migrations.AlterField(
            model_name="canteen",
            name="import_source",
            field=models.TextField(blank=True, null=True, verbose_name="Source de l'import de la cantine"),
        ),
    ]
