# Generated by Django 4.0.4 on 2022-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_canteen_creation_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('ESTABLISHMENT_MANAGER', "Gestionnaire d'établissement"), ('CATERING_PURCHASES_MANAGER', 'Direction Achat Société de restauration'), ('DIRECT_PURCHASES_MANAGER', "Responsable d'achats en gestion directe"), ('CENTRAL_MANAGER', 'Responsable de plusieurs établissements (type cuisine centrale)'), ('MANY_ESTABLISHMENTS_MANAGER', 'Responsable de plusieurs établissements (SRC)'), ('OTHER', 'Autre')], max_length=255, null=True, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_job_description',
            field=models.TextField(blank=True, null=True, verbose_name='autre fonction détail'),
        ),
    ]
