# Generated by Django 4.0.4 on 2022-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_remove_canteen_creation_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='creation_mtm_campaign',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_campaign du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='creation_mtm_medium',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_medium du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='creation_mtm_source',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_source du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='creation_mtm_campaign',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_campaign du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='creation_mtm_medium',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_medium du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='creation_mtm_source',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_source du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_mtm_campaign',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_campaign du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_mtm_medium',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_medium du lien tracké lors de la création'),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_mtm_source',
            field=models.TextField(blank=True, null=True, verbose_name='mtm_source du lien tracké lors de la création'),
        ),
    ]
