# Generated by Django 4.0.4 on 2022-05-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_user_job_user_other_job_description'),
        ('data', '0066_canteen_creation_mtm_campaign_and_more'),
    ]

    operations = [
    ]
