# Generated by Django 4.0.4 on 2022-05-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_canteen_email_no_diagnostic_first_reminder'),
        ('data', '0067_merge_20220506_1438'),
    ]

    operations = [
    ]
