# Generated by Django 4.0.4 on 2022-05-12 07:38

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0069_vegetarianexpe_cost_per_meal_vg_t0_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vegetarianexpe",
            name="difficulties_daily_option_t0",
        ),
        migrations.AddField(
            model_name="vegetarianexpe",
            name="difficulties_daily_option_t0",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("formation", "Difficultés d'accès à la formation"),
                        ("appro", "Difficultés d'approvisionnement"),
                        ("recipes", "Manque de recettes"),
                        ("cost", "Surcoût des produits"),
                        ("clients", "Réaction des convives"),
                        ("overwork", "Surcharge de travail pour le personnel"),
                        ("other", "Autre"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Principaux freins rencontrés à la mise en place de l’option végétarienne quotidienne",
            ),
        ),
        migrations.RemoveField(
            model_name="vegetarianexpe",
            name="difficulties_daily_option_t1",
        ),
        migrations.AddField(
            model_name="vegetarianexpe",
            name="difficulties_daily_option_t1",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("formation", "Difficultés d'accès à la formation"),
                        ("appro", "Difficultés d'approvisionnement"),
                        ("recipes", "Manque de recettes"),
                        ("cost", "Surcoût des produits"),
                        ("clients", "Réaction des convives"),
                        ("overwork", "Surcharge de travail pour le personnel"),
                        ("other", "Autre"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Principaux freins rencontrés à la mise en place de l’option végétarienne quotidienne",
            ),
        ),
    ]
