# Generated by Django 4.0.4 on 2022-05-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_user_other_source_description_user_source'),
        ('data', '0070_alter_vegetarianexpe_difficulties_daily_option_t0_and_more'),
    ]

    operations = [
    ]
