# Generated by Django 4.0.4 on 2022-05-20 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_user_number_of_managed_cantines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(verbose_name='score')),
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='suggestion')),
                ('page', models.CharField(max_length=100, verbose_name='page')),
                ('hasCanteen', models.BooleanField(default=False, verbose_name="eu une cantine au moment de l'évaluation")),
                ('hasDiagnostic', models.BooleanField(default=False, verbose_name="eu un diagnostic au moment de l'évaluation")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'évaluation du site',
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'page'), name='one_review_per_page'),
        ),
    ]
