# Generated by Django 4.0.4 on 2022-05-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_user_number_of_managed_cantines'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='import_source',
            field=models.TextField(blank=True, null=True, verbose_name="Source de l'import du produit"),
        ),
    ]
