# Generated by Django 4.0.4 on 2022-05-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_vegetarianexpe_share_results'),
        ('data', '0074_alter_review_rating'),
    ]

    operations = [
    ]
