# Generated by Django 4.0.4 on 2022-06-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_purchase_import_source'),
        ('data', '0075_merge_20220530_1100'),
    ]

    operations = [
    ]
