# Generated by Django 4.0.4 on 2022-06-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_merge_20220530_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(verbose_name='titre')),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('end_date', models.DateTimeField(verbose_name='date de fin')),
                ('tagline', models.TextField(blank=True, null=True, verbose_name='description courte')),
                ('link', models.TextField(verbose_name="lien pour s'inscrire")),
            ],
            options={
                'verbose_name': 'événement',
                'ordering': ['start_date'],
            },
        ),
    ]
