# Generated by Django 4.0.4 on 2022-06-06 22:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_merge_20220530_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(verbose_name='titre')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="date de l'événement")),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('link', models.TextField(blank=True, null=True, verbose_name='lien')),
            ],
            options={
                'verbose_name': 'événement',
                'ordering': ['date'],
            },
        ),
    ]
