# Generated by Django 4.0.4 on 2022-06-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_communityevent'),
        ('data', '0076_merge_20220601_1220'),
    ]

    operations = [
    ]
