# Generated by Django 4.0.5 on 2022-06-13 13:22

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_merge_0076_communityevent_0076_merge_20220601_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, choices=[('VIANDES_VOLAILLES', 'Viandes, volailles'), ('PRODUITS_DE_LA_MER', 'Produits de la mer'), ('FRUITS_ET_LEGUMES', 'Fruits, légumes, légumineuses et oléagineux'), ('PRODUITS_CEREALIERS', 'Produits céréaliers'), ('ENTREES', 'Entrées et plats composés'), ('PRODUITS_LAITIERS', 'Lait et produits laitiers'), ('BOISSONS', 'Boissons'), ('AIDES', 'Aides culinaires et ingrédients divers'), ('BEURRE_OEUF_FROMAGE', 'Beurre, oeuf, fromage'), ('PRODUITS_SUCRES', 'Produits sucrés'), ('ALIMENTS_INFANTILES', 'Aliments infantiles'), ('GLACES_SORBETS', 'Glaces et sorbets'), ('AUTRES', 'Autres')], max_length=255, null=True, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='characteristics',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('BIO', 'Bio'), ('CONVERSION_BIO', 'En conversion bio'), ('LABEL_ROUGE', 'Label rouge'), ('AOCAOP', 'AOC / AOP'), ('ICP', 'Indication géographique protégée'), ('STG', 'Spécialité traditionnelle garantie'), ('HVE', 'Haute valeur environnementale'), ('PECHE_DURABLE', 'Pêche durable'), ('RUP', 'Région ultrapériphérique'), ('FERMIER', 'Fermier'), ('EXTERNALITES', 'Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie'), ('COMMERCE_EQUITABLE', 'Commerce équitable'), ('PERFORMANCE', 'Produits acquis sur la base de leurs performances en matière environnementale'), ('EQUIVALENTS', 'Produits équivalents'), ('FRANCE', 'Provenance France'), ('SHORT_DISTRIBUTION', 'Circuit-court'), ('LOCAL', 'Produit local')], max_length=255, null=True, verbose_name='caractéristique'), blank=True, null=True, size=None, verbose_name='caractéristiques'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description du produit'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='import_source',
            field=models.TextField(blank=True, null=True, verbose_name="source de l'import du produit"),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='prix HT'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='provider',
            field=models.TextField(blank=True, null=True, verbose_name='fournisseur'),
        ),
    ]
