# Generated by Django 4.0.5 on 2022-06-14 15:29

from django.db import migrations, models


def migrate_product_family(apps, schema_editor):
    Purchase = apps.get_model("data", "Purchase")
    mapping = {
        "VIANDES_VOLAILLES": "VIANDES_VOLAILLES",
        "PRODUITS_DE_LA_MER": "PRODUITS_DE_LA_MER",
        "FRUITS_ET_LEGUMES": "AUTRES",
        "PRODUITS_CEREALIERS": "",
        "ENTREES": "AUTRES",
        "PRODUITS_LAITIERS": "PRODUITS_LAITIERS",
        "BOISSONS": "BOISSONS",
        "AIDES": "AUTRES",
        "BEURRE_OEUF_FROMAGE": "PRODUITS_LAITIERS",
        "PRODUITS_SUCRES": "",
        "ALIMENTS_INFANTILES": "AUTRES",
        "GLACES_SORBETS": "AUTRES",
        "AUTRES": "AUTRES",
    }
    for purchase in Purchase.objects.all():
        if purchase.category and mapping[purchase.category]:
            purchase.family = mapping[purchase.category]
            purchase.save()


def undo_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0078_alter_purchase_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIANDES_VOLAILLES", "Viandes et volailles fraîches et surgelées"),
                    ("PRODUITS_DE_LA_MER", "Produits aquatiques frais et surgelés"),
                    ("PRODUITS_LAITIERS", "BOF (Produits laitiers, beurre et œufs)"),
                    ("BOULANGERIE", "Boulangerie/Pâtisserie fraîches"),
                    ("BOISSONS", "Boissons"),
                    ("AUTRES", "Autres produits frais, surgelés et d’épicerie"),
                ],
                max_length=255,
                null=True,
                verbose_name="famille de produits",
            ),
        ),
        migrations.RunPython(migrate_product_family, undo_migrate),
    ]
