# Generated by Django 4.0.5 on 2022-07-06 14:18

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_remove_diagnostic_value_autres_equivalents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='characteristics',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('BIO', 'Bio'), ('LABEL_ROUGE', 'Label rouge'), ('AOCAOP', 'AOC / AOP'), ('ICP', 'Indication géographique protégée'), ('STG', 'Spécialité traditionnelle garantie'), ('HVE', 'Haute valeur environnementale'), ('PECHE_DURABLE', 'Pêche durable'), ('RUP', 'Région ultrapériphérique'), ('FERMIER', 'Fermier'), ('EXTERNALITES', 'Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie'), ('COMMERCE_EQUITABLE', 'Commerce équitable'), ('PERFORMANCE', 'Produits acquis sur la base de leurs performances en matière environnementale'), ('FRANCE', 'Provenance France'), ('SHORT_DISTRIBUTION', 'Circuit-court'), ('LOCAL', 'Produit local')], max_length=255, null=True, verbose_name='caractéristique'), blank=True, null=True, size=None, verbose_name='caractéristiques'),
        ),
    ]
