# Generated by Django 4.0.6 on 2022-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0081_remove_diagnostic_value_autres_equivalents_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="diagnostic", old_name="value_sustainable_ht", new_name="value_siqo_ht"),
        migrations.AlterField(
            model_name="diagnostic",
            name="value_siqo_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Produits SIQO (hors bio) - Valeur annuelle HT",
            ),
        ),
    ]
