# Generated by Django 4.0.6 on 2022-07-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_remove_diagnostic_value_autres_equivalents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='value_egalim_others_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur totale (HT) des autres achats EGAlim'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_externality_performance_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur totale (HT) prenant en compte les coûts imputés aux externalités environnementales ou leurs performances en matière environnementale'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_fish_egalim_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur totale (HT) poissons et produits aquatiques EGAlim'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_fish_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur totale (HT) poissons et produits aquatiques'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_meat_poultry_egalim_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur totale (HT) viandes et volailles fraiches ou surgelées EGAlim'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_meat_poultry_france_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur totale (HT) viandes et volailles fraiches ou surgelées provenance France'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_meat_poultry_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valeur totale (HT) viandes et volailles fraiches ou surgelées'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_sustainable_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Produits SIQO (hors bio) - Valeur annuelle HT'),
        ),
    ]
