# Generated by Django 4.0.6 on 2022-07-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_rename_value_label_aoc_igp_diagnostic_value_aocaop_igp_stg_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='value_commerce_equitable_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Commerce équitable'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_externalites_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_fermier_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Fermier'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_france_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Provenance France'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_local_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Produit local'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_peche_durable_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Pêche durable'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_performance_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Produits acquis sur la base de leurs performances en matière environnementale'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_rup_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Région ultrapériphérique'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='value_short_distribution_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Circuit-court'),
        ),
    ]
