# Generated by Django 4.0.6 on 2022-07-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_diagnostic_value_commerce_equitable_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='diagnostic_type',
            field=models.CharField(blank=True, choices=[('SIMPLE', 'Télédeclaration simple'), ('INTERMEDIATE', 'Télédeclaration intermédiaire'), ('COMPLETE', 'Télédeclaration complète')], max_length=255, null=True, verbose_name='Type de diagnostic (simplifié, intermediaire, complet)'),
        ),
    ]
