# Generated by Django 4.0.6 on 2022-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_diagnostic_diagnostic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_out_reminder_emails',
            field=models.BooleanField(default='False', verbose_name='Désactiver les emails de rappel'),
        ),
    ]
