# Generated by Django 4.1 on 2022-08-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0085_alter_message_destination_canteen"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="geolocation_bot_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
