# Generated by Django 4.1 on 2022-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0086_canteen_geolocation_bot_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="value_autres_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Autres produits frais, surgelés et d’épicerie, non-EGAlim.",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_boissons_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Boissons, non-EGAlim.",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_boulangerie_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Boulangerie/Pâtisserie fraîches, non-EGAlim.",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_charcuterie_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Charcuterie, non-EGAlim.",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_fruits_et_legumes_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Fruits et légumes frais et surgelés, non-EGAlim.",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_produits_de_la_mer_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Produits aquatiques frais et surgelés, non-EGAlim.",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_produits_laitiers_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="BOF (Produits laitiers, beurre et œufs), non-EGAlim.",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_viandes_volailles_non_egalim",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Viandes et volailles fraîches et surgelées, non-EGAlim.",
            ),
        ),
    ]
