# Generated by Django 4.1 on 2022-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0088_partnertype_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Site web"),
        ),
    ]
