# Generated by Django 4.1 on 2022-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0091_alter_partner_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="published",
            field=models.BooleanField(default=False, verbose_name="publié"),
        ),
    ]
