# Generated by Django 4.1 on 2022-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0091_alter_partner_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_dev",
            field=models.BooleanField(
                default="False", verbose_name="Compte développeur / technique"
            ),
        ),
    ]
