# Generated by Django 4.1 on 2022-09-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0092_partner_published"),
        ("data", "0092_user_is_dev"),
    ]

    operations = []
