# Generated by Django 4.1 on 2022-09-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0093_merge_0092_partner_published_0092_user_is_dev"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="yearly_meal_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="repas par an (cuisines centrales)"
            ),
        ),
    ]
