# Generated by Django 4.1 on 2022-10-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0094_canteen_yearly_meal_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="yearly_meal_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="repas par an (y compris livrés)"
            ),
        ),
    ]
