# Generated by Django 4.1 on 2022-10-24 11:45

import data.fields
from django.db import migrations, models


def migrate_partner_categories(apps, schema_editor):
    Partner = apps.get_model("data", "Partner")
    for partner in Partner.objects.filter(categories__contains=["hygiene"]):
        partner.categories.remove("hygiene")
        partner.save()


def undo_migrate_partner_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0095_alter_canteen_yearly_meal_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="categories",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("appro", "Améliorer ma part de bio / durable"),
                        ("plastic", "Substituer mes plastiques"),
                        ("asso", "Donner à une association"),
                        ("waste", "Diagnostiquer mon gaspillage"),
                        ("training", "Me former ou former mon personnel"),
                        ("suivi", "Assurer mon suivi d'approvisionnement"),
                        ("vege", "Diversifier mes sources de protéines"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Besoin(s) comblé(s) par ce partenaire",
            ),
        ),
        migrations.RunPython(migrate_partner_categories, undo_migrate_partner_categories),
    ]
