# Generated by Django 4.1 on 2022-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0096_alter_partner_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="job",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTABLISHMENT_MANAGER", "Gestionnaire d'établissement"),
                    (
                        "CATERING_PURCHASES_MANAGER",
                        "Direction Achat Société de restauration",
                    ),
                    (
                        "DIRECT_PURCHASES_MANAGER",
                        "Responsable d'achats en gestion directe",
                    ),
                    (
                        "CENTRAL_MANAGER",
                        "Responsable de plusieurs établissements (type cuisine centrale)",
                    ),
                    (
                        "MANY_ESTABLISHMENTS_MANAGER",
                        "Responsable de plusieurs établissements (SRC)",
                    ),
                    (
                        "TECHNICAL",
                        "Développement logiciel, analyse de données ou autre rôle technique",
                    ),
                    ("OTHER", "Autre"),
                ],
                max_length=255,
                null=True,
                verbose_name="Fonction",
            ),
        ),
    ]
