# Generated by Django 4.1.3 on 2022-11-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0097_alter_user_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="includes_all_satellites",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Inclut les données d'approvisionnement de tous les satellites",
            ),
        ),
    ]
