# Generated by Django 4.1.3 on 2022-11-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0097_alter_user_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="central_kitchen_diagnostic_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "NO_SATELLITES",
                        "Ce diagnostic concerne le lieu de service de la cuisine centrale et non pas ses satellites",
                    ),
                    (
                        "APPRO",
                        "Ce diagnostic concerne les données d'approvisionnement de toutes les cantines satellites",
                    ),
                    (
                        "ALL",
                        "Ce diagnostic concerne toutes les données des cantines satellites",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="Type de diagnostic pour la cuisine centrale",
            ),
        ),
        migrations.AlterField(
            model_name="canteen",
            name="economic_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Public"),
                    ("private", "Privé"),
                    ("published", "✅ Publié"),
                ],
                max_length=50,
                null=True,
                verbose_name="Secteur économique",
            ),
        ),
    ]
