# Generated by Django 4.1.3 on 2022-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0098_diagnostic_central_kitchen_diagnostic_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teledeclaration",
            name="uses_central_kitchen_appro",
        ),
        migrations.AddField(
            model_name="teledeclaration",
            name="teledeclaration_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "SATELLITE_WITHOUT_APPRO",
                        "Cantine satellite dont les données d'appro sont déclarées par la cuisine centrale",
                    ),
                    (
                        "CENTRAL_APPRO",
                        "Cuisine centrale déclarant les données d'appro pour ses cuisines satellites",
                    ),
                    (
                        "CENTRAL_ALL",
                        "Cuisine centrale déclarant toutes les données EGAlim pour ses cuisines satellites",
                    ),
                    ("SITE", "Cantine déclarant ses propres données"),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de télédéclaration",
            ),
        ),
    ]
