# Generated by Django 4.1.3 on 2022-11-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0099_alter_diagnostic_central_kitchen_diagnostic_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="teledeclaration",
            name="uses_central_kitchen_appro",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Cantine satellite dont les données d'appro ont été prises en charge par la cuisine centrale",
            ),
        ),
    ]
