# Generated by Django 4.1.3 on 2023-02-10 09:30

import data.models.teledeclaration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0100_alter_diagnostic_central_kitchen_diagnostic_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teledeclaration",
            name="declared_data",
            field=models.JSONField(
                encoder=data.models.teledeclaration.CustomJSONEncoder,
                verbose_name="Champs",
            ),
        ),
    ]
