# Generated by Django 4.1.3 on 2023-02-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0101_alter_teledeclaration_declared_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="economic_model",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("private", "Privé")],
                max_length=50,
                null=True,
                verbose_name="Secteur économique",
            ),
        ),
    ]
