# Generated by Django 4.1 on 2023-02-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0102_alter_canteen_economic_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanteenSectorRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.canteen"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.sector"
                    ),
                ),
            ],
        ),
    ]
