# Generated by Django 4.1 on 2023-02-17 15:37
import datetime

from django.db import migrations

# Thank you https://stackoverflow.com/a/51351406/3845770
def create_through_relations(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")
    CanteenSectorRelation = apps.get_model("data", "CanteenSectorRelation")
    for canteen in Canteen.objects.all():
        for sector in canteen.sectors.all():
            CanteenSectorRelation(
                sector=sector,
                canteen=canteen,
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0103_canteensectorrelation"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
