# Generated by Django 4.1.7 on 2023-03-30 15:05

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0103_alter_canteen_publication_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoTutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(verbose_name="titre")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="publié"),
                ),
                ("video", models.FileField(upload_to="videos/", verbose_name="vidéo")),
                (
                    "categories",
                    data.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("technical", "Technique"),
                                ("transition", "Transition alimentaire"),
                                ("profile", "Je suis..."),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="aperçu"
                    ),
                ),
            ],
            options={
                "verbose_name": "tutoriel vidéo",
                "verbose_name_plural": "tutoriels vidéo",
            },
        ),
    ]
