# Generated by Django 4.1 on 2023-02-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0104_migrate_canteen_sectors_to_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canteen",
            name="sectors",
        ),
    ]
