# Generated by Django 4.1.7 on 2023-04-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0105_alter_canteen_central_producer_siret"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_with_mcp",
            field=models.BooleanField(
                default="False", verbose_name="Compte créé avec MonComptePro"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mcp_id",
            field=models.TextField(
                blank=True, null=True, verbose_name="ID MonComptePro"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mcp_organizations",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Organisations sous MonComptePro"
            ),
        ),
    ]
