# Generated by Django 4.1.7 on 2023-04-28 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0105_alter_canteen_central_producer_siret"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET("deleted user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="Personne qui a revendiqué la cantine",
            ),
        ),
    ]
