# Generated by Django 4.1 on 2023-02-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0105_remove_canteen_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="sectors",
            field=models.ManyToManyField(
                through="data.CanteenSectorRelation", to="data.sector"
            ),
        ),
    ]
