# Generated by Django 4.1.7 on 2023-04-28 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0104_historicalcanteen"),
        ("data", "0105_alter_canteen_central_producer_siret"),
    ]

    operations = []
