# Generated by Django 4.1.7 on 2023-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0106_canteen_claimed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="has_been_claimed",
            field=models.BooleanField(
                default=False, verbose_name="cette cantine a été revendiquée"
            ),
        ),
        migrations.AlterField(
            model_name="canteen",
            name="reservation_expe_participant",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="participante à l'expérimentation réservation",
            ),
        ),
        migrations.AlterField(
            model_name="canteen",
            name="vegetarian_expe_participant",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="participante à l'expérimentation repas végétariens",
            ),
        ),
    ]
