# Generated by Django 4.1.7 on 2023-05-03 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0107_canteen_has_been_claimed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Personne qui a revendiqué la cantine",
            ),
        ),
    ]
