# Generated by Django 4.1.7 on 2023-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0108_alter_canteen_claimed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="deletion_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de suppression par l'utilisateur",
            ),
        ),
    ]
