# Generated by Django 4.1.7 on 2023-05-04 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0106_user_created_with_mcp_user_mcp_id_and_more"),
        ("data", "0108_alter_canteen_claimed_by"),
    ]

    operations = []
