# Generated by Django 4.2.1 on 2023-05-11 13:33

import data.fields
from django.db import migrations, models

def migrate_igp_typo(apps, schema_editor):
    Purchase = apps.get_model("data", "Purchase")
    for purchase in Purchase.objects.filter(characteristics__contains=["ICP"]):
        purchase.characteristics.remove("ICP")
        purchase.characteristics.append("IGP")
        purchase.save()

def undo_migrate_igp_typo(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0109_merge_20230504_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="characteristics",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("BIO", "Bio"),
                        ("CONVERSION_BIO", "En conversion bio"),
                        ("LABEL_ROUGE", "Label rouge"),
                        ("AOCAOP", "AOC / AOP"),
                        ("IGP", "Indication géographique protégée"),
                        ("STG", "Spécialité traditionnelle garantie"),
                        ("HVE", "Haute valeur environnementale"),
                        ("PECHE_DURABLE", "Pêche durable"),
                        ("RUP", "Région ultrapériphérique"),
                        ("FERMIER", "Fermier"),
                        (
                            "EXTERNALITES",
                            "Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie",
                        ),
                        ("COMMERCE_EQUITABLE", "Commerce équitable"),
                        (
                            "PERFORMANCE",
                            "Produits acquis sur la base de leurs performances en matière environnementale",
                        ),
                        ("EQUIVALENTS", "Produits équivalents"),
                        ("FRANCE", "Provenance France"),
                        ("SHORT_DISTRIBUTION", "Circuit-court"),
                        ("LOCAL", "Produit local"),
                    ],
                    max_length=255,
                    null=True,
                    verbose_name="caractéristique",
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="caractéristiques",
            ),
        ),
        migrations.RunPython(migrate_igp_typo, undo_migrate_igp_typo),
    ]
