# Generated by Django 4.2.1 on 2023-05-15 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0109_purchase_deletion_date"),
        ("data", "0110_alter_purchase_characteristics"),
    ]

    operations = []
