# Generated by Django 4.2.1 on 2023-05-30 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0107_alter_historicalcanteen_central_producer_siret"),
        ("data", "0111_merge_20230515_1046"),
    ]

    operations = []
