# Generated by Django 4.2.1 on 2023-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0114_historicaldiagnostic"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teledeclaration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SUBMITTED")),
                fields=("year", "canteen"),
                name="unique_submitted_td",
            ),
        ),
    ]
