# Generated by Django 4.2.1 on 2023-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0115_teledeclaration_unique_submitted_td"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="teledeclaration",
            index=models.Index(
                fields=["canteen", "year"], name="data_telede_canteen_c2ff43_idx"
            ),
        ),
    ]
