# Generated by Django 4.2.1 on 2023-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0116_teledeclaration_data_telede_canteen_c2ff43_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="canteen",
            index=models.Index(
                fields=["central_producer_siret"], name="data_cantee_central_5c2299_idx"
            ),
        ),
    ]
