# Generated by Django 4.2.3 on 2023-07-17 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0118_purchase_data_purcha_canteen_ac0038_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="purchase",
            name="data_purcha_canteen_ac0038_idx",
        ),
    ]
