# Generated by Django 4.2.3 on 2023-07-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0119_remove_purchase_data_purcha_canteen_ac0038_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, to="data.sector", verbose_name="secteurs d'activité"
            ),
        ),
    ]
