# Generated by Django 4.2.3 on 2023-07-27 15:33

from django.db import migrations, models

def migrate_gratuity_option(apps, schema_editor):
    Partner = apps.get_model('data', 'Partner')
    for partner in Partner.objects.filter(free__isnull=False):
        partner.gratuity_option = "free" if partner.free else "paid"
        partner.save()

def undo_migrate_gratuity_option(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0120_partner_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="gratuity_option",
            field=models.CharField(
                blank=True,
                choices=[("free", "Gratuit"), ("paid", "Payant"), ("mix", "Mixte")],
                max_length=50,
                null=True,
                verbose_name="Type d'offre",
            ),
        ),
        migrations.RunPython(migrate_gratuity_option, undo_migrate_gratuity_option),
        migrations.RemoveField(
            model_name="partner",
            name="free",
        ),
    ]
