# Generated by Django 4.2.3 on 2023-07-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0120_partner_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="contact_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Commentaires sur la demande"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="contact_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nom de contact"
            ),
        ),
    ]
