# Generated by Django 4.2.3 on 2023-08-01 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0121_partner_contact_email_partner_contact_message_and_more"),
        ("data", "0121_remove_partner_free_partner_gratuity_option"),
    ]

    operations = []
