# Generated by Django 4.2.3 on 2023-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0123_partner_contact_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="videotutorial",
            name="subtitles",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="subtitles/",
                verbose_name="sous-titres",
            ),
        ),
    ]
