# Generated by Django 4.2.4 on 2023-08-18 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0124_videotutorial_subtitles"),
        ("data", "0125_rename_is_elected_user_is_elected_official"),
    ]

    operations = []
