# Generated by Django 4.2.4 on 2023-08-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0124_alter_partner_categories"),
        ("data", "0126_merge_20230818_1308"),
    ]

    operations = []
