# Generated by Django 4.2.6 on 2023-11-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0128_partner_sector_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="tunnel_appro",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel appro",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tunnel_diversification",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel diversification",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tunnel_info",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel information convives",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tunnel_plastic",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel anti-plastique",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tunnel_waste",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel anti-gaspi",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="tunnel_appro",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel appro",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="tunnel_diversification",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel diversification",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="tunnel_info",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel information convives",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="tunnel_plastic",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel anti-plastique",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="tunnel_waste",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Progrès tunnel anti-gaspi",
            ),
        ),
    ]
