# Generated by Django 4.2.7 on 2023-11-18 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0129_alter_canteen_line_ministry_and_more"),
        ("data", "0130_diagnostic_creation_source_and_more"),
    ]

    operations = []
