# Generated by Django 4.2.7 on 2024-01-18 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0133_alter_diagnostic_vegetarian_weekly_recurrence_and_more"),
        ("data", "0133_diagnostic_duration_leftovers_measurement_and_more"),
    ]

    operations = []
