# Generated by Django 4.2.7 on 2024-01-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0134_merge_20240118_1110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="total_leftovers",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=20,
                null=True,
                verbose_name="total des déchets alimentaires (t)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="total_leftovers",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=20,
                null=True,
                verbose_name="total des déchets alimentaires (t)",
            ),
        ),
    ]
