# Generated by Django 4.2.7 on 2024-01-26 10:55

import data.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0134_merge_20240118_1110"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTeledeclaration",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "declared_data",
                    models.JSONField(
                        encoder=data.utils.CustomJSONEncoder,
                        verbose_name="Champs",
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                ("year", models.IntegerField(verbose_name="année")),
                (
                    "status",
                    models.CharField(
                        choices=[("SUBMITTED", "Télédéclaré"), ("CANCELLED", "Annulé")],
                        max_length=255,
                        verbose_name="status",
                    ),
                ),
                ("canteen_siret", models.TextField(blank=True, null=True)),
                (
                    "teledeclaration_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "SATELLITE_WITHOUT_APPRO",
                                "Cantine satellite dont les données d'appro sont déclarées par la cuisine centrale",
                            ),
                            (
                                "CENTRAL_APPRO",
                                "Cuisine centrale déclarant les données d'appro pour ses cuisines satellites",
                            ),
                            (
                                "CENTRAL_ALL",
                                "Cuisine centrale déclarant toutes les données EGAlim pour ses cuisines satellites",
                            ),
                            ("SITE", "Cantine déclarant ses propres données"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="mode de télédéclaration",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="déclarant",
                    ),
                ),
                (
                    "canteen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.canteen",
                        verbose_name="cantine",
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.diagnostic",
                        verbose_name="diagnostic",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical télédéclaration",
                "verbose_name_plural": "historical télédéclarations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
