# Generated by Django 4.2.7 on 2024-01-30 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0135_alter_diagnostic_total_leftovers_and_more"),
        ("data", "0135_historicalteledeclaration"),
    ]

    operations = []
