# Generated by Django 4.2.10 on 2024-03-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0136_merge_20240130_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteenimage",
            name="alt_text",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="texte alternatif pour les utilisateurs qui voient pas l'image",
            ),
        ),
    ]
