# Generated by Django 4.2.10 on 2024-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0136_merge_20240130_1205"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="canteen",
            index=models.Index(fields=["siret"], name="data_cantee_siret_067f92_idx"),
        ),
    ]
