# Generated by Django 4.2.10 on 2024-03-04 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0137_canteen_data_cantee_siret_067f92_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "modification_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="import-errors/%Y/%m/%d/",
                        verbose_name="fichier",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="détails"),
                ),
                (
                    "import_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            (
                                "CANTEEN_ONLY_OR_DIAGNOSTIC_SIMPLE",
                                "Canteen only or simple diagnostic",
                            ),
                            ("DIAGNOSTIC_COMPLETE", "Diagnostic complete"),
                            ("CC_SIMPLE", "Central kitchen simple"),
                            ("CC_COMPLETE", "Central kitchen complete"),
                            ("PURCHASE", "Purchase"),
                        ],
                        null=True,
                        verbose_name="type d'import",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
        ),
    ]
