# Generated by Django 4.2.10 on 2024-03-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0139_rename_importerror_importfailure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importfailure",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    (
                        "CANTEEN_ONLY_OR_DIAGNOSTIC_SIMPLE",
                        "Cantines seules ou avec un diagnostic simple",
                    ),
                    ("DIAGNOSTIC_COMPLETE", "Cantines avec diagnostic complet"),
                    (
                        "CC_SIMPLE",
                        "Cuisines centrales avec un diagnostic simple et leurs satellites",
                    ),
                    (
                        "CC_COMPLETE",
                        "Cuisines centrales avec un diagnostic complet et leurs satellites",
                    ),
                    ("PURCHASE", "Achats"),
                ],
                null=True,
                verbose_name="type d'import",
            ),
        ),
    ]
