# Generated by Django 4.2.10 on 2024-03-07 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0137_canteenimage_alt_text"),
        ("data", "0140_alter_importfailure_import_type"),
    ]

    operations = []
