# Generated by Django 5.0.3 on 2024-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0141_merge_20240307_1032"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_brevo_update",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de la dernière mise à jour Brevo",
            ),
        ),
    ]
