# Generated by Django 5.0.3 on 2024-04-02 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0142_user_last_brevo_update"),
        ("data", "0142_videotutorial_transcription"),
    ]

    operations = []
