# Generated by Django 5.0.3 on 2024-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0143_merge_20240402_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="publication_status",
            field=models.CharField(
                choices=[("draft", "🔒 Non publié"), ("published", "✅ Publié")],
                default="published",
                max_length=50,
                verbose_name="état de publication",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="publication_status",
            field=models.CharField(
                choices=[("draft", "🔒 Non publié"), ("published", "✅ Publié")],
                default="published",
                max_length=50,
                verbose_name="état de publication",
            ),
        ),
    ]
