# Generated by Django 5.0.3 on 2024-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0143_merge_20240402_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Livreur des repas sans lieu de consommation"),
                    (
                        "central_serving",
                        "Livreur des repas qui accueille aussi des convives sur place",
                    ),
                    ("site", "Cantine qui produit les repas sur place"),
                    (
                        "site_cooked_elsewhere",
                        "Cantine qui sert des repas preparés par une cuisine centrale",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Livreur des repas sans lieu de consommation"),
                    (
                        "central_serving",
                        "Livreur des repas qui accueille aussi des convives sur place",
                    ),
                    ("site", "Cantine qui produit les repas sur place"),
                    (
                        "site_cooked_elsewhere",
                        "Cantine qui sert des repas preparés par une cuisine centrale",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
        migrations.AlterField(
            model_name="importfailure",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    (
                        "CANTEEN_ONLY_OR_DIAGNOSTIC_SIMPLE",
                        "Cantines seules ou avec un diagnostic simple",
                    ),
                    ("DIAGNOSTIC_COMPLETE", "Cantines avec diagnostic complet"),
                    (
                        "CC_SIMPLE",
                        "Livreurs avec un diagnostic simple et leurs satellites",
                    ),
                    (
                        "CC_COMPLETE",
                        "Livreurs avec un diagnostic complet et leurs satellites",
                    ),
                    ("PURCHASE", "Achats"),
                ],
                null=True,
                verbose_name="type d'import",
            ),
        ),
    ]
