# Generated by Django 5.0.3 on 2024-05-07 12:23

from django.db import migrations, models


def migrate_auth_method(apps, schema_editor):
    HistoricalTeledeclaration = apps.get_model("data", "historicalteledeclaration")
    for td in HistoricalTeledeclaration.objects.filter(
        history_change_reason__isnull=True, history_user__is_staff=True
    ):
        td.authentication_method = "ADMIN"
        td.save()

    for td in HistoricalTeledeclaration.objects.filter(history_change_reason__isnull=False):
        if td.history_change_reason == "SessionAuthentication":
            td.authentication_method = "WEBSITE"
            td.history_change_reason = None
        elif td.history_change_reason == "OAuth2Authentication":
            td.authentication_method = "API"
            td.history_change_reason = None
        elif td.history_change_reason.startswith("Mass CSV import"):
            td.authentication_method = "WEBSITE"
        elif td.history_change_reason.startswith("Données de localisation MAJ"):
            td.authentication_method = "AUTO"
        td.save()


def undo_migrate_auth_method(apps, schema_editor):
    HistoricalTeledeclaration = apps.get_model("data", "historicalteledeclaration")
    for td in HistoricalTeledeclaration.objects.filter(authentication_method__isnull=False):
        if td.authentication_method == "WEBSITE" or td.authentication_method == "ADMIN":
            td.history_change_reason = "SessionAuthentication"
        elif td.authentication_method == "API":
            td.history_change_reason = "OAuth2Authentication"
        td.save()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0143_merge_20240402_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalteledeclaration",
            name="authentication_method",
            field=models.CharField(
                choices=[
                    ("WEBSITE", "Via la plateforme en ligne"),
                    ("API", "Via une intégration API"),
                    ("AUTO", "Via un script ou bot interne"),
                    ("ADMIN", "Via site admin"),
                ],
                max_length=255,
                null=True,
                verbose_name="méthode d'authentification",
            ),
        ),
        migrations.RunPython(migrate_auth_method, undo_migrate_auth_method),
    ]
