# Generated by Django 5.0.3 on 2024-05-14 15:30

import data.fields
import data.models.canteen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0143_merge_20240402_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="redacted_appro_years",
            field=data.fields.ChoiceArrayField(
                base_field=models.IntegerField(
                    choices=data.models.canteen.get_diagnostic_year_choices
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="les années pour lesquelles les données d'appro sont masquées",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="redacted_appro_years",
            field=data.fields.ChoiceArrayField(
                base_field=models.IntegerField(
                    choices=data.models.canteen.get_diagnostic_year_choices
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="les années pour lesquelles les données d'appro sont masquées",
            ),
        ),
    ]
