# Generated by Django 5.0.3 on 2024-05-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0144_canteen_redacted_appro_years_and_more"),
        ("data", "0144_historicalteledeclaration_authentication_method"),
    ]

    operations = []
