# Generated by Django 5.0.3 on 2024-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0144_canteen_redacted_appro_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalteledeclaration",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Télédéclaré"),
                    ("VOIDED", "À corriger"),
                    ("CANCELLED", "Annulé"),
                ],
                max_length=255,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="teledeclaration",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Télédéclaré"),
                    ("VOIDED", "À corriger"),
                    ("CANCELLED", "Annulé"),
                ],
                max_length=255,
                verbose_name="status",
            ),
        ),
    ]
