# Generated by Django 5.0.3 on 2024-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0145_merge_20240527_1738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalteledeclaration",
            name="authentication_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEBSITE", "Via la plateforme en ligne"),
                    ("API", "Via une intégration API"),
                    ("AUTO", "Via un script ou bot interne"),
                    ("ADMIN", "Via site admin"),
                ],
                max_length=255,
                null=True,
                verbose_name="méthode d'authentification",
            ),
        ),
    ]
