# Generated by Django 5.0.6 on 2024-06-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0147_alter_canteen_line_ministry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="line_ministry",
            field=models.TextField(
                blank=True,
                choices=[
                    ("premier_ministre", "Services du Premier Ministre"),
                    (
                        "affaires_etrangeres",
                        "Ministère en charge des affaires étrangères",
                    ),
                    ("ecologie", "Ministère de la Transition écologique"),
                    (
                        "jeunesse",
                        "Ministère en charge de l'Éducation, de la Jeunesse et des Sports",
                    ),
                    ("economie", "Ministère en charge de l'Économie et des finances"),
                    ("armee", "Ministère des Armées"),
                    ("interieur", "Ministère de l’Intérieur"),
                    ("travail", "Ministère en charge du Travail"),
                    ("outre_mer", "Ministère des Outre-mer"),
                    (
                        "territoires",
                        "Ministère de la Cohésion des Territoires et des Relations avec les Collectivités Territoriales",
                    ),
                    ("justice", "Ministère de la Justice"),
                    ("culture", "Ministère de la Culture"),
                    ("sante", "Ministère en charge de la Santé et des Solidarités"),
                    ("mer", "Ministère de la Mer"),
                    (
                        "enseignement_superieur",
                        "Ministère en charge de l'Enseignement supérieur et de la Recherche",
                    ),
                    (
                        "agriculture",
                        "Ministère en charge de l'Agriculture et de l'Alimentation",
                    ),
                    (
                        "transformation",
                        "Ministère de la Transformation et de la Fonction Publiques",
                    ),
                    (
                        "administration_territoriale",
                        "Préfecture - Administration Territoriale de l'État (ATE)",
                    ),
                    (
                        "autorites_independantes",
                        "Présidence de la république - Autorités indépendantes (AAI, API)",
                    ),
                    ("autre", "Autre"),
                ],
                null=True,
                verbose_name="Ministère de tutelle",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="line_ministry",
            field=models.TextField(
                blank=True,
                choices=[
                    ("premier_ministre", "Services du Premier Ministre"),
                    (
                        "affaires_etrangeres",
                        "Ministère en charge des affaires étrangères",
                    ),
                    ("ecologie", "Ministère de la Transition écologique"),
                    (
                        "jeunesse",
                        "Ministère en charge de l'Éducation, de la Jeunesse et des Sports",
                    ),
                    ("economie", "Ministère en charge de l'Économie et des finances"),
                    ("armee", "Ministère des Armées"),
                    ("interieur", "Ministère de l’Intérieur"),
                    ("travail", "Ministère en charge du Travail"),
                    ("outre_mer", "Ministère des Outre-mer"),
                    (
                        "territoires",
                        "Ministère de la Cohésion des Territoires et des Relations avec les Collectivités Territoriales",
                    ),
                    ("justice", "Ministère de la Justice"),
                    ("culture", "Ministère de la Culture"),
                    ("sante", "Ministère en charge de la Santé et des Solidarités"),
                    ("mer", "Ministère de la Mer"),
                    (
                        "enseignement_superieur",
                        "Ministère en charge de l'Enseignement supérieur et de la Recherche",
                    ),
                    (
                        "agriculture",
                        "Ministère en charge de l'Agriculture et de l'Alimentation",
                    ),
                    (
                        "transformation",
                        "Ministère de la Transformation et de la Fonction Publiques",
                    ),
                    (
                        "administration_territoriale",
                        "Préfecture - Administration Territoriale de l'État (ATE)",
                    ),
                    (
                        "autorites_independantes",
                        "Présidence de la république - Autorités indépendantes (AAI, API)",
                    ),
                    ("autre", "Autre"),
                ],
                null=True,
                verbose_name="Ministère de tutelle",
            ),
        ),
    ]
