# Generated by Django 5.1 on 2024-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0149_historicalwastemeasurement_wastemeasurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="leftovers_edible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="restes assiette - masse comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="leftovers_inedible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="restes assiette - masse non-comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="leftovers_total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="restes assiette - masse totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="preparation_edible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="préparation - masse comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="preparation_inedible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="préparation - masse non-comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="preparation_total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="préparation - masse totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Masse totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="unserved_edible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="non-servi - masse comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="unserved_inedible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="non-servi - masse non-comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="unserved_total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="non-servi - masse totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="leftovers_edible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="restes assiette - masse comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="leftovers_inedible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="restes assiette - masse non-comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="leftovers_total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="restes assiette - masse totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="preparation_edible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="préparation - masse comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="preparation_inedible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="préparation - masse non-comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="preparation_total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="préparation - masse totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Masse totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="unserved_edible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="non-servi - masse comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="unserved_inedible_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="non-servi - masse non-comestible (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="unserved_total_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="non-servi - masse totale (kg)",
            ),
        ),
    ]
