# Generated by Django 5.0.8 on 2024-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0149_historicalwastemeasurement_wastemeasurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwastemeasurement",
            name="period_start_date",
            field=models.DateField(verbose_name="date de début"),
        ),
        migrations.AlterField(
            model_name="wastemeasurement",
            name="period_start_date",
            field=models.DateField(verbose_name="date de début"),
        ),
    ]
