# Generated by Django 5.0.8 on 2024-09-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0150_alter_historicalwastemeasurement_leftovers_edible_mass_and_more",
        ),
        ("data", "0150_alter_historicalwastemeasurement_options_and_more"),
    ]

    operations = []
