# Generated by Django 5.0.7 on 2024-09-12 10:55
# Fixes the SQL sequence of the data_wasteaction table
# https://stackoverflow.com/a/44113124


from django.db import migrations

# Reset the SQL sequence of the data_wasteaction table
# Extracted from sqlsequencereset command
SQL_COMMAND = """
BEGIN;
SELECT setval(pg_get_serial_sequence('"data_wasteaction"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "data_wasteaction";
COMMIT;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0152_wasteaction"),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_COMMAND, reverse_sql=migrations.RunSQL.noop),
    ]
