# Generated by Django 5.0.8 on 2024-09-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0152_wasteaction"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteaction",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
    ]
