# Generated by Django 5.0.7 on 2024-09-12 10:55
# Fixes the SQL sequence of the data_wasteaction table
# https://stackoverflow.com/a/44113124

from io import StringIO
from django.db import migrations
from django.core.management import call_command


def get_sql_sequence_reset(app_label):
    out = StringIO()
    call_command("sqlsequencereset", app_label, stdout=out, no_color=True)
    return out.getvalue()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0152_wasteaction"),
    ]

    operations = [
        migrations.RunSQL(get_sql_sequence_reset("data")),
    ]
