# Generated by Django 5.0.7 on 2024-09-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0153_reset_sql_sequences"),
        ("data", "0153_wasteaction_latest_revision"),
    ]

    operations = []
