# Generated by Django 5.0.7 on 2024-09-27 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0154_merge_20240916_1041"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "is_done",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="mis en place"
                    ),
                ),
                (
                    "is_not_interested",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="pas intéressé"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="favori"),
                ),
                (
                    "canteen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.canteen",
                        verbose_name="cantine",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.wasteaction",
                        verbose_name="ressource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "ressource : action utilisateur",
                "verbose_name_plural": "ressources : actions utilisateurs",
            },
        ),
    ]
