# Generated by Django 5.0.7 on 2024-10-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0154_merge_20240916_1041"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "is_done",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="mis en place"
                    ),
                ),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_actions",
                        to="data.canteen",
                        verbose_name="cantine",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="data.wasteaction",
                        verbose_name="ressource",
                    ),
                ),
            ],
            options={
                "verbose_name": "ressource : action (cantine)",
                "verbose_name_plural": "ressources : actions (cantines)",
                "unique_together": {("resource", "canteen")},
            },
        ),
    ]
