# Generated by Django 5.0.7 on 2024-11-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0156_historicalresourceaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresourceaction",
            name="is_favorite",
            field=models.BooleanField(blank=True, null=True, verbose_name="favori"),
        ),
        migrations.AddField(
            model_name="resourceaction",
            name="is_favorite",
            field=models.BooleanField(blank=True, null=True, verbose_name="favori"),
        ),
    ]
