# Generated by Django 5.0.8 on 2024-11-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0157_alter_canteen_production_type_and_more"),
        ("data", "0157_resourceaction_is_favorite_and_more"),
    ]

    operations = []
