# Generated by Django 5.0.8 on 2024-11-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0158_merge_20241106_1432"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created_with_mcp",
            new_name="created_with_proconnect",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="mcp_id",
            new_name="proconnect_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="mcp_organizations",
            new_name="proconnect_organizations",
        ),
        migrations.AlterField(
            model_name="user",
            name="created_with_proconnect",
            field=models.BooleanField(
                default="False",
                verbose_name="Compte créé avec ProConnect (ex. MonComptePro)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="proconnect_id",
            field=models.TextField(
                blank=True, null=True, verbose_name="ID ProConnect (ex. MonComptePro)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="proconnect_organizations",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Organisations sous ProConnect (ex. MonComptePro)",
            ),
        ),
    ]
