# Generated by Django 5.0.7 on 2024-11-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0158_merge_20241106_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="line_ministry",
            field=models.TextField(
                blank=True,
                choices=[
                    ("affaires_etrangeres", "Affaires étrangères"),
                    ("agriculture", "Agriculture, Alimentation et Forêts"),
                    ("armee", "Armées"),
                    (
                        "territoires",
                        "Cohésion des territoires - Relations avec les collectivités territoriales",
                    ),
                    ("culture", "Culture"),
                    ("economie", "Économie et finances"),
                    ("jeunesse", "Éducation et Jeunesse"),
                    ("enseignement_superieur", "Enseignement supérieur et Recherche"),
                    ("ecologie", "Environnement"),
                    ("transformation", "Fonction Publiques"),
                    ("interieur", "Intérieur et Outre-mer"),
                    ("justice", "Justice"),
                    ("mer", "Mer"),
                    (
                        "administration_territoriale",
                        "Préfecture - Administration Territoriale de l'État (ATE)",
                    ),
                    (
                        "autorites_independantes",
                        "Présidence de la république - Autorités indépendantes (AAI, API)",
                    ),
                    ("premier_ministre", "Services du Premier Ministre"),
                    ("sante", "Santé et Solidarités"),
                    ("sport", "Sport"),
                    ("travail", "Travail"),
                    ("outre_mer", "Ministère des Outre-mer"),
                    ("autre", "Autre"),
                ],
                null=True,
                verbose_name="Ministère de tutelle",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="line_ministry",
            field=models.TextField(
                blank=True,
                choices=[
                    ("affaires_etrangeres", "Affaires étrangères"),
                    ("agriculture", "Agriculture, Alimentation et Forêts"),
                    ("armee", "Armées"),
                    (
                        "territoires",
                        "Cohésion des territoires - Relations avec les collectivités territoriales",
                    ),
                    ("culture", "Culture"),
                    ("economie", "Économie et finances"),
                    ("jeunesse", "Éducation et Jeunesse"),
                    ("enseignement_superieur", "Enseignement supérieur et Recherche"),
                    ("ecologie", "Environnement"),
                    ("transformation", "Fonction Publiques"),
                    ("interieur", "Intérieur et Outre-mer"),
                    ("justice", "Justice"),
                    ("mer", "Mer"),
                    (
                        "administration_territoriale",
                        "Préfecture - Administration Territoriale de l'État (ATE)",
                    ),
                    (
                        "autorites_independantes",
                        "Présidence de la république - Autorités indépendantes (AAI, API)",
                    ),
                    ("premier_ministre", "Services du Premier Ministre"),
                    ("sante", "Santé et Solidarités"),
                    ("sport", "Sport"),
                    ("travail", "Travail"),
                    ("outre_mer", "Ministère des Outre-mer"),
                    ("autre", "Autre"),
                ],
                null=True,
                verbose_name="Ministère de tutelle",
            ),
        ),
    ]
