# Generated by Django 5.0.7 on 2024-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0159_alter_canteen_line_ministry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNIQUE", "Menu unique"),
                    ("MULTIPLE_SELF", "Choix multiple en libre-service"),
                    (
                        "MULTIPLE_RESERVATION",
                        "Choix multiple avec réservation à l’avance au jour le jour",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="type de service",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNIQUE", "Menu unique"),
                    ("MULTIPLE_SELF", "Choix multiple en libre-service"),
                    (
                        "MULTIPLE_RESERVATION",
                        "Choix multiple avec réservation à l’avance au jour le jour",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="type de service",
            ),
        ),
    ]
