# Generated by Django 5.0.7 on 2025-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0162_alter_diagnostic_value_autres_non_egalim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importfailure",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("CANTEEN_ONLY", "Cantines seules"),
                    (
                        "CANTEEN_ONLY_OR_DIAGNOSTIC_SIMPLE",
                        "Cantines seules ou avec un diagnostic simple",
                    ),
                    ("DIAGNOSTIC_SIMPLE", "Diagnostic simple"),
                    ("DIAGNOSTIC_COMPLETE", "Cantines avec diagnostic complet"),
                    (
                        "CC_SIMPLE",
                        "Livreurs avec un diagnostic simple et leurs satellites",
                    ),
                    (
                        "CC_COMPLETE",
                        "Livreurs avec un diagnostic complet et leurs satellites",
                    ),
                    ("PURCHASE", "Achats"),
                ],
                null=True,
                verbose_name="type d'import",
            ),
        ),
    ]
