# Generated by Django 5.0.7 on 2025-03-03 11:36

import common.utils.siret
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0163_importfailure_import_type_add_canteen_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="siren_unite_legale",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[common.utils.siret.validate_siren],
                verbose_name="siren de l'unité légale",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="siren_unite_legale",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[common.utils.siret.validate_siren],
                verbose_name="siren de l'unité légale",
            ),
        ),
    ]
