# Generated by Django 5.0.7 on 2025-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0164_canteen_siren_unite_legale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalteledeclaration",
            name="canteen_siren_unite_legale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teledeclaration",
            name="canteen_siren_unite_legale",
            field=models.TextField(blank=True, null=True),
        ),
    ]
