# Generated by Django 5.0.7 on 2025-03-28 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0167_populate_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationexpe",
            name="avg_weight_not_served_t0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Moyenne des pesées des excédents présentés aux convives et non servis ou non valorisés (g/ convive) sur 20 déjeuners successifs",
            ),
        ),
        migrations.AlterField(
            model_name="reservationexpe",
            name="avg_weight_not_served_t1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Moyenne des pesées des excédents présentés aux convives et non servis ou non valorisés (g/ convive) sur 20 déjeuners successifs",
            ),
        ),
        migrations.AlterField(
            model_name="reservationexpe",
            name="avg_weight_not_served_t2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Moyenne des pesées des excédents présentés aux convives et non servis ou non valorisés (g/ convive) sur 20 déjeuners successifs",
            ),
        ),
        migrations.AlterField(
            model_name="vegetarianexpe",
            name="waste_non_vegetarian_not_served_t0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Menus non-végétariens : Moyenne des pesées des excédents présentés aux convives et non servis ou non valorisés",
            ),
        ),
        migrations.AlterField(
            model_name="vegetarianexpe",
            name="waste_non_vegetarian_not_served_t1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Menus non-végétariens : Moyenne des pesées des excédents présentés aux convives et non servis ou non valorisés",
            ),
        ),
        migrations.AlterField(
            model_name="vegetarianexpe",
            name="waste_vegetarian_not_served_t0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Menus végétariens : Moyenne des pesées des excédents présentés aux convives et non servis ou non valorisés",
            ),
        ),
        migrations.AlterField(
            model_name="vegetarianexpe",
            name="waste_vegetarian_not_served_t1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Menus végétariens : Moyenne des pesées des excédents présentés aux convives et non servis ou non valorisés",
            ),
        ),
    ]
