# Generated by Django 5.0.7 on 2025-03-28 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0168_alter_reservationexpe_avg_weight_not_served_t0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationexpe",
            name="avg_weight_preparation_leftover_t0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Moyenne des pesées des déchets alimentaires issus de la préparation (g/convive)",
            ),
        ),
        migrations.AlterField(
            model_name="reservationexpe",
            name="avg_weight_preparation_leftover_t1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Moyenne des pesées des déchets alimentaires issus de la préparation (g/convive)",
            ),
        ),
        migrations.AlterField(
            model_name="reservationexpe",
            name="avg_weight_preparation_leftover_t2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Moyenne des pesées des déchets alimentaires issus de la préparation (g/convive)",
            ),
        ),
    ]
