# Generated by Django 5.0.7 on 2025-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0169_alter_reservationexpe_avg_weight_preparation_leftover_t0_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[("TUNNEL", "Tunnel"), ("API", "API"), ("IMPORT", "Import")],
                max_length=255,
                null=True,
                verbose_name="comment est-ce que ce diagnostic à été créé ?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[("TUNNEL", "Tunnel"), ("API", "API"), ("IMPORT", "Import")],
                max_length=255,
                null=True,
                verbose_name="comment est-ce que ce diagnostic à été créé ?",
            ),
        ),
    ]
