# Generated by Django 5.0.13 on 2025-03-26 09:16

from django.db import migrations

#########################################################
# Copying functions from data.models.Diagnostic because:
# * it can't be accessed
# * it preserves the migration from any modification
def label_sum(diagnostic, label):
    families = [
        "viandes_volailles",
        "produits_de_la_mer",
        "fruits_et_legumes",
        "charcuterie",
        "produits_laitiers",
        "boulangerie",
        "boissons",
        "autres",
    ]
    sum = 0
    for family in families:
        value = getattr(diagnostic, f"value_{family}_{label}")
        if value:
            sum = sum + value
    return sum

def populate_simplified_diagnostic_values(td, diag):
    td.value_bio_ht_agg = label_sum(diag, "bio")
    td.value_sustainable_ht_agg = label_sum(diag, "label_rouge") + label_sum(diag, "aocaop_igp_stg")
    td.value_externality_performance_ht_agg = label_sum(diag, "externalites") + label_sum(diag, "performance")
    td.value_egalim_others_ht_agg = (
        label_sum(diag, "hve")
        + label_sum(diag, "peche_durable")
        + label_sum(diag, "rup")
        + label_sum(diag, "commerce_equitable")
        + label_sum(diag, "fermier")
    )
    return td

def populate_simple_values(td, diag):
    td.value_bio_ht_agg = diag.value_bio_ht or 0
    td.value_sustainable_ht_agg = diag.value_sustainable_ht or 0
    td.value_externality_performance_ht_agg = diag.value_externality_performance_ht or 0
    td.value_egalim_others_ht_agg = diag.value_egalim_others_ht or 0
    return td
#########################################################


def populate_aggregated_food_fields(apps, schema_editor):
    Teledeclaration = apps.get_model('data', 'Teledeclaration')
    teledeclarations = Teledeclaration.objects.select_related('diagnostic').filter(diagnostic__isnull=False)
    if teledeclarations:
        for td in teledeclarations:
            diag = td.diagnostic
            td.value_total_ht = diag.value_total_ht or 0

            if diag.diagnostic_type == 'COMPLETE':
                td = populate_simplified_diagnostic_values(td, diag)
            else:
                td = populate_simple_values(td, diag)
            td.save()

def unpopulate_aggregated_fields(apps, schema_editor):
    Teledeclaration = apps.get_model('data', 'Teledeclaration')
    
    for td in Teledeclaration.objects.all():
        td.value_total_ht = None
        td.value_bio_ht_agg = None
        td.value_sustainable_ht_agg = None
        td.value_egalim_others_ht_agg = None
        td.value_externality_performance_ht_agg = None
        
        td.save()
class Migration(migrations.Migration):


    dependencies = [
        ("data", "0169_alter_reservationexpe_avg_weight_preparation_leftover_t0_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_aggregated_food_fields, unpopulate_aggregated_fields)
    ]
