# Generated by Django 5.0.13 on 2025-03-26 09:16

from django.db import migrations

def populate_aggregated_food_fields(apps, schema_editor):
    Teledeclaration = apps.get_model('data', 'Teledeclaration')
    Diagnostic = apps.get_model('data', 'Diagnostic')
    teledeclarations = Teledeclaration.objects.select_related('diagnostic').all()
    if teledeclarations:
        for td in teledeclarations:
            diag = td.diagnostic
            if diag == Diagnostic.DiagnosticType.COMPLETE:
                diag.populate_simplified_diagnostic_values()
            td.value_total_ht = diag.value_total_ht
            td.value_bio_ht_agg = diag.value_bio_ht 
            td.value_sustainable_ht_agg = diag.value_sustainable_ht 
            td.value_egalim_others_ht_agg = diag.value_egalim_others_ht 
            td.value_externality_performance_ht_agg = diag.value_externality_performance_ht 

            td.save()

def unpopulate_aggregated_fields(apps, schema_editor):
    Teledeclaration = apps.get_model('data', 'Teledeclaration')
    
    for td in Teledeclaration.objects.all():
        td.value_total_ht = None
        td.value_bio_ht_agg = None
        td.value_sustainable_ht_agg = None
        td.value_egalim_others_ht_agg = None
        td.value_externality_performance_ht_agg = None
        
        td.save()
class Migration(migrations.Migration):


    dependencies = [
        ("data", "0169_alter_reservationexpe_avg_weight_preparation_leftover_t0_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_aggregated_food_fields, unpopulate_aggregated_fields)
    ]
