# Generated by Django 5.0.13 on 2025-04-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0171_repopulate_fields_agg_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalteledeclaration",
            name="meal_price",
            field=models.FloatField(blank=True, null=True, verbose_name="Coût denrées"),
        ),
        migrations.AddField(
            model_name="historicalteledeclaration",
            name="yearly_meal_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de repas servis par an"
            ),
        ),
        migrations.AddField(
            model_name="teledeclaration",
            name="meal_price",
            field=models.FloatField(blank=True, null=True, verbose_name="Coût denrées"),
        ),
        migrations.AddField(
            model_name="teledeclaration",
            name="yearly_meal_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de repas servis par an"
            ),
        ),
    ]
