# Generated by Django 5.0.7 on 2025-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0173_repopulate_fields_agg_meal_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="diagnostic_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIMPLE", "Télédeclaration simple"),
                    ("COMPLETE", "Télédeclaration détaillée"),
                ],
                max_length=255,
                null=True,
                verbose_name="Type de diagnostic (simplifié, complet)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="diagnostic_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIMPLE", "Télédeclaration simple"),
                    ("COMPLETE", "Télédeclaration détaillée"),
                ],
                max_length=255,
                null=True,
                verbose_name="Type de diagnostic (simplifié, complet)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteledeclaration",
            name="value_bio_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ value bio (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteledeclaration",
            name="value_egalim_others_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ Autres Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteledeclaration",
            name="value_externality_performance_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ externalité/performance (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteledeclaration",
            name="value_sustainable_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ value Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteledeclaration",
            name="value_total_ht",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ value total (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="teledeclaration",
            name="value_bio_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ value bio (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="teledeclaration",
            name="value_egalim_others_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ Autres Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="teledeclaration",
            name="value_externality_performance_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ externalité/performance (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="teledeclaration",
            name="value_sustainable_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ value Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AlterField(
            model_name="teledeclaration",
            name="value_total_ht",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ value total (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
    ]
