# Generated by Django 5.0.7 on 2025-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0174_alter_diagnostic_diagnostic_type_complete_wording_detaillee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="diagnostic_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIMPLE", "Télédeclaration simple"),
                    ("COMPLETE", "Télédeclaration détaillée"),
                ],
                max_length=255,
                null=True,
                verbose_name="Type de diagnostic (simplifié, détaillé)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="diagnostic_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIMPLE", "Télédeclaration simple"),
                    ("COMPLETE", "Télédeclaration détaillée"),
                ],
                max_length=255,
                null=True,
                verbose_name="Type de diagnostic (simplifié, détaillé)",
            ),
        ),
    ]
