# Generated by Django 5.0.7 on 2025-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0176_alter_diagnostic_creation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TUNNEL", "Tunnel"),
                    ("API", "API"),
                    ("IMPORT", "Import"),
                    ("ADMIN", "Admin"),
                ],
                max_length=255,
                null=True,
                verbose_name="comment est-ce que cette cantine à été créée ?",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TUNNEL", "Tunnel"),
                    ("API", "API"),
                    ("IMPORT", "Import"),
                    ("ADMIN", "Admin"),
                ],
                max_length=255,
                null=True,
                verbose_name="comment est-ce que cette cantine à été créée ?",
            ),
        ),
    ]
