# Generated by Django 5.0.7 on 2025-04-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0176_alter_canteen_line_ministry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TUNNEL", "Tunnel"),
                    ("API", "API"),
                    ("IMPORT", "Import"),
                    ("ADMIN", "Admin"),
                ],
                max_length=255,
                null=True,
                verbose_name="Source de création du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TUNNEL", "Tunnel"),
                    ("API", "API"),
                    ("IMPORT", "Import"),
                    ("ADMIN", "Admin"),
                ],
                max_length=255,
                null=True,
                verbose_name="Source de création du diagnostic",
            ),
        ),
    ]
