# Generated by Django 5.0.7 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0177_canteen_creation_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TUNNEL", "Tunnel"),
                    ("API", "API"),
                    ("IMPORT", "Import"),
                    ("ADMIN", "Admin"),
                ],
                max_length=255,
                null=True,
                verbose_name="comment est-ce que cette achat à été créé ?",
            ),
        ),
    ]
