# Generated by Django 5.0.7 on 2025-04-28 12:54

from django.db import migrations, models


def migrate_creation_source_tunnel_to_app(apps, schema_editor):
    """
    Migrate the creation_source field from 'TUNNEL' to 'APP' for all records
    in the Purchase model.
    """
    Purchase = apps.get_model("data", "Purchase")
    Canteen = apps.get_model("data", "Canteen")
    Diagnostic = apps.get_model("data", "Diagnostic")

    Purchase.objects.filter(creation_source="TUNNEL").update(creation_source="APP")
    Canteen.objects.filter(creation_source="TUNNEL").update(creation_source="APP")
    Diagnostic.objects.filter(creation_source="TUNNEL").update(creation_source="APP")


def undo_migrate_creation_source_tunnel_to_app(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0181_alter_diagnostic_value_boulangerie_aocaop_igp_stg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APP", "APP"),
                    ("API", "API"),
                    ("IMPORT", "IMPORT"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=255,
                null=True,
                verbose_name="Source de création de la cantine",
            ),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APP", "APP"),
                    ("API", "API"),
                    ("IMPORT", "IMPORT"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=255,
                null=True,
                verbose_name="Source de création du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APP", "APP"),
                    ("API", "API"),
                    ("IMPORT", "IMPORT"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=255,
                null=True,
                verbose_name="Source de création de la cantine",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APP", "APP"),
                    ("API", "API"),
                    ("IMPORT", "IMPORT"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=255,
                null=True,
                verbose_name="Source de création du diagnostic",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APP", "APP"),
                    ("API", "API"),
                    ("IMPORT", "IMPORT"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=255,
                null=True,
                verbose_name="Source de création de l'achat",
            ),
        ),
        migrations.RunPython(migrate_creation_source_tunnel_to_app, undo_migrate_creation_source_tunnel_to_app)
    ]
