# Generated by Django 5.0.7 on 2025-05-06 10:10

from django.db import migrations
from django.db.models import Q, Case, When, F, Value
from django.db.models.functions import Length

def populate_canteen_creation_source(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")
    HistoricalCanteen = apps.get_model("data", "HistoricalCanteen")
    # first set of rules
    canteen_qs = Canteen.objects.filter(Q(creation_source="") | Q(creation_source__isnull=True))
    canteen_qs.annotate(import_source_length=Length("import_source")).annotate(creation_source_annotated=Case(
        When(Q(import_source__startswith="Cuisine centrale : "), then=Value("APP")),
        When(Q(import_source_length__gt=0), then=Value("IMPORT")),
        default=Value(None),
    )).update(
        creation_source=F("creation_source_annotated")
    )
    # second set of rules: HistoricalCanteen
    for canteen in canteen_qs.all():
        canteen_first_version = HistoricalCanteen.objects.filter(id=canteen.id).last()
        if not canteen.creation_source and canteen_first_version and canteen_first_version.history_type == "+":
            if canteen_first_version.history_change_reason is None:
                if canteen_first_version.history_user_id and canteen_first_version.history_user.is_staff:
                    canteen.creation_source = "ADMIN"
                    canteen.save(update_fields=["creation_source"])
            elif canteen_first_version.history_change_reason.startswith("Mass CSV import"):
                canteen.creation_source = "IMPORT"
                canteen.save(update_fields=["creation_source"])
            elif canteen_first_version.history_change_reason == "SessionAuthentication":
                canteen.creation_source = "APP"
                canteen.save(update_fields=["creation_source"])
            elif canteen_first_version.history_change_reason == "OAuth2Authentication":
                canteen.creation_source = "API"
                canteen.save(update_fields=["creation_source"])

def undo_populate_canteen_creation_source(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("data", "0182_alter_canteen_creation_source_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_canteen_creation_source, undo_populate_canteen_creation_source)
    ]
