# Generated by Django 5.0.7 on 2025-05-06 08:09

from django.db import migrations
from django.db.models import Q, F, Case, When, Value
from django.db.models.functions import Length


def populate_purchase_creation_source(apps, schema_editor):
    """
    Update only the Purchases with an empty creation_source
    """
    Purchase = apps.get_model("data", "Purchase")
    purchase_qs = Purchase.objects.filter(Q(creation_source="") | Q(creation_source__isnull=True))
    purchase_qs.annotate(import_source_length=Length("import_source")).annotate(
        creation_source_annotated=Case(
            When(Q(import_source="Duplication"), then=Value("APP")),
            When(Q(import_source="Import du fichier CSV"), then=Value("IMPORT")),
            When(Q(import_source_length=32), then=Value("IMPORT")),  # file uuid4
            default=Value(None),
        )
    ).update(
        creation_source=F("creation_source_annotated")
    )

def undo_populate_purchase_creation_source(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0184_diagnostic_creation_source_populate"),
    ]

    operations = [
        migrations.RunPython(populate_purchase_creation_source, undo_populate_purchase_creation_source)
    ]
