# Generated by Django 5.0.7 on 2025-05-07 16:28

import common.utils.siret
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0185_purchase_creation_source_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="epci",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[common.utils.siret.validate_siren],
                verbose_name="Code EPCI",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="epci",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[common.utils.siret.validate_siren],
                verbose_name="Code EPCI",
            ),
        ),
    ]
