# Generated by Django 5.0.7 on 2025-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0186_canteen_epci_historicalcanteen_epci"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="epci_lib",
            field=models.TextField(blank=True, null=True, verbose_name="nom EPCI"),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="epci_lib",
            field=models.TextField(blank=True, null=True, verbose_name="nom EPCI"),
        ),
    ]
