# Generated by Django 5.0.7 on 2025-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0187_canteen_epci_lib_historicalcanteen_epci_lib"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="department_lib",
            field=models.TextField(
                blank=True, null=True, verbose_name="nom du département"
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="region_lib",
            field=models.TextField(
                blank=True, null=True, verbose_name="nom de la région"
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="department_lib",
            field=models.TextField(
                blank=True, null=True, verbose_name="nom du département"
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="region_lib",
            field=models.TextField(
                blank=True, null=True, verbose_name="nom de la région"
            ),
        ),
    ]
