# Generated by Django 5.0.7 on 2025-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0188_canteen_department_lib_canteen_region_lib_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="pat",
            field=models.CharField(blank=True, null=True, verbose_name="Code PAT"),
        ),
        migrations.AddField(
            model_name="canteen",
            name="pat_lib",
            field=models.TextField(blank=True, null=True, verbose_name="nom PAT"),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="pat",
            field=models.CharField(blank=True, null=True, verbose_name="Code PAT"),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="pat_lib",
            field=models.TextField(blank=True, null=True, verbose_name="nom PAT"),
        ),
    ]
