# Generated by Django 5.0.7 on 2025-05-28 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0189_alter_canteen_department_alter_canteen_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="pat_lib_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="noms PAT",
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="pat_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="codes PAT",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="pat_lib_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="noms PAT",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="pat_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="codes PAT",
            ),
        ),
    ]
