# Generated by Django 5.0.7 on 2025-06-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0190_canteen_pat_lib_list_canteen_pat_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="teledeclared_2021",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2021"
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="teledeclared_2022",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2022"
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="teledeclared_2023",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2023"
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="teledeclared_2024",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2024"
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="teledeclared_2021",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2021"
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="teledeclared_2022",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2022"
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="teledeclared_2023",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2023"
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="teledeclared_2024",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="a télédéclarée ses données de 2024"
            ),
        ),
    ]
