# Generated by Django 5.0.7 on 2025-07-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0191_canteen_declaration_donnees_YEAR"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canteen",
            name="publication_status",
        ),
        migrations.RemoveField(
            model_name="historicalcanteen",
            name="publication_status",
        ),
    ]
