# Generated by Django 5.0.7 on 2025-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0193_alter_canteen_declaration_donnees_2021_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("SUBMITTED", "Télédéclaré")],
                default="DRAFT",
                max_length=255,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("SUBMITTED", "Télédéclaré")],
                default="DRAFT",
                max_length=255,
                verbose_name="status",
            ),
        ),
    ]
