# Generated by Django 5.0.7 on 2025-08-04 14:25

from django.db import migrations


def populate_diagnostic_source(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    diagnostic_submitted_id_list = Teledeclaration.objects.filter(status="SUBMITTED").values_list("diagnostic_id", flat=True)
    Diagnostic.objects.filter(id__in=diagnostic_submitted_id_list).update(status="SUBMITTED")


def undo_populate_diagnostic_source(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0194_diagnostic_status_historicaldiagnostic_status"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_source, undo_populate_diagnostic_source)
    ]
