# Generated by Django 5.0.7 on 2025-08-11 15:07

import data.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0195_diagnostic_status_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="canteen_snapshot",
            field=models.JSONField(
                blank=True,
                encoder=data.utils.CustomJSONEncoder,
                null=True,
                verbose_name="cantine (copie au moment de la télédéclaration)",
            ),
        ),
    ]
