# Generated by Django 5.0.7 on 2025-08-11 15:13

from django.db import migrations


def populate_diagnostic_canteen_snapshot(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    for teledeclaration in Teledeclaration.objects.filter(status="SUBMITTED"):
        try:
            diagnostic = Diagnostic.objects.get(id=teledeclaration.diagnostic_id)
            canteen_snapshot = teledeclaration.declared_data.get("canteen")
            if canteen_snapshot:
                diagnostic.canteen_snapshot = canteen_snapshot
                diagnostic.save(update_fields=["canteen_snapshot"])
        except Diagnostic.DoesNotExist:
            continue


def undo_populate_diagnostic_canteen_snapshot(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Diagnostic.objects.all().update(canteen_snapshot=dict())


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0196_diagnostic_canteen_snapshot_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_canteen_snapshot, undo_populate_diagnostic_canteen_snapshot)
    ]
