# Generated by Django 5.0.7 on 2025-08-12 06:06

import data.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0197_diagnostic_canteen_snapshort_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="applicant_snapshot",
            field=models.JSONField(
                blank=True,
                encoder=data.utils.CustomJSONEncoder,
                null=True,
                verbose_name="déclarant (copie au moment de la télédéclaration)",
            ),
        ),
    ]
