# Generated by Django 5.0.7 on 2025-08-12 06:08

from django.db import migrations


def populate_diagnostic_applicant_snapshot(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    for teledeclaration in Teledeclaration.objects.filter(status="SUBMITTED"):
        try:
            diagnostic = Diagnostic.objects.get(id=teledeclaration.diagnostic_id)
            applicant_snapshot = teledeclaration.declared_data.get("applicant")
            if applicant_snapshot:
                diagnostic.applicant_snapshot = applicant_snapshot
                diagnostic.save(update_fields=["applicant_snapshot"])
        except Diagnostic.DoesNotExist:
            continue


def undo_populate_diagnostic_applicant_snapshot(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Diagnostic.objects.all().update(applicant_snapshot=None)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0198_diagnostic_applicant_snapshot"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_applicant_snapshot, undo_populate_diagnostic_applicant_snapshot)
    ]
