# Generated by Django 5.0.7 on 2025-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0199_diagnostic_applicant_snapshot_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="teledeclaration_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date de télédéclaration",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="teledeclaration_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date de télédéclaration",
            ),
        ),
    ]
