# Generated by Django 5.0.7 on 2025-08-12 06:40

from django.db import migrations


def populate_diagnostic_teledeclaration_submitted_date(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    for teledeclaration in Teledeclaration.objects.filter(status="SUBMITTED"):
        try:
            diagnostic = Diagnostic.objects.get(id=teledeclaration.diagnostic_id)
            teledeclaration_submitted_date = teledeclaration.creation_date
            if teledeclaration_submitted_date:
                diagnostic.teledeclaration_submitted_date = teledeclaration_submitted_date
                diagnostic.save(update_fields=["teledeclaration_submitted_date"])
        except Diagnostic.DoesNotExist:
            continue


def undo_populate_diagnostic_teledeclaration_submitted_date(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Diagnostic.objects.all().update(teledeclaration_submitted_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0200_diagnostic_teledeclaration_submitted_date_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_teledeclaration_submitted_date, undo_populate_diagnostic_teledeclaration_submitted_date)
    ]
