# Generated by Django 5.0.7 on 2025-08-15 12:32

import data.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0201_diagnostic_teledeclaration_date_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="satellites_snapshot",
            field=models.JSONField(
                blank=True,
                encoder=data.utils.CustomJSONEncoder,
                null=True,
                verbose_name="satellites (copie au moment de la télédéclaration)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="satellites_snapshot",
            field=models.JSONField(
                blank=True,
                encoder=data.utils.CustomJSONEncoder,
                null=True,
                verbose_name="satellites (copie au moment de la télédéclaration)",
            ),
        ),
    ]
