# Generated by Django 5.0.7 on 2025-08-18 09:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0201_diagnostic_teledeclaration_date_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="value_bio_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Bio - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_sustainable_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Produits SIQO (hors bio) - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_externality_performance_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Externalité/performance - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_egalim_others_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Autres achats EGalim - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_bio_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Bio - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_sustainable_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Produits SIQO (hors bio) - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_externality_performance_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Externalité/performance - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_egalim_others_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Autres achats EGalim - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
    ]
