# Generated by Django 5.0.7 on 2025-08-15 12:49

from django.db import migrations


def populate_diagnostic_satellites_snapshot(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    for teledeclaration in Teledeclaration.objects.filter(status="SUBMITTED"):
        try:
            diagnostic = Diagnostic.objects.get(id=teledeclaration.diagnostic_id)
            satellites_snapshot = teledeclaration.declared_data.get("satellites")
            if satellites_snapshot:
                diagnostic.satellites_snapshot = satellites_snapshot
                diagnostic.save(update_fields=["satellites_snapshot"])
        except Diagnostic.DoesNotExist:
            continue


def undo_populate_diagnostic_satellites_snapshot(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Diagnostic.objects.all().update(satellites_snapshot=None)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0202_diagnostic_satellites_snapshot_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_satellites_snapshot, undo_populate_diagnostic_satellites_snapshot)
    ]
