# Generated by Django 5.0.7 on 2025-08-18 09:37

from django.db import migrations


def populate_diagnostic_value_bio_ht_agg(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    for teledeclaration in Teledeclaration.objects.filter(status="SUBMITTED"):
        try:
            diagnostic = Diagnostic.objects.get(id=teledeclaration.diagnostic_id)
            value_bio_ht_agg = teledeclaration.value_bio_ht_agg
            if value_bio_ht_agg:
                diagnostic.value_bio_ht_agg = value_bio_ht_agg
                diagnostic.save(update_fields=["value_bio_ht_agg"])
        except Diagnostic.DoesNotExist:
            continue


def undo_populate_diagnostic_value_bio_ht_agg(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Diagnostic.objects.all().update(value_bio_ht_agg=None)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0202_diagnostic_value_bio_ht_agg_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_value_bio_ht_agg, undo_populate_diagnostic_value_bio_ht_agg)
    ]
