# Generated by Django 5.0.7 on 2025-08-18 09:37

from django.db import migrations


VALUE_HT_AGG_FIELDS = [
    "value_bio_ht_agg",
    "value_sustainable_ht_agg",
    "value_externality_performance_ht_agg",
    "value_egalim_others_ht_agg",
]


def populate_diagnostic_value_ht_agg_fields(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    for teledeclaration in Teledeclaration.objects.filter(status="SUBMITTED"):
        try:
            diagnostic = Diagnostic.objects.get(id=teledeclaration.diagnostic_id)
            for field in VALUE_HT_AGG_FIELDS:
                value = getattr(teledeclaration, field)
                if value:
                    setattr(diagnostic, field, value)
            diagnostic.save(update_fields=VALUE_HT_AGG_FIELDS)
        except Diagnostic.DoesNotExist:
            continue


def undo_populate_diagnostic_value_ht_agg_fields(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    for field in VALUE_HT_AGG_FIELDS:
        Diagnostic.objects.all().update(**{field: None})


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0204_diagnostic_value_ht_agg_fields"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_value_ht_agg_fields, undo_populate_diagnostic_value_ht_agg_fields)
    ]
