# Generated by Django 5.1 on 2025-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0205_diagnostic_value_ht_agg_fields_populate"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="diagnostic",
            name="annual_diagnostic",
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="generated_from_central_kitchen_diagnostic",
            field=models.BooleanField(
                default=False,
                verbose_name="seulement pertinent pour les satellites : A été automatiquement généré depuis le bilan de la cuisine centrale",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="generated_from_central_kitchen_diagnostic",
            field=models.BooleanField(
                default=False,
                verbose_name="seulement pertinent pour les satellites : A été automatiquement généré depuis le bilan de la cuisine centrale",
            ),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("SUBMITTED", "Télédéclaré"),
                    ("OVERRIDEN_BY_CC", "Ecrasé par la cuisine centrale"),
                ],
                default="DRAFT",
                max_length=255,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("SUBMITTED", "Télédéclaré"),
                    ("OVERRIDEN_BY_CC", "Ecrasé par la cuisine centrale"),
                ],
                default="DRAFT",
                max_length=255,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnostic",
            constraint=models.UniqueConstraint(
                fields=("canteen", "year", "generated_from_central_kitchen_diagnostic"),
                name="annual_diagnostic",
            ),
        ),
    ]
