# Generated by Django 5.0.7 on 2025-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0206_diagnostic_value_ht_agg_fields_populate_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="teledeclaration_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "SATELLITE_WITHOUT_APPRO",
                        "Cantine satellite dont les données d'appro sont déclarées par la cuisine centrale",
                    ),
                    (
                        "CENTRAL_APPRO",
                        "Cuisine centrale déclarant les données d'appro pour ses cuisines satellites",
                    ),
                    (
                        "CENTRAL_ALL",
                        "Cuisine centrale déclarant toutes les données EGalim pour ses cuisines satellites",
                    ),
                    ("SITE", "Cantine déclarant ses propres données"),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de télédéclaration",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="teledeclaration_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "SATELLITE_WITHOUT_APPRO",
                        "Cantine satellite dont les données d'appro sont déclarées par la cuisine centrale",
                    ),
                    (
                        "CENTRAL_APPRO",
                        "Cuisine centrale déclarant les données d'appro pour ses cuisines satellites",
                    ),
                    (
                        "CENTRAL_ALL",
                        "Cuisine centrale déclarant toutes les données EGalim pour ses cuisines satellites",
                    ),
                    ("SITE", "Cantine déclarant ses propres données"),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de télédéclaration",
            ),
        ),
    ]
