# Generated by Django 5.0.7 on 2025-08-25 09:08

from django.db import migrations


def populate_diagnostic_teledeclaration_mode(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Teledeclaration = apps.get_model("data", "Teledeclaration")
    for teledeclaration in Teledeclaration.objects.filter(status="SUBMITTED"):
        try:
            diagnostic = Diagnostic.objects.get(id=teledeclaration.diagnostic_id)
            teledeclaration_mode = teledeclaration.teledeclaration_mode
            if teledeclaration_mode:
                diagnostic.teledeclaration_mode = teledeclaration_mode
                diagnostic.save(update_fields=["teledeclaration_mode"])
        except Diagnostic.DoesNotExist:
            continue


def undo_populate_diagnostic_teledeclaration_mode(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Diagnostic.objects.all().update(teledeclaration_mode=None)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0207_diagnostic_teledeclaration_mode_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_diagnostic_teledeclaration_mode, undo_populate_diagnostic_teledeclaration_mode)
    ]
