# Generated by Django 5.0.7 on 2025-08-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0208_diagnostic_teledeclaration_mode_populate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaldiagnostic",
            name="satellites_snapshot",
        ),
    ]
