# Generated by Django 5.1.10 on 2025-09-06 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0209_remove_historicaldiagnostic_satellites_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="déclarant",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="déclarant",
            ),
        ),
    ]
