# Generated by Django 5.1 on 2025-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0209_remove_historicaldiagnostic_satellites_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalteledeclaration",
            name="value_fish_egalim_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ poissons et produits aquatiques Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicalteledeclaration",
            name="value_meat_poultry_egalim_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ viandes et volailles fraiches ou surgelées Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicalteledeclaration",
            name="value_meat_poultry_france_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ viandes et volailles fraiches ou surgelées France (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="teledeclaration",
            name="value_fish_egalim_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ poissons et produits aquatiques Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="teledeclaration",
            name="value_meat_poultry_egalim_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ viandes et volailles fraiches ou surgelées Egalim (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="teledeclaration",
            name="value_meat_poultry_france_ht_agg",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Champ viandes et volailles fraiches ou surgelées France (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
    ]
