# Generated by Django 5.1 on 2025-08-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0209_remove_historicaldiagnostic_satellites_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="central_canteen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.canteen",
                verbose_name="Cantine centrale",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="central_canteen",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.canteen",
                verbose_name="Cantine centrale",
            ),
        ),
    ]
