# Generated by Django 5.1 on 2025-08-29 19:47
from django.db import migrations


def populate_central_canteen(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")
    for canteen in Canteen.objects.filter(production_type="site_cooked_elsewhere"):
        try:
            if (canteen.central_producer_siret):
                related_central_canteen = None
                central_canteen_found = Canteen.objects.filter(production_type__in=["central", "central_serving"], siret=canteen.central_producer_siret)
                print("1", central_canteen_found)
                if (central_canteen_found.count() > 0):
                    if (central_canteen_found.count() == 1):
                        print("2", central_canteen_found)
                        related_central_canteen = central_canteen_found[0]
                    elif (central_canteen_found.count() > 1):
                        central_canteen_found = Canteen.objects.filter(production_type__in=["central", "central_serving"], siret=canteen.central_producer_siret).exclude(deletion_date__isnull=False)
                        print("3", central_canteen_found)
                        if (central_canteen_found.count() == 1):
                            print("4", central_canteen_found)
                            related_central_canteen = central_canteen_found[0]
                        # if still have more than one result after that no automatic update :
                        # user will we ask to choose his central canteen before teledeclare
                print('AVANT UPDATE', related_central_canteen)
                canteen.central_canteen = related_central_canteen
                canteen.save(update_fields=["central_canteen"])
        except Canteen.DoesNotExist:
            continue


def undo_populate_central_canteen(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")
    Canteen.objects.all().update(central_canteen=None)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0210_canteen_central_relation"),
    ]

    operations = [
        migrations.RunPython(populate_central_canteen, undo_populate_central_canteen)
    ]
