# Generated by Django 5.1.10 on 2025-09-09 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0211_diagnostic_teledeclaration_version_historicaldiagnostic_teledeclaration_version_and_populate",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="value_egalim_hors_bio_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="EGalim (Produits SIQO (hors bio) + Externalité/performance + Autres achats EGalim) - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_egalim_hors_bio_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="EGalim (Produits SIQO (hors bio) + Externalité/performance + Autres achats EGalim) - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
    ]
