# Generated by Django 5.1.10 on 2025-09-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0211_diagnostic_teledeclaration_version_historicaldiagnostic_teledeclaration_version_and_populate",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="canteen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.canteen",
                verbose_name="cantine",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="canteen",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.canteen",
                verbose_name="cantine",
            ),
        ),
    ]
