# Generated by Django 5.1.10 on 2025-09-09 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def populate_diagnostic_value_egalim_hors_bio_ht_agg(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    for diagnostic in Diagnostic.objects.all():
        if diagnostic.value_bio_ht_agg is not None or diagnostic.value_egalim_ht_agg is not None:
            value_egalim_ht_agg = (diagnostic.value_egalim_ht_agg or 0) + (diagnostic.value_bio_ht_agg or 0)
            diagnostic.value_egalim_hors_bio_ht_agg = value_egalim_ht_agg
            diagnostic.save(update_fields=["value_egalim_hors_bio_ht_agg"])



def undo_populate_diagnostic_value_egalim_hors_bio_ht_agg(apps, schema_editor):
    Diagnostic = apps.get_model("data", "Diagnostic")
    Diagnostic.objects.all().update(value_egalim_hors_bio_ht_agg=None)



class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0213_diagnostic_teledeclaration_id_historical_diagnostic_teledeclaration_id_and_populate",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="value_egalim_hors_bio_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="EGalim (Produits SIQO (hors bio) + Externalité/performance + Autres achats EGalim) - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_egalim_hors_bio_ht_agg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="EGalim (Produits SIQO (hors bio) + Externalité/performance + Autres achats EGalim) - Valeur annuelle HT (en cas de TD détaillée, ce champ est aggrégé)",
            ),
        ),
        migrations.RunPython(populate_diagnostic_value_egalim_hors_bio_ht_agg, undo_populate_diagnostic_value_egalim_hors_bio_ht_agg),
    ]
