# Generated by Django 5.1.10 on 2025-10-08 17:07

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0214_diagnostic_value_egalim_hors_bio_ht_agg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="tags",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("VALUE_TOTAL_HT_VIDE", "value_total_ht vide"),
                        ("VALUE_BIO_HT_VIDE", "value_bio_ht vide"),
                        (
                            "CANTINE_SUPPRIMEE_PENDANT_CAMPAGNE",
                            "Cantine supprimée pendant la campagne",
                        ),
                        ("CANTINE_SANS_SIRET_OU_SIREN", "Cantine sans siret ou siren"),
                        ("VALEURS_ABERRANTES", "Valeurs aberrantes"),
                        ("DOUBLON_SATELLITE_CENTRALE", "Doublon satellite / centrale"),
                        ("VALEURS_INCOHERENTES", "Valeurs incohérentes"),
                        ("RAPPORT", "Présent dans le rapport"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="tags de qualité des données",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="tags",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("VALUE_TOTAL_HT_VIDE", "value_total_ht vide"),
                        ("VALUE_BIO_HT_VIDE", "value_bio_ht vide"),
                        (
                            "CANTINE_SUPPRIMEE_PENDANT_CAMPAGNE",
                            "Cantine supprimée pendant la campagne",
                        ),
                        ("CANTINE_SANS_SIRET_OU_SIREN", "Cantine sans siret ou siren"),
                        ("VALEURS_ABERRANTES", "Valeurs aberrantes"),
                        ("DOUBLON_SATELLITE_CENTRALE", "Doublon satellite / centrale"),
                        ("VALEURS_INCOHERENTES", "Valeurs incohérentes"),
                        ("RAPPORT", "Présent dans le rapport"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="tags de qualité des données",
            ),
        ),
    ]
