# Generated by Django 5.1.10 on 2025-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0215_alter_canteen_production_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Cuisine centrale sans lieu de consommation"),
                    (
                        "central_serving",
                        "Cuisine centrale qui accueille aussi des convives sur place",
                    ),
                    ("site", "Cantine qui produit les repas sur place"),
                    (
                        "site_cooked_elsewhere",
                        "Etablissement desservi par une cuisine centrale",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Cuisine centrale sans lieu de consommation"),
                    (
                        "central_serving",
                        "Cuisine centrale qui accueille aussi des convives sur place",
                    ),
                    ("site", "Cantine qui produit les repas sur place"),
                    (
                        "site_cooked_elsewhere",
                        "Etablissement desservi par une cuisine centrale",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
        migrations.AlterField(
            model_name="importfailure",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("CANTEEN_ONLY", "Cantines seules"),
                    (
                        "CANTEEN_ONLY_OR_DIAGNOSTIC_SIMPLE",
                        "Cantines seules ou avec un diagnostic simple",
                    ),
                    ("DIAGNOSTIC_SIMPLE", "Diagnostic simple"),
                    ("DIAGNOSTIC_COMPLETE", "Cantines avec diagnostic complet"),
                    (
                        "CC_SIMPLE",
                        "Cuisines centrales avec un diagnostic simple et leurs cuisines satellites",
                    ),
                    (
                        "CC_COMPLETE",
                        "Cuisines centrales avec un diagnostic complet et leurs cuisines satellites",
                    ),
                    ("PURCHASE", "Achats"),
                ],
                null=True,
                verbose_name="type d'import",
            ),
        ),
    ]
