# Generated by Django 5.1.10 on 2025-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0216_alter_canteen_production_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "central",
                        "Livre des repas mais n'a pas de lieu de service en propre",
                    ),
                    (
                        "central_serving",
                        "Livre des repas et accueille aussi des convives sur place",
                    ),
                    ("site", "Produit sur place les repas qu'il sert aux convives"),
                    (
                        "site_cooked_elsewhere",
                        "Sert des repas préparés par une cuisine centrale (une petite partie peut être réalisée sur place entrée / dessert)",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "central",
                        "Livre des repas mais n'a pas de lieu de service en propre",
                    ),
                    (
                        "central_serving",
                        "Livre des repas et accueille aussi des convives sur place",
                    ),
                    ("site", "Produit sur place les repas qu'il sert aux convives"),
                    (
                        "site_cooked_elsewhere",
                        "Sert des repas préparés par une cuisine centrale (une petite partie peut être réalisée sur place entrée / dessert)",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
    ]
