# Generated by Django 5.1.10 on 2025-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0217_alter_canteen_production_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="economic_model",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("private", "Privé")],
                max_length=50,
                null=True,
                verbose_name="Modèle économique",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="economic_model",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("private", "Privé")],
                max_length=50,
                null=True,
                verbose_name="Modèle économique",
            ),
        ),
    ]
