# Generated by Django 5.1.13 on 2025-11-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0218_alter_canteen_economic_model_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sector",
            new_name="SectorM2M",
        ),
        migrations.RenameField(
            model_name="canteen",
            old_name="sectors",
            new_name="sectors_m2m",
        ),
        migrations.RenameField(
            model_name="partner",
            old_name="sectors",
            new_name="sectors_m2m",
        ),
    ]
