# Generated by Django 5.1.13 on 2025-11-24 13:52

from django.db import migrations, models

import data.fields


def populate_sector_list_from_sectors_m2m(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")

    for canteen in Canteen.objects.prefetch_related("sectors_m2m").all():
        sectors_m2m_name_list = list(canteen.sectors_m2m.values_list("name", flat=True))
        canteen.sector_list = [sector.replace("’", "'") for sector in sectors_m2m_name_list]
        canteen.save()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0219_rename_sector_sectorm2m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="sector_list",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("administration_prison", "Restaurants des prisons"),
                        (
                            "administration_administratif",
                            "Restaurants administratifs d'Etat (RA)",
                        ),
                        (
                            "administration_armee",
                            "Restaurants des armées / police / gendarmerie",
                        ),
                        (
                            "administration_etablissement_public",
                            "Etablissements publics d'Etat (EPA ou EPIC)",
                        ),
                        (
                            "administration_inter_administratif",
                            "Restaurants inter-administratifs d'État (RIA)",
                        ),
                        (
                            "administration_administratif_des_collectivites",
                            "Restaurants administratifs des collectivités territoriales",
                        ),
                        ("entreprise_entreprise", "Restaurants d'entreprises"),
                        (
                            "entreprise_inter_entreprise",
                            "Restaurants inter-entreprises",
                        ),
                        (
                            "education_primaire",
                            "Ecole primaire (maternelle et élémentaire)",
                        ),
                        ("education_secondaire_college", "Secondaire collège"),
                        (
                            "education_secondaire_lycee",
                            "Secondaire lycée (hors agricole)",
                        ),
                        (
                            "education_enseignement_agricole",
                            "Etablissements d'enseignement agricole",
                        ),
                        (
                            "education_superieur_universitaire",
                            "Supérieur et Universitaire",
                        ),
                        ("education_autre", "Autres structures d'enseignement"),
                        ("sante_hopital", "Hôpitaux"),
                        ("sante_clinique", "Cliniques"),
                        ("sante_autre", "Autres établissements de soins"),
                        ("social_creche", "Crèche"),
                        ("social_ime", "IME / ITEP"),
                        ("social_esat", "ESAT / Etablissements spécialisés"),
                        (
                            "social_ehpad",
                            "EHPAD / maisons de retraite / foyers de personnes âgées",
                        ),
                        ("social_pjj", "Etablissements de la PJJ"),
                        (
                            "social_autre",
                            "Autres établissements sociaux et médico-sociaux",
                        ),
                        ("loisir_centre_vacances", "Centre de vacances / sportif"),
                        ("loisir_autre", "Autres établissements de loisirs"),
                        ("autres_autre", "Autres établissements non listés"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="secteurs d'activité",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="sector_list",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("administration_prison", "Restaurants des prisons"),
                        (
                            "administration_administratif",
                            "Restaurants administratifs d'Etat (RA)",
                        ),
                        (
                            "administration_armee",
                            "Restaurants des armées / police / gendarmerie",
                        ),
                        (
                            "administration_etablissement_public",
                            "Etablissements publics d'Etat (EPA ou EPIC)",
                        ),
                        (
                            "administration_inter_administratif",
                            "Restaurants inter-administratifs d'État (RIA)",
                        ),
                        (
                            "administration_administratif_des_collectivites",
                            "Restaurants administratifs des collectivités territoriales",
                        ),
                        ("entreprise_entreprise", "Restaurants d'entreprises"),
                        (
                            "entreprise_inter_entreprise",
                            "Restaurants inter-entreprises",
                        ),
                        (
                            "education_primaire",
                            "Ecole primaire (maternelle et élémentaire)",
                        ),
                        ("education_secondaire_college", "Secondaire collège"),
                        (
                            "education_secondaire_lycee",
                            "Secondaire lycée (hors agricole)",
                        ),
                        (
                            "education_enseignement_agricole",
                            "Etablissements d'enseignement agricole",
                        ),
                        (
                            "education_superieur_universitaire",
                            "Supérieur et Universitaire",
                        ),
                        ("education_autre", "Autres structures d'enseignement"),
                        ("sante_hopital", "Hôpitaux"),
                        ("sante_clinique", "Cliniques"),
                        ("sante_autre", "Autres établissements de soins"),
                        ("social_creche", "Crèche"),
                        ("social_ime", "IME / ITEP"),
                        ("social_esat", "ESAT / Etablissements spécialisés"),
                        (
                            "social_ehpad",
                            "EHPAD / maisons de retraite / foyers de personnes âgées",
                        ),
                        ("social_pjj", "Etablissements de la PJJ"),
                        (
                            "social_autre",
                            "Autres établissements sociaux et médico-sociaux",
                        ),
                        ("loisir_centre_vacances", "Centre de vacances / sportif"),
                        ("loisir_autre", "Autres établissements de loisirs"),
                        ("autres_autre", "Autres établissements non listés"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="secteurs d'activité",
            ),
        ),
        migrations.RunPython(populate_sector_list_from_sectors_m2m, reverse_code=migrations.RunPython.noop),
    ]
