# Generated by Django 5.1.13 on 2025-11-27 16:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0219_rename_sector_sectorm2m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='value_meat_poultry_france_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) viandes et volailles fraiches ou surgelées origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_aocaop_igp_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, AOC / AOP / IGP / STG"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Bio"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Commerce équitable"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_externalites',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Fermier"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Provenance France"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_hve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Haute valeur environnementale"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_label_rouge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Label rouge"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Produit local"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, non-EGalim."),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Pêche durable"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Produits acquis sur la base de leurs performances en matière environnementale"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_rup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Région ultrapériphérique"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='value_produits_de_la_mer_short_distribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Circuit-court"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_meat_poultry_france_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) viandes et volailles fraiches ou surgelées origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_aocaop_igp_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, AOC / AOP / IGP / STG"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Bio"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Commerce équitable"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_externalites',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Fermier"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Provenance France"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_hve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Haute valeur environnementale"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_label_rouge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Label rouge"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Produit local"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, non-EGalim."),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Pêche durable"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Produits acquis sur la base de leurs performances en matière environnementale"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_rup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Région ultrapériphérique"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='value_produits_de_la_mer_short_distribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Circuit-court"),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='family',
            field=models.CharField(blank=True, choices=[('VIANDES_VOLAILLES', 'Viandes et volailles fraîches et surgelées'), ('CHARCUTERIE', 'Charcuterie'), ('PRODUITS_DE_LA_MER', "Poissons, produits de la mer et de l'aquaculture"), ('FRUITS_ET_LEGUMES', 'Fruits et légumes frais et surgelés'), ('PRODUITS_LAITIERS', 'BOF (Produits laitiers, beurre et œufs)'), ('BOULANGERIE', 'Boulangerie/Pâtisserie fraîches et surgelées'), ('BOISSONS', 'Boissons'), ('AUTRES', 'Autres produits frais, surgelés et d’épicerie')], max_length=255, null=True, verbose_name='famille de produits'),
        ),
    ]
