# Generated by Django 5.1.13 on 2025-11-14 17:44

import data.fields
from django.db import migrations, models


def populate_sectors_from_sectors_m2m(apps, schema_editor):
    Canteen = apps.get_model("data", "Canteen")

    for canteen in Canteen.objects.prefetch_related("sectors_m2m").all():
        sector_values = list(canteen.sectors_m2m.values_list("name", flat=True))
        canteen.sectors = sector_values
        canteen.save()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0219_rename_sector_sectorm2m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="sectors",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Restaurants des prisons", "Restaurants des prisons"),
                        (
                            "Restaurants administratifs d'Etat (RA)",
                            "Restaurants administratifs d'Etat (RA)",
                        ),
                        (
                            "Restaurants des armées / police / gendarmerie",
                            "Restaurants des armées / police / gendarmerie",
                        ),
                        (
                            "Etablissements publics d'Etat (EPA ou EPIC)",
                            "Etablissements publics d'Etat (EPA ou EPIC)",
                        ),
                        (
                            "Restaurants inter-administratifs d'État (RIA)",
                            "Restaurants inter-administratifs d'État (RIA)",
                        ),
                        (
                            "Restaurants administratifs des collectivités territoriales",
                            "Restaurants administratifs des collectivités territoriales",
                        ),
                        ("Restaurants d'entreprises", "Restaurants d'entreprises"),
                        (
                            "Restaurants inter-entreprises",
                            "Restaurants inter-entreprises",
                        ),
                        (
                            "Ecole primaire (maternelle et élémentaire)",
                            "Ecole primaire (maternelle et élémentaire)",
                        ),
                        ("Secondaire collège", "Secondaire collège"),
                        (
                            "Secondaire lycée (hors agricole)",
                            "Secondaire lycée (hors agricole)",
                        ),
                        (
                            "Etablissements d'enseignement agricole",
                            "Etablissements d'enseignement agricole",
                        ),
                        ("Supérieur et Universitaire", "Supérieur et Universitaire"),
                        (
                            "Autres structures d'enseignement",
                            "Autres structures d'enseignement",
                        ),
                        ("Hôpitaux", "Hôpitaux"),
                        ("Cliniques", "Cliniques"),
                        (
                            "Autres établissements de soins",
                            "Autres établissements de soins",
                        ),
                        ("Crèche", "Crèche"),
                        ("IME / ITEP", "IME / ITEP"),
                        (
                            "ESAT / Etablissements spécialisés",
                            "ESAT / Etablissements spécialisés",
                        ),
                        (
                            "EHPAD / maisons de retraite / foyers de personnes âgées",
                            "EHPAD / maisons de retraite / foyers de personnes âgées",
                        ),
                        ("Etablissements de la PJJ", "Etablissements de la PJJ"),
                        (
                            "Autres établissements sociaux et médico-sociaux",
                            "Autres établissements sociaux et médico-sociaux",
                        ),
                        (
                            "Centre de vacances / sportif",
                            "Centre de vacances / sportif",
                        ),
                        (
                            "Autres établissements de loisirs",
                            "Autres établissements de loisirs",
                        ),
                        (
                            "Autres établissements non listés",
                            "Autres établissements non listés",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="secteurs d'activité",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="sectors",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Restaurants des prisons", "Restaurants des prisons"),
                        (
                            "Restaurants administratifs d'Etat (RA)",
                            "Restaurants administratifs d'Etat (RA)",
                        ),
                        (
                            "Restaurants des armées / police / gendarmerie",
                            "Restaurants des armées / police / gendarmerie",
                        ),
                        (
                            "Etablissements publics d'Etat (EPA ou EPIC)",
                            "Etablissements publics d'Etat (EPA ou EPIC)",
                        ),
                        (
                            "Restaurants inter-administratifs d'État (RIA)",
                            "Restaurants inter-administratifs d'État (RIA)",
                        ),
                        (
                            "Restaurants administratifs des collectivités territoriales",
                            "Restaurants administratifs des collectivités territoriales",
                        ),
                        ("Restaurants d'entreprises", "Restaurants d'entreprises"),
                        (
                            "Restaurants inter-entreprises",
                            "Restaurants inter-entreprises",
                        ),
                        (
                            "Ecole primaire (maternelle et élémentaire)",
                            "Ecole primaire (maternelle et élémentaire)",
                        ),
                        ("Secondaire collège", "Secondaire collège"),
                        (
                            "Secondaire lycée (hors agricole)",
                            "Secondaire lycée (hors agricole)",
                        ),
                        (
                            "Etablissements d'enseignement agricole",
                            "Etablissements d'enseignement agricole",
                        ),
                        ("Supérieur et Universitaire", "Supérieur et Universitaire"),
                        (
                            "Autres structures d'enseignement",
                            "Autres structures d'enseignement",
                        ),
                        ("Hôpitaux", "Hôpitaux"),
                        ("Cliniques", "Cliniques"),
                        (
                            "Autres établissements de soins",
                            "Autres établissements de soins",
                        ),
                        ("Crèche", "Crèche"),
                        ("IME / ITEP", "IME / ITEP"),
                        (
                            "ESAT / Etablissements spécialisés",
                            "ESAT / Etablissements spécialisés",
                        ),
                        (
                            "EHPAD / maisons de retraite / foyers de personnes âgées",
                            "EHPAD / maisons de retraite / foyers de personnes âgées",
                        ),
                        ("Etablissements de la PJJ", "Etablissements de la PJJ"),
                        (
                            "Autres établissements sociaux et médico-sociaux",
                            "Autres établissements sociaux et médico-sociaux",
                        ),
                        (
                            "Centre de vacances / sportif",
                            "Centre de vacances / sportif",
                        ),
                        (
                            "Autres établissements de loisirs",
                            "Autres établissements de loisirs",
                        ),
                        (
                            "Autres établissements non listés",
                            "Autres établissements non listés",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="secteurs d'activité",
            ),
        ),
        migrations.RunPython(populate_sectors_from_sectors_m2m, reverse_code=migrations.RunPython.noop),
    ]
