# Generated by Django 5.1.13 on 2025-11-25 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0220_canteen_sector_list_historicalcanteen_sector_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="value_autres_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Autres produits frais, surgelés et d’épicerie, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_bio_dont_commerce_equitable_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Bio dont commerce équitable - Valeur annuelle HT",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_boissons_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Boissons, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_boulangerie_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Boulangerie/Pâtisserie fraîches et surgelées, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_charcuterie_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Charcuterie, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_commerce_equitable_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Valeur totale (HT) des achats commerce équitable (hors bio)",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_fruits_et_legumes_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Fruits et légumes frais et surgelés, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_produits_de_la_mer_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Produits aquatiques frais et surgelés, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_produits_laitiers_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="BOF (Produits laitiers, beurre et œufs), Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="value_viandes_volailles_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Viandes et volailles fraîches et surgelées, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_autres_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Autres produits frais, surgelés et d’épicerie, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_bio_dont_commerce_equitable_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Bio dont commerce équitable - Valeur annuelle HT",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_boissons_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Boissons, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_boulangerie_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Boulangerie/Pâtisserie fraîches et surgelées, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_charcuterie_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Charcuterie, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_commerce_equitable_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Valeur totale (HT) des achats commerce équitable (hors bio)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_fruits_et_legumes_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Fruits et légumes frais et surgelés, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_produits_de_la_mer_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Produits aquatiques frais et surgelés, Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_produits_laitiers_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="BOF (Produits laitiers, beurre et œufs), Bio dont commerce équitable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="value_viandes_volailles_bio_dont_commerce_equitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Viandes et volailles fraîches et surgelées, Bio dont commerce équitable",
            ),
        ),
    ]
