# Generated by Django 5.1.13 on 2025-12-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0222_alter_diagnostic_value_meat_poultry_france_ht_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnostic",
            old_name="value_commerce_equitable_ht",
            new_name="value_egalim_others_dont_commerce_equitable_ht",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="value_commerce_equitable_ht",
            new_name="value_egalim_others_dont_commerce_equitable_ht",
        ),
    ]
