# Generated by Django 5.1.13 on 2025-12-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0223_rename_value_commerce_equitable_ht_diagnostic_value_egalim_others_dont_commerce_equitable_ht_and_mor",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnostic",
            old_name="value_fish_ht",
            new_name="value_produits_de_la_mer",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="value_fish_egalim_ht",
            new_name="value_produits_de_la_mer_egalim",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="value_meat_poultry_ht",
            new_name="value_viandes_volailles",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="value_meat_poultry_egalim_ht",
            new_name="value_viandes_volailles_egalim",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="value_fish_ht",
            new_name="value_produits_de_la_mer",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="value_fish_egalim_ht",
            new_name="value_produits_de_la_mer_egalim",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="value_meat_poultry_ht",
            new_name="value_viandes_volailles",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="value_meat_poultry_egalim_ht",
            new_name="value_viandes_volailles_egalim",
        ),
        migrations.RemoveField(
            model_name="diagnostic",
            name="value_meat_poultry_france_ht",
        ),
        migrations.RemoveField(
            model_name="historicaldiagnostic",
            name="value_meat_poultry_france_ht",
        ),
    ]
