# Generated by Django 5.1.13 on 2025-12-03 14:00

import data.fields
from django.db import migrations, models


def update_purchase_characteristics_rename_short_distribution_to_circuit_court_forward(apps, schema_editor):
    # Purchase = apps.get_model("data", "Purchase")
    schema_editor.execute(
        """
        UPDATE data_purchase
        SET characteristics = array_replace(characteristics, 'SHORT_DISTRIBUTION', 'CIRCUIT_COURT')
        WHERE 'SHORT_DISTRIBUTION' = ANY(characteristics)
        """
    )

def update_purchase_characteristics_rename_short_distribution_to_circuit_court_backward(apps, schema_editor):
    # Purchase = apps.get_model("data", "Purchase")
    schema_editor.execute(
        """
        UPDATE data_purchase
        SET characteristics = array_replace(characteristics, 'CIRCUIT_COURT', 'SHORT_DISTRIBUTION')
        WHERE 'CIRCUIT_COURT' = ANY(characteristics)
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0226_rename_value_autres_aocaop_igp_stg_diagnostic_valeur_autres_aocaop_igp_stg_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_autres_short_distribution",
            new_name="valeur_autres_circuit_court",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_boissons_short_distribution",
            new_name="valeur_boissons_circuit_court",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_boulangerie_short_distribution",
            new_name="valeur_boulangerie_circuit_court",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_charcuterie_short_distribution",
            new_name="valeur_charcuterie_circuit_court",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_fruits_et_legumes_short_distribution",
            new_name="valeur_fruits_et_legumes_circuit_court",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_produits_de_la_mer_short_distribution",
            new_name="valeur_produits_de_la_mer_circuit_court",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_produits_laitiers_short_distribution",
            new_name="valeur_produits_laitiers_circuit_court",
        ),
        migrations.RenameField(
            model_name="diagnostic",
            old_name="valeur_viandes_volailles_short_distribution",
            new_name="valeur_viandes_volailles_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_autres_short_distribution",
            new_name="valeur_autres_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_boissons_short_distribution",
            new_name="valeur_boissons_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_boulangerie_short_distribution",
            new_name="valeur_boulangerie_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_charcuterie_short_distribution",
            new_name="valeur_charcuterie_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_fruits_et_legumes_short_distribution",
            new_name="valeur_fruits_et_legumes_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_produits_de_la_mer_short_distribution",
            new_name="valeur_produits_de_la_mer_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_produits_laitiers_short_distribution",
            new_name="valeur_produits_laitiers_circuit_court",
        ),
        migrations.RenameField(
            model_name="historicaldiagnostic",
            old_name="valeur_viandes_volailles_short_distribution",
            new_name="valeur_viandes_volailles_circuit_court",
        ),
        migrations.AlterField(
            model_name="purchase",
            name="characteristics",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("BIO", "Bio"),
                        ("CONVERSION_BIO", "En conversion bio"),
                        ("LABEL_ROUGE", "Label rouge"),
                        ("AOCAOP", "AOC / AOP"),
                        ("IGP", "Indication géographique protégée"),
                        ("STG", "Spécialité traditionnelle garantie"),
                        ("HVE", "Haute valeur environnementale"),
                        ("PECHE_DURABLE", "Pêche durable"),
                        ("RUP", "Région ultrapériphérique"),
                        ("FERMIER", "Fermier"),
                        (
                            "EXTERNALITES",
                            "Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie",
                        ),
                        ("COMMERCE_EQUITABLE", "Commerce équitable"),
                        (
                            "PERFORMANCE",
                            "Produits acquis sur la base de leurs performances en matière environnementale",
                        ),
                        ("EQUIVALENTS", "Produits équivalents"),
                        ("FRANCE", "Provenance France"),
                        ("CIRCUIT_COURT", "Circuit-court"),
                        ("LOCAL", "Produit local"),
                    ],
                    max_length=255,
                    null=True,
                    verbose_name="caractéristique",
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="caractéristiques",
            ),
        ),
        migrations.RunPython(update_purchase_characteristics_rename_short_distribution_to_circuit_court_forward, reverse_code=update_purchase_characteristics_rename_short_distribution_to_circuit_court_backward),
    ]
