# Generated by Django 5.1.14 on 2025-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0227_rename_valeur_autres_short_distribution_diagnostic_valeur_autres_circuit_court_and_more_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='production_type',
            field=models.CharField(blank=True, choices=[('central', 'Cuisine centrale'), ('central_serving', 'Cuisine centrale et site'), ('site', 'Restaurant avec cuisine sur place'), ('site_cooked_elsewhere', 'Restaurant satellite')], max_length=255, null=True, verbose_name='mode de production'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='production_type',
            field=models.CharField(blank=True, choices=[('central', 'Cuisine centrale'), ('central_serving', 'Cuisine centrale et site'), ('site', 'Restaurant avec cuisine sur place'), ('site_cooked_elsewhere', 'Restaurant satellite')], max_length=255, null=True, verbose_name='mode de production'),
        ),
    ]
