# Generated by Django 5.1.13 on 2025-12-16 16:32

from django.db import migrations, models


def update_purchase_local_definition_rename_department_to_departement_forward(apps, schema_editor):
    # Purchase = apps.get_model("data", "Purchase")
    schema_editor.execute(
        """
        UPDATE data_purchase
        SET local_definition = 'DEPARTEMENT'
        WHERE local_definition = 'DEPARTMENT'
        """
    )

def update_purchase_local_definition_rename_department_to_departement_backward(apps, schema_editor):
    # Purchase = apps.get_model("data", "Purchase")
    schema_editor.execute(
        """
        UPDATE data_purchase
        SET local_definition = 'DEPARTMENT'
        WHERE local_definition = 'DEPARTEMENT'
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0228_alter_canteen_production_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="local_definition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGION", "Région"),
                    ("DEPARTEMENT", "Département"),
                    ("AUTOUR_SERVICE", "200 km autour du lieu de service"),
                    ("AUTRE", "Autre"),
                ],
                max_length=255,
                null=True,
                verbose_name="définition de local",
            ),
        ),
        migrations.RunPython(
            update_purchase_local_definition_rename_department_to_departement_forward,
            update_purchase_local_definition_rename_department_to_departement_backward,
        ),
    ]
