# Generated by Django 5.1.13 on 2025-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0229_alter_purchase_local_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Données calculées"
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="number_of_managed_cantines",
        ),
    ]
