# Generated by Django 5.1.14 on 2026-01-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0230_user_add_data_remove_user_number_of_managed_cantines'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='canteen',
            name='declaration_donnees_2025',
            field=models.BooleanField(default=False, verbose_name='a télédéclaré ses données de 2025'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='declaration_donnees_2025',
            field=models.BooleanField(default=False, verbose_name='a télédéclaré ses données de 2025'),
        ),
    ]
