# Generated by Django 5.1.13 on 2026-01-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0231_alter_user_managers_canteen_declaration_donnees_2025_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("groupe", "Groupe"),
                    ("central", "Cuisine centrale"),
                    ("central_serving", "Cuisine centrale et site"),
                    ("site", "Restaurant avec cuisine sur place"),
                    ("site_cooked_elsewhere", "Restaurant satellite"),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="canteen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostics",
                to="data.canteen",
                verbose_name="cantine",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcanteen",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("groupe", "Groupe"),
                    ("central", "Cuisine centrale"),
                    ("central_serving", "Cuisine centrale et site"),
                    ("site", "Restaurant avec cuisine sur place"),
                    ("site_cooked_elsewhere", "Restaurant satellite"),
                ],
                max_length=255,
                null=True,
                verbose_name="mode de production",
            ),
        ),
    ]
