# Generated by Django 5.1.13 on 2026-01-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0232_alter_canteen_production_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.canteen",
                verbose_name="Groupe",
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.canteen",
                verbose_name="Groupe",
            ),
        ),
    ]
