# Generated by Django 5.1.13 on 2026-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0233_canteen_groupe_historicalcanteen_groupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="is_filled",
            field=models.BooleanField(
                default=False, verbose_name="cantine complète (champ calculé)"
            ),
        ),
        migrations.AddField(
            model_name="historicalcanteen",
            name="is_filled",
            field=models.BooleanField(
                default=False, verbose_name="cantine complète (champ calculé)"
            ),
        ),
    ]
