# Generated by Django 5.1.13 on 2026-01-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0234_canteen_is_filled_historicalcanteen_is_filled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_brevo_update",
            new_name="brevo_last_update_date",
        ),
        migrations.AddField(
            model_name="user",
            name="brevo_is_deleted",
            field=models.BooleanField(
                default=False,
                verbose_name="Indique si le contact a été supprimé de Brevo",
            ),
        ),
    ]
