# Generated by Django 5.1.15 on 2026-01-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0235_user_brevo_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_no_canteen_first_reminder",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_no_canteen_second_reminder",
        ),
    ]
