# Generated by Django 5.1.15 on 2026-01-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0235_user_brevo_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canteen",
            name="email_no_diagnostic_first_reminder",
        ),
        migrations.RemoveField(
            model_name="historicalcanteen",
            name="email_no_diagnostic_first_reminder",
        ),
    ]
