# Generated by Django 5.1.15 on 2026-01-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0236_remove_user_email_no_canteen_first_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfailure',
            name='import_type',
            field=models.TextField(blank=True, choices=[('CANTEEN_ONLY', 'Cantines seules'), ('CANTEEN_ONLY_OR_DIAGNOSTIC_SIMPLE', 'Cantines seules ou avec un diagnostic simple'), ('DIAGNOSTIC_SIMPLE', 'Diagnostic simple'), ('DIAGNOSTIC_COMPLETE', 'Cantines avec diagnostic complet'), ('CC_SIMPLE', 'Cuisines centrales avec un diagnostic simple et leurs restaurants satellites'), ('CC_COMPLETE', 'Cuisines centrales avec un diagnostic complet et leurs restaurants satellites'), ('PURCHASE_SIRET', 'Achats par SIRET'), ('PURCHASE_ID', 'Achats par ID')], null=True, verbose_name="type d'import"),
        ),
    ]
