# Generated by Django 5.1.15 on 2026-01-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0237_alter_importfailure_import_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='satellite_canteens_count',
        ),
        migrations.RemoveField(
            model_name='historicalcanteen',
            name='satellite_canteens_count',
        ),
    ]
