# Generated by Django 5.1.15 on 2026-02-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0239_remove_canteen_email_no_diagnostic_first_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='siret_etat_administratif',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='état administratif du siret (obtenu via API Recherche Entreprises)'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='siret_inconnu',
            field=models.BooleanField(default=False, verbose_name='le siret de cette cantine est inconnu (obtenu via API Recherche Entreprises)'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='siret_etat_administratif',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='état administratif du siret (obtenu via API Recherche Entreprises)'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='siret_inconnu',
            field=models.BooleanField(default=False, verbose_name='le siret de cette cantine est inconnu (obtenu via API Recherche Entreprises)'),
        ),
    ]
