# Generated by Django 5.1.15 on 2026-02-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0240_canteen_siret_etat_administratif_and_siret_inconnu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfailure',
            name='import_type',
            field=models.TextField(blank=True, choices=[('CANTEEN_ONLY', 'Cantines seules'), ('CANTEEN_MANAGERS', 'Cantines avec gestionnaires'), ('CANTEEN_ONLY_OR_DIAGNOSTIC_SIMPLE', 'Cantines seules ou avec un diagnostic simple'), ('DIAGNOSTIC_SIMPLE_SIRET', 'Bilans simples par SIRET'), ('DIAGNOSTIC_SIMPLE_ID', 'Bilans simples par ID'), ('DIAGNOSTIC_COMPLETE', 'Cantines avec diagnostic complet'), ('CC_SIMPLE', 'Cuisines centrales avec un diagnostic simple et leurs restaurants satellites'), ('CC_COMPLETE', 'Cuisines centrales avec un diagnostic complet et leurs restaurants satellites'), ('PURCHASE_SIRET', 'Achats par SIRET'), ('PURCHASE_ID', 'Achats par ID')], null=True, verbose_name="type d'import"),
        ),
    ]
