# Generated by Django 5.1.15 on 2026-02-19 17:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0242_alter_importfailure_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_aocaop_igp_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, AOC / AOP / IGP / STG"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Bio"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_bio_dont_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Bio dont commerce équitable"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_circuit_court',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Circuit-court"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Commerce équitable"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_externalites',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Fermier"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_hve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Haute valeur environnementale"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_label_rouge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Label rouge"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Produit local"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Pêche durable"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Produits acquis sur la base de leurs performances en matière environnementale"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_rup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Région ultrapériphérique"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_aocaop_igp_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, AOC / AOP / IGP / STG"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Bio"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_bio_dont_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Bio dont commerce équitable"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_circuit_court',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Circuit-court"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Commerce équitable"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_externalites',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Fermier"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_hve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Haute valeur environnementale"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_label_rouge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Label rouge"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Produit local"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Pêche durable"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Produits acquis sur la base de leurs performances en matière environnementale"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_rup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Région ultrapériphérique"),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='family',
            field=models.CharField(blank=True, choices=[('VIANDES_VOLAILLES', 'Viandes et volailles fraîches et surgelées'), ('CHARCUTERIE', 'Charcuterie'), ('PRODUITS_DE_LA_MER', "Poissons, produits de la mer et de l'aquaculture"), ('FRUITS_ET_LEGUMES', 'Fruits et légumes frais et surgelés'), ('PRODUITS_LAITIERS', 'BOF (Produits laitiers, beurre et œufs)'), ('BOULANGERIE', 'Boulangerie/Pâtisserie fraîches et surgelées'), ('BOISSONS', 'Boissons'), ('AUTRES', "Autres produits frais, surgelés et d'épicerie")], max_length=255, null=True, verbose_name='famille de produits'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Origine France"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, non-EGalim"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boissons_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, Origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boissons_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie/Pâtisserie fraîches et surgelées, Origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie/Pâtisserie fraîches et surgelées, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_charcuterie_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, Origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_charcuterie_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, Origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) poissons et produits aquatiques, EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Origine France"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, non-EGalim"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_produits_laitiers_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), Origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_produits_laitiers_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), non-EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_viandes_volailles_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) viandes et volailles fraiches ou surgelées, EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_viandes_volailles_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, Origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_viandes_volailles_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Origine France"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, non-EGalim"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boissons_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, Origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boissons_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie/Pâtisserie fraîches et surgelées, Origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie/Pâtisserie fraîches et surgelées, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_charcuterie_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, Origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_charcuterie_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, Origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) poissons et produits aquatiques, EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Origine France"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, non-EGalim"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_produits_laitiers_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), Origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_produits_laitiers_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), non-EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_viandes_volailles_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) viandes et volailles fraiches ou surgelées, EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_viandes_volailles_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, Origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_viandes_volailles_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, non-EGalim'),
        ),
    ]
