# Generated by Django 5.1.10 on 2025-10-08 17:07

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0245_alter_diagnostic_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="invalid_reason_list",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("VALUE_TOTAL_HT_VIDE", "Valeur totale des achats vide"),
                        ("VALUE_BIO_HT_VIDE", "Valeur totale des achats bio vide"),
                        (
                            "CANTINE_SUPPRIMEE_PENDANT_CAMPAGNE",
                            "Cantine supprimée pendant la campagne",
                        ),
                        ("CANTINE_SANS_SIRET_OU_SIREN", "Cantine sans siret ou siren"),
                        ("VALEURS_ABERRANTES", "Valeurs aberrantes"),
                        ("DOUBLON_1TD1SITE", "Doublon 1TD1Site"),
                        ("VALEURS_INCOHERENTES", "Valeurs incohérentes"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="bilan ignoré dans les stats (raisons)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="invalid_reason_list",
            field=data.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("VALUE_TOTAL_HT_VIDE", "Valeur totale des achats vide"),
                        ("VALUE_BIO_HT_VIDE", "Valeur totale des achats bio vide"),
                        (
                            "CANTINE_SUPPRIMEE_PENDANT_CAMPAGNE",
                            "Cantine supprimée pendant la campagne",
                        ),
                        ("CANTINE_SANS_SIRET_OU_SIREN", "Cantine sans siret ou siren"),
                        ("VALEURS_ABERRANTES", "Valeurs aberrantes"),
                        ("DOUBLON_1TD1SITE", "Doublon 1TD1Site"),
                        ("VALEURS_INCOHERENTES", "Valeurs incohérentes"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="bilan ignoré dans les stats (raisons)",
            ),
        ),
    ]
