# Generated by Django 5.2.11 on 2026-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0246_diagnostic_invalid_reason_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='teledeclaration_in_rapport',
            field=models.BooleanField(blank=True, null=True, verbose_name='la télédéclaration est utilisée dans le rapport'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='teledeclaration_in_rapport',
            field=models.BooleanField(blank=True, null=True, verbose_name='la télédéclaration est utilisée dans le rapport'),
        ),
    ]
