# Generated by Django 5.2.11 on 2026-03-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0246_diagnostic_invalid_reason_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='objectifs_egalim_atteints',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_egalim_hors_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='objectifs_egalim_atteints',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_egalim_hors_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
