# Generated by Django 5.2.11 on 2026-03-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0246_diagnostic_invalid_reason_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='city_insee_code',
            field=models.TextField(blank=True, help_text="Le code INSEE est récupéré automatiquement grâce au SIRET ou code postal pour les cantines sans SIRET. Si ce dernier est incorrect : ne pas le corriger directement mais passer le champ à vide, il sera automatiquement renseigné avec les informations d'annuaires entreprises pour les cantines avec SIRET dans les 24 heures.", null=True, verbose_name='Code INSEE'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='city_insee_code',
            field=models.TextField(blank=True, help_text="Le code INSEE est récupéré automatiquement grâce au SIRET ou code postal pour les cantines sans SIRET. Si ce dernier est incorrect : ne pas le corriger directement mais passer le champ à vide, il sera automatiquement renseigné avec les informations d'annuaires entreprises pour les cantines avec SIRET dans les 24 heures.", null=True, verbose_name='Code INSEE'),
        ),
    ]
