# Generated by Django 5.2.11 on 2026-03-05 12:03

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0247_diagnostic_generated_from_groupe_diagnostic_and_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='invalid_reason_list',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('CANTINE_SUPPRIMEE', 'Cantine supprimée'), ('CANTINE_SOFT_SUPPRIMEE_PENDANT_CAMPAGNE', 'Cantine soft supprimée pendant la campagne'), ('CANTINE_SANS_SIRET_OU_SIREN', 'Cantine sans siret ou siren'), ('TELEDECLARATION_MODE_SATELLITE_WITHOUT_APPRO', 'Télédeclaration mode satellite without appro'), ('VALEUR_TOTALE_VIDE', 'Valeur totale des achats vide'), ('VALEUR_BIO_AGG_VIDE', 'Valeur totale des achats bio vide'), ('VALEURS_ABERRANTES', 'Valeurs aberrantes'), ('VALEURS_INCOHERENTES', 'Valeurs incohérentes'), ('DOUBLON_1TD1SITE', 'Doublon 1TD1Site')], max_length=255), blank=True, null=True, size=None, verbose_name='bilan ignoré dans les stats (raisons)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='invalid_reason_list',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('CANTINE_SUPPRIMEE', 'Cantine supprimée'), ('CANTINE_SOFT_SUPPRIMEE_PENDANT_CAMPAGNE', 'Cantine soft supprimée pendant la campagne'), ('CANTINE_SANS_SIRET_OU_SIREN', 'Cantine sans siret ou siren'), ('TELEDECLARATION_MODE_SATELLITE_WITHOUT_APPRO', 'Télédeclaration mode satellite without appro'), ('VALEUR_TOTALE_VIDE', 'Valeur totale des achats vide'), ('VALEUR_BIO_AGG_VIDE', 'Valeur totale des achats bio vide'), ('VALEURS_ABERRANTES', 'Valeurs aberrantes'), ('VALEURS_INCOHERENTES', 'Valeurs incohérentes'), ('DOUBLON_1TD1SITE', 'Doublon 1TD1Site')], max_length=255), blank=True, null=True, size=None, verbose_name='bilan ignoré dans les stats (raisons)'),
        ),
    ]
