# Generated by Django 5.1 on 2025-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0247_diagnostic_pourcentage_bio_egalim_et_objectifs_atteints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="diagnostic",
            name="annual_diagnostic",
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="generated_from_groupe_diagnostic",
            field=models.BooleanField(
                default=False,
                verbose_name="A été automatiquement généré depuis le bilan du groupe (seulement pertinent pour les satellites)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostic",
            name="generated_from_groupe_diagnostic",
            field=models.BooleanField(
                default=False,
                verbose_name="A été automatiquement généré depuis le bilan du groupe (seulement pertinent pour les satellites)",
            ),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="central_kitchen_diagnostic_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "APPRO",
                        "Ce diagnostic concerne les données d'approvisionnement de tous les restaurants satellites",
                    ),
                    (
                        "ALL",
                        "Ce diagnostic concerne toutes les données des restaurants satellites",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="Quelles données sont déclarées par ce groupe ? (seulement pertinent pour les groupes)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnostic",
            name="central_kitchen_diagnostic_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "APPRO",
                        "Ce diagnostic concerne les données d'approvisionnement de tous les restaurants satellites",
                    ),
                    (
                        "ALL",
                        "Ce diagnostic concerne toutes les données des restaurants satellites",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="Quelles données sont déclarées par ce groupe ? (seulement pertinent pour les groupes)",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnostic",
            constraint=models.UniqueConstraint(
                fields=("canteen", "year", "generated_from_groupe_diagnostic"),
                name="annual_diagnostic",
            ),
        ),
    ]
