# Generated by Django 5.2.11 on 2026-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0248_diagnostic_invalid_reason_list_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='bio_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='egalim_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='has_egalim_objectives_reached',
            field=models.BooleanField(blank=True, null=True, verbose_name='objectifs EGalim atteints'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='bio_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='egalim_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='has_egalim_objectives_reached',
            field=models.BooleanField(blank=True, null=True, verbose_name='objectifs EGalim atteints'),
        ),
    ]
