# Generated by Django 5.2.11 on 2026-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0249_diagnostic_bio_percent_diagnostic_egalim_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='egalim_hors_bio_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='egalim_hors_bio_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
