# Generated by Django 5.2.11 on 2026-04-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0249_diagnostic_invalid_reason_list_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('CORRECTION', 'En correction'), ('SUBMITTED', 'Télédéclaré')], default='DRAFT', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('CORRECTION', 'En correction'), ('SUBMITTED', 'Télédéclaré')], default='DRAFT', max_length=255, verbose_name='status'),
        ),
    ]
