# Generated by Django 5.2.13 on 2026-05-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0250_alter_diagnostic_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='geolocation_bot_attempts',
        ),
        migrations.RemoveField(
            model_name='historicalcanteen',
            name='geolocation_bot_attempts',
        ),
    ]
