# Generated by Django 5.2.14 on 2026-05-13 07:35

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0251_remove_canteen_geolocation_bot_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='characteristics',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('BIO', 'Bio'), ('CONVERSION_BIO', 'En conversion bio'), ('LABEL_ROUGE', 'Label rouge'), ('AOCAOP', 'AOC / AOP'), ('IGP', 'Indication géographique protégée'), ('STG', 'Spécialité traditionnelle garantie'), ('HVE', 'Haute valeur environnementale'), ('PECHE_DURABLE', 'Pêche durable'), ('RUP', 'Région ultrapériphérique'), ('FERMIER', 'Fermier'), ('EXTERNALITES', 'Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie'), ('COMMERCE_EQUITABLE', 'Commerce équitable'), ('PERFORMANCE', 'Produits acquis sur la base de leurs performances en matière environnementale'), ('EQUIVALENTS', 'Produits équivalents'), ('EUROPE', 'Origine Europe'), ('FRANCE', 'Origine France'), ('CIRCUIT_COURT', 'Circuit-court'), ('LOCAL', 'Produit local')], max_length=255, null=True, verbose_name='caractéristique'), blank=True, null=True, size=None, verbose_name='caractéristiques'),
        ),
    ]
