# Generated by Django 5.2.14 on 2026-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0252_alter_purchase_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='local_definition',
            field=models.CharField(blank=True, choices=[('REGION', 'Région'), ('DEPARTEMENT', 'Département'), ('AUTOUR_SERVICE', '200 km autour du lieu de service'), ('PAT', 'Issu du Projet Alimentaire Territorial (PAT)'), ('AUTRE', 'Autre')], max_length=255, null=True, verbose_name='définition de local'),
        ),
    ]
