# Generated by Django 5.2.14 on 2026-05-20 09:53

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0252_alter_purchase_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='warning_reason_list',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('CIRCUIT_COURT_SUP_FRANCE', 'Origine France (dont circuit-court) > Origine France'), ('LOCAL_SUP_FRANCE', 'Origine France (dont local) > Origine France'), ('COMMERCE_EQUITABLE_SUP_BIO', 'Bio dont commerce équitable > Bio')], max_length=255), blank=True, null=True, size=None, verbose_name="bilan avec d'autres soucis data (raisons)"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='warning_reason_list',
            field=data.fields.ChoiceArrayField(base_field=models.CharField(choices=[('CIRCUIT_COURT_SUP_FRANCE', 'Origine France (dont circuit-court) > Origine France'), ('LOCAL_SUP_FRANCE', 'Origine France (dont local) > Origine France'), ('COMMERCE_EQUITABLE_SUP_BIO', 'Bio dont commerce équitable > Bio')], max_length=255), blank=True, null=True, size=None, verbose_name="bilan avec d'autres soucis data (raisons)"),
        ),
    ]
