# Generated by Django 5.2.14 on 2026-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0257_alter_diagnostic_objectifs_egalim_atteints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='cout_repas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='le coût repas est calculé en divisant la valeur totale annuelle par le nombre de repas annuels de la cantine', max_digits=5, null=True, verbose_name='coût repas (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='cout_repas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='le coût repas est calculé en divisant la valeur totale annuelle par le nombre de repas annuels de la cantine', max_digits=5, null=True, verbose_name='coût repas (champ calculé)'),
        ),
    ]
