# Generated by Django 5.2.14 on 2026-05-28 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0257_canteen_creation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canteens_created', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur qui a créé la cantine'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics_created', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur qui a créé le diagnostic'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='creation_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur qui a créé la cantine'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='creation_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur qui a créé le diagnostic'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_created', to=settings.AUTH_USER_MODEL, verbose_name="utilisateur qui a créé l'achat"),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='import_source',
            field=models.TextField(blank=True, null=True, verbose_name="source de l'import de l'achat"),
        ),
    ]
