# Generated by Django 5.2.14 on 2026-05-27 14:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0258_alter_creation_user_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='objectifs_egalim_atteints',
            field=models.BooleanField(blank=True, null=True, verbose_name='objectifs EGalim atteints (champ calculé)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='objectifs_egalim_atteints',
            field=models.BooleanField(blank=True, null=True, verbose_name='objectifs EGalim atteints (champ calculé)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='pourcentage_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage bio (champ calculé)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='pourcentage_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage EGalim (champ calculé)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='pourcentage_egalim_hors_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage EGalim hors bio (champ calculé)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='pourcentage_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage bio (champ calculé)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='pourcentage_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage EGalim (champ calculé)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='pourcentage_egalim_hors_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage EGalim hors bio (champ calculé)'),
        ),
    ]
