# Generated by Django 5.2.14 on 2026-05-31 21:53

import data.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0260_diagnostic_cout_repas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='local_definition',
            new_name='definition_local',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='family',
            new_name='famille_produits',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='provider',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='price_ht',
            new_name='prix_ht',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='characteristics',
            new_name='caracteristiques',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='invoice_file',
            new_name='facture',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='canteen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='data.canteen', verbose_name='cantine'),
        ),
    ]
