# Generated by Django 5.2.14 on 2026-06-03 12:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0260_diagnostic_cout_repas'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_autres_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Origine Europe (hors France)"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boissons_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boulangerie_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie/Pâtisserie fraîches et surgelées, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_charcuterie_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Origine Europe (hors France)"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_laitiers_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_viandes_volailles_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_autres_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Origine Europe (hors France)"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boissons_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie/Pâtisserie fraîches et surgelées, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_charcuterie_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Origine Europe (hors France)"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_laitiers_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), Origine Europe (hors France)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_viandes_volailles_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, Origine Europe (hors France)'),
        ),
    ]
