# Generated by Django 5.2.14 on 2026-06-08 13:52

import data.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0262_alter_purchase_caracteristiques_europe_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='groupe_snapshot',
            field=models.JSONField(blank=True, encoder=data.utils.CustomJSONEncoder, null=True, verbose_name='groupe (copie lors de la génération depuis le bilan du groupe) (seulement pertinent pour les satellites)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='groupe_snapshot',
            field=models.JSONField(blank=True, encoder=data.utils.CustomJSONEncoder, null=True, verbose_name='groupe (copie lors de la génération depuis le bilan du groupe) (seulement pertinent pour les satellites)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='satellites_snapshot',
            field=models.JSONField(blank=True, encoder=data.utils.CustomJSONEncoder, null=True, verbose_name='satellites (copie au moment de la télédéclaration) (seulement pertinent pour les groupes)'),
        ),
    ]
