# Generated by Django 5.2.14 on 2026-06-17 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0263_diagnostic_groupe_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwastemeasurement',
            name='creation_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name="Source de création de l'évaluation du gaspillage alimentaire"),
        ),
        migrations.AddField(
            model_name='historicalwastemeasurement',
            name='creation_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="utilisateur qui a créé l'évaluation du gaspillage alimentaire"),
        ),
        migrations.AddField(
            model_name='wastemeasurement',
            name='creation_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name="Source de création de l'évaluation du gaspillage alimentaire"),
        ),
        migrations.AddField(
            model_name='wastemeasurement',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_measurements_created', to=settings.AUTH_USER_MODEL, verbose_name="utilisateur qui a créé l'évaluation du gaspillage alimentaire"),
        ),
        migrations.AlterField(
            model_name='wastemeasurement',
            name='period_end_date',
            field=models.DateField(verbose_name="date de fin"),
        ),
        migrations.AlterField(
            model_name='historicalwastemeasurement',
            name='period_end_date',
            field=models.DateField(verbose_name="date de fin"),
        )
    ]
