# Generated by Django 5.2.14 on 2026-06-22 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0264_wastemeasurement_creation_user_and_source'),
        ('oauth2_provider', '__first__'),
        ('oauth2_provider', '__first__'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='creation_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_created', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name="app OAuth2 (API) qui a créé l'achat"),
        ),
        migrations.AddField(
            model_name='canteen',
            name='creation_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canteens_created', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='app OAuth2 (API) qui a créé la cantine'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='creation_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics_created', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='app OAuth2 (API) qui a créé le diagnostic'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='creation_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='app OAuth2 (API) qui a créé la cantine'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='creation_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='app OAuth2 (API) qui a créé le diagnostic'),
        ),
        migrations.AddField(
            model_name='historicalwastemeasurement',
            name='creation_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name="app OAuth2 (API) qui a créé l'évaluation du gaspillage alimentaire"),
        ),
        migrations.AddField(
            model_name='wastemeasurement',
            name='creation_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_measurements_created', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name="app OAuth2 (API) qui a créé l'évaluation du gaspillage alimentaire"),
        ),
    ]
