# Generated by Django 5.2.14 on 2026-06-22 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0264_wastemeasurement_creation_user_and_source'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwastemeasurement',
            name='creation_source_api_app',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='OAuth app which created this record'),
        ),
        migrations.AddField(
            model_name='wastemeasurement',
            name='creation_source_api_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_measurements_created', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='OAuth app which created this record'),
        ),
    ]
