# Generated by Django 5.2.14 on 2026-06-23 09:56

import django.core.validators
from django.db import migrations, models


def migrate_autour_service_to_km(apps, schema_editor):
    """
    AUTOUR_SERVICE --> KM
    Set definition_local_km to 200 for all purchases that had AUTOUR_SERVICE as definition_local
    """
    Purchase = apps.get_model('data', 'Purchase')
    Purchase.objects.filter(definition_local='AUTOUR_SERVICE').update(
        definition_local='KM',
        definition_local_km=200
    )


def reverse_migrate_autour_service_to_km(apps, schema_editor):
    """
    Reverse
    """
    Purchase = apps.get_model('data', 'Purchase')
    Purchase.objects.filter(definition_local='KM', definition_local_km=200).update(
        definition_local='AUTOUR_SERVICE',
        definition_local_km=None
    )


def migrate_autre_to_km(apps, schema_editor):
    """
    AUTRE --> KM
    """
    Purchase = apps.get_model('data', 'Purchase')
    Purchase.objects.filter(definition_local='AUTRE').update(
        definition_local='KM'
    )


def reverse_migrate_autre_to_km(apps, schema_editor):
    """
    Reverse
    """
    Purchase = apps.get_model('data', 'Purchase')
    Purchase.objects.filter(definition_local='KM').update(
        definition_local='AUTRE'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0265_creation_source_api_oauth2_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='definition_local',
            field=models.CharField(blank=True, choices=[('PAT', 'Issu du Projet Alimentaire Territorial (PAT)'), ('COMMUNE', 'Commune et/ou intercommunalité'), ('DEPARTEMENT', 'Département'), ('REGION', 'Région'), ('KM', 'Distance en km')], max_length=255, null=True, verbose_name='définition de local'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='definition_local_km',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='définition de local (distance en km)'),
        ),
        migrations.RunPython(migrate_autour_service_to_km, reverse_migrate_autour_service_to_km),
        migrations.RunPython(migrate_autre_to_km, reverse_migrate_autre_to_km),
    ]
