# Generated by Django 5.2.14 on 2026-06-30 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0266_purchase_definition_local_km'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteledeclaration',
            name='authentication_method',
        ),
        migrations.AddField(
            model_name='historicalteledeclaration',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicalresourceaction',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicalwastemeasurement',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='history_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Application OAuth2 (API) qui a fait la modification'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='history_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Application OAuth2 (API) qui a fait la modification'),
        ),
        migrations.AddField(
            model_name='historicalresourceaction',
            name='history_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Application OAuth2 (API) qui a fait la modification'),
        ),
        migrations.AddField(
            model_name='historicalteledeclaration',
            name='history_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Application OAuth2 (API) qui a fait la modification'),
        ),
        migrations.AddField(
            model_name='historicalwastemeasurement',
            name='history_source_api_oauth2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Application OAuth2 (API) qui a fait la modification'),
        ),
    ]
