# Generated by Django 5.2.14 on 2026-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0266_purchase_definition_local_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteledeclaration',
            name='authentication_method',
        ),
        migrations.AddField(
            model_name='historicalteledeclaration',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicalresourceaction',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
        migrations.AddField(
            model_name='historicalwastemeasurement',
            name='history_source',
            field=models.CharField(blank=True, choices=[('APP', 'APP'), ('API', 'API'), ('IMPORT', 'IMPORT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='source de modification'),
        ),
    ]
