# Generated by Django 5.2.14 on 2026-07-06 16:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0267_history_source_and_api_oauth2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_aocaop_igp_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, AOC / AOP / IGP / STG'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Bio'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_bio_dont_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Bio dont commerce équitable'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_circuit_court',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Origine France (dont circuit-court)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Commerce équitable'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_externalites',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Fermier (non applicable)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Origine France'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_hve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Haute valeur environnementale'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_label_rouge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Label rouge'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Origine France (dont local)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Pêche durable (non applicable)'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Produits acquis sur la base de leurs performances en matière environnementale'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_rup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Région ultrapériphérique'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_aocaop_igp_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, AOC / AOP / IGP / STG'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_bio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Bio'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_bio_dont_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Bio dont commerce équitable'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_circuit_court',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Origine France (dont circuit-court)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_commerce_equitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Commerce équitable'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_externalites',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Produit prenant en compte les coûts imputés aux externalités environnementales pendant son cycle de vie'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Fermier (non applicable)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Origine France'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_hve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Haute valeur environnementale'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_label_rouge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Label rouge'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Origine France (dont local)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_non_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, non-EGalim'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Pêche durable (non applicable)'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Produits acquis sur la base de leurs performances en matière environnementale'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_rup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Région ultrapériphérique'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='famille_produits',
            field=models.CharField(blank=True, choices=[('VIANDES_VOLAILLES', 'Viandes et volailles fraîches et surgelées'), ('CHARCUTERIE', 'Charcuterie'), ('PRODUITS_DE_LA_MER', "Poissons, produits de la mer et de l'aquaculture"), ('FRUITS_ET_LEGUMES', 'Fruits et légumes frais et surgelés'), ('PRODUITS_LAITIERS', 'BOF (Produits laitiers, beurre et œufs)'), ('BOULANGERIE', 'Boulangerie / Pâtisserie fraîches'), ('BOISSONS', 'Boissons'), ('AUTRES', "Autres produits frais, surgelés et d'épicerie")], max_length=255, null=True, verbose_name='famille de produits'),
        ),
    ]
