# Generated by Django 5.2.14 on 2026-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0268_alter_diagnostic_valeur_boulangerie_aocaop_igp_stg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenimage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canteenimage',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='canteenimage',
            name='alt_text',
            field=models.TextField(blank=True, null=True, verbose_name="texte alternatif (pour les utilisateurs qui ne peuvent pas voir l'image)"),
        ),
    ]
