# Generated by Django 5.2.16 on 2026-08-12 10:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0269_canteenimage_creation_and_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_autres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Valeur totale (HT) autres produits frais, surgelés et d'épicerie"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boissons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) boissons'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boulangerie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) boulangerie / pâtisserie fraîches'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_charcuterie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) charcuterie'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) fruits et légumes frais ou surgelés'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_laitiers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) BOF (Produits laitiers, beurre et œufs)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_autres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Valeur totale (HT) autres produits frais, surgelés et d'épicerie"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boissons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) boissons'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) boulangerie / pâtisserie fraîches'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_charcuterie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) charcuterie'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) fruits et légumes frais ou surgelés'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_laitiers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur totale (HT) BOF (Produits laitiers, beurre et œufs)'),
        ),
    ]
