# Generated by Django 5.2.16 on 2026-08-14 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0272_alter_purchase_caracteristiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='nombre_repas_an',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Nombre de repas par an'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='nombre_repas_an',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Nombre de repas par an'),
        ),
    ]
