# Generated by Django 5.2.16 on 2026-08-17 10:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0273_diagnostic_nombre_repas_an_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_circuit_court',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Circuit court - Valeur annuelle HT'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Origine UE (hors France) - Valeur annuelle HT'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Origine France - Valeur annuelle HT'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Local - Valeur annuelle HT'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_circuit_court',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Circuit court - Valeur annuelle HT'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_europe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Origine UE (hors France) - Valeur annuelle HT'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_france',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Origine France - Valeur annuelle HT'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Local - Valeur annuelle HT'),
        ),
    ]
