# Generated by Django 5.2.16 on 2026-08-17 10:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0274_diagnostic_valeur_france_europe_circuit_court_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_autres_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, AOC / AOP"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_autres_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, IGP"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_autres_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, STG"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boissons_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boissons_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, IGP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boissons_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, STG'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boulangerie_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boulangerie_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, IGP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_boulangerie_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, STG'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_charcuterie_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_charcuterie_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, IGP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_charcuterie_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, STG'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, IGP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, STG'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, AOC / AOP"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, IGP"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, STG"),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_laitiers_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), AOC / AOP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_laitiers_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), IGP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_produits_laitiers_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), STG'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_viandes_volailles_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_viandes_volailles_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, IGP'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='valeur_viandes_volailles_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, STG'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_autres_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, AOC / AOP"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_autres_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, IGP"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_autres_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, STG"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boissons_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boissons_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, IGP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boissons_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, STG'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, IGP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, STG'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_charcuterie_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_charcuterie_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, IGP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_charcuterie_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charcuterie, STG'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, IGP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, STG'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, AOC / AOP"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, IGP"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, STG"),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_laitiers_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), AOC / AOP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_laitiers_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), IGP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_produits_laitiers_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BOF (Produits laitiers, beurre et œufs), STG'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_viandes_volailles_aocaop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, AOC / AOP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_viandes_volailles_igp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, IGP'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='valeur_viandes_volailles_stg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Viandes et volailles fraîches et surgelées, STG'),
        ),
    ]
