# Generated by Django 5.2.17 on 2026-09-16 13:24

import common.utils.siret
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0275_diagnostic_valeur_famille_aocaop_igp_stg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteenimage',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='canteen',
            name='central_producer_siret',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[common.utils.siret.validate_siret], verbose_name='siret de la cuisine centrale'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='city_insee_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='department',
            field=models.CharField(blank=True, choices=[('01', '01 - Ain'), ('02', '02 - Aisne'), ('03', '03 - Allier'), ('04', '04 - Alpes-de-Haute-Provence'), ('05', '05 - Hautes-Alpes'), ('06', '06 - Alpes-Maritimes'), ('07', '07 - Ardèche'), ('08', '08 - Ardennes'), ('09', '09 - Ariège'), ('10', '10 - Aube'), ('11', '11 - Aude'), ('12', '12 - Aveyron'), ('13', '13 - Bouches-du-Rhône'), ('14', '14 - Calvados'), ('15', '15 - Cantal'), ('16', '16 - Charente'), ('17', '17 - Charente-Maritime'), ('18', '18 - Cher'), ('19', '19 - Corrèze'), ('21', "21 - Côte-d'or"), ('22', "22 - Côtes-d'armor"), ('23', '23 - Creuse'), ('24', '24 - Dordogne'), ('25', '25 - Doubs'), ('26', '26 - Drôme'), ('27', '27 - Eure'), ('28', '28 - Eure-et-Loir'), ('29', '29 - Finistère'), ('2A', '2A - Corse-du-Sud'), ('2B', '2B - Haute-Corse'), ('30', '30 - Gard'), ('31', '31 - Haute-Garonne'), ('32', '32 - Gers'), ('33', '33 - Gironde'), ('34', '34 - Hérault'), ('35', '35 - Ille-et-Vilaine'), ('36', '36 - Indre'), ('37', '37 - Indre-et-Loire'), ('38', '38 - Isère'), ('39', '39 - Jura'), ('40', '40 - Landes'), ('41', '41 - Loir-et-Cher'), ('42', '42 - Loire'), ('43', '43 - Haute-Loire'), ('44', '44 - Loire-Atlantique'), ('45', '45 - Loiret'), ('46', '46 - Lot'), ('47', '47 - Lot-et-Garonne'), ('48', '48 - Lozère'), ('49', '49 - Maine-et-Loire'), ('50', '50 - Manche'), ('51', '51 - Marne'), ('52', '52 - Haute-Marne'), ('53', '53 - Mayenne'), ('54', '54 - Meurthe-et-Moselle'), ('55', '55 - Meuse'), ('56', '56 - Morbihan'), ('57', '57 - Moselle'), ('58', '58 - Nièvre'), ('59', '59 - Nord'), ('60', '60 - Oise'), ('61', '61 - Orne'), ('62', '62 - Pas-de-Calais'), ('63', '63 - Puy-de-Dôme'), ('64', '64 - Pyrénées-Atlantiques'), ('65', '65 - Hautes-Pyrénées'), ('66', '66 - Pyrénées-Orientales'), ('67', '67 - Bas-Rhin'), ('68', '68 - Haut-Rhin'), ('69', '69 - Rhône'), ('70', '70 - Haute-Saône'), ('71', '71 - Saône-et-Loire'), ('72', '72 - Sarthe'), ('73', '73 - Savoie'), ('74', '74 - Haute-Savoie'), ('75', '75 - Paris'), ('76', '76 - Seine-Maritime'), ('77', '77 - Seine-et-Marne'), ('78', '78 - Yvelines'), ('79', '79 - Deux-Sèvres'), ('80', '80 - Somme'), ('81', '81 - Tarn'), ('82', '82 - Tarn-et-Garonne'), ('83', '83 - Var'), ('84', '84 - Vaucluse'), ('85', '85 - Vendée'), ('86', '86 - Vienne'), ('87', '87 - Haute-Vienne'), ('88', '88 - Vosges'), ('89', '89 - Yonne'), ('90', '90 - Territoire de Belfort'), ('91', '91 - Essonne'), ('92', '92 - Hauts-de-Seine'), ('93', '93 - Seine-Saint-Denis'), ('94', '94 - Val-de-Marne'), ('95', "95 - Val-d'oise"), ('971', '971 - Guadeloupe'), ('972', '972 - Martinique'), ('973', '973 - Guyane'), ('974', '974 - La Réunion'), ('975', '975 - Saint-Pierre-et-Miquelon'), ('976', '976 - Mayotte'), ('977', '977 - Saint-Barthélemy'), ('978', '978 - Saint-Martin'), ('984', '984 - Terres australes et antarctiques françaises'), ('986', '986 - Wallis-et-Futuna'), ('987', '987 - Polynésie Française'), ('988', '988 - Nouvelle Calédonie'), ('989', '989 - Île de Clipperton')], max_length=3, null=True, verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='department_lib',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nom du département'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='epci',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[common.utils.siret.validate_siren], verbose_name='Code EPCI'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='epci_lib',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nom EPCI'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='import_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Source de l'import de la cantine"),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='line_ministry',
            field=models.CharField(blank=True, choices=[('affaires_etrangeres', 'Affaires étrangères'), ('agriculture', 'Agriculture, Alimentation et Forêts'), ('armee', 'Armées'), ('territoires', 'Cohésion des territoires - Relations avec les collectivités territoriales'), ('culture', 'Culture'), ('economie', 'Économie et finances'), ('jeunesse', 'Éducation et Jeunesse'), ('enseignement_superieur', 'Enseignement supérieur et Recherche'), ('ecologie', 'Environnement'), ('transformation', 'Fonction Publiques'), ('interieur', 'Intérieur et Outre-mer'), ('justice', 'Justice'), ('mer', 'Mer'), ('administration_territoriale', "Préfecture - Administration Territoriale de l'État (ATE)"), ('autorites_independantes', 'Présidence de la république - Autorités indépendantes (AAI, API)'), ('premier_ministre', 'Services du Premier Ministre'), ('sante', 'Santé et Solidarités'), ('sport', 'Sport'), ('travail', 'Travail')], max_length=255, null=True, verbose_name='Ministère de tutelle'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='pat_lib_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='noms PAT'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='pat_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='codes PAT'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='region',
            field=models.CharField(blank=True, choices=[('01', '01 - Guadeloupe'), ('02', '02 - Martinique'), ('03', '03 - Guyane'), ('04', '04 - La Réunion'), ('06', '06 - Mayotte'), ('11', '11 - Île-de-France'), ('24', '24 - Centre-Val de Loire'), ('27', '27 - Bourgogne-Franche-Comté'), ('28', '28 - Normandie'), ('32', '32 - Hauts-de-France'), ('44', '44 - Grand Est'), ('52', '52 - Pays de la Loire'), ('53', '53 - Bretagne'), ('75', '75 - Nouvelle-Aquitaine'), ('76', '76 - Occitanie'), ('84', '84 - Auvergne-Rhône-Alpes'), ('93', "93 - Provence-Alpes-Côte d'Azur"), ('94', '94 - Corse'), ('975', '975 - Saint-Pierre-et-Miquelon'), ('977', '977 - Saint-Barthélemy'), ('978', '978 - Saint-Martin'), ('984', '984 - Terres australes et antarctiques françaises'), ('986', '986 - Wallis-et-Futuna'), ('987', '987 - Polynésie Française'), ('988', '988 - Nouvelle Calédonie'), ('989', '989 - Île de Clipperton')], max_length=3, null=True, verbose_name='région'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='region_lib',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nom de la région'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='siren_unite_legale',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[common.utils.siret.validate_siren], verbose_name="siren de l'unité légale"),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[common.utils.siret.validate_siret]),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='central_producer_siret',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[common.utils.siret.validate_siret], verbose_name='siret de la cuisine centrale'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='city_insee_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='department',
            field=models.CharField(blank=True, choices=[('01', '01 - Ain'), ('02', '02 - Aisne'), ('03', '03 - Allier'), ('04', '04 - Alpes-de-Haute-Provence'), ('05', '05 - Hautes-Alpes'), ('06', '06 - Alpes-Maritimes'), ('07', '07 - Ardèche'), ('08', '08 - Ardennes'), ('09', '09 - Ariège'), ('10', '10 - Aube'), ('11', '11 - Aude'), ('12', '12 - Aveyron'), ('13', '13 - Bouches-du-Rhône'), ('14', '14 - Calvados'), ('15', '15 - Cantal'), ('16', '16 - Charente'), ('17', '17 - Charente-Maritime'), ('18', '18 - Cher'), ('19', '19 - Corrèze'), ('21', "21 - Côte-d'or"), ('22', "22 - Côtes-d'armor"), ('23', '23 - Creuse'), ('24', '24 - Dordogne'), ('25', '25 - Doubs'), ('26', '26 - Drôme'), ('27', '27 - Eure'), ('28', '28 - Eure-et-Loir'), ('29', '29 - Finistère'), ('2A', '2A - Corse-du-Sud'), ('2B', '2B - Haute-Corse'), ('30', '30 - Gard'), ('31', '31 - Haute-Garonne'), ('32', '32 - Gers'), ('33', '33 - Gironde'), ('34', '34 - Hérault'), ('35', '35 - Ille-et-Vilaine'), ('36', '36 - Indre'), ('37', '37 - Indre-et-Loire'), ('38', '38 - Isère'), ('39', '39 - Jura'), ('40', '40 - Landes'), ('41', '41 - Loir-et-Cher'), ('42', '42 - Loire'), ('43', '43 - Haute-Loire'), ('44', '44 - Loire-Atlantique'), ('45', '45 - Loiret'), ('46', '46 - Lot'), ('47', '47 - Lot-et-Garonne'), ('48', '48 - Lozère'), ('49', '49 - Maine-et-Loire'), ('50', '50 - Manche'), ('51', '51 - Marne'), ('52', '52 - Haute-Marne'), ('53', '53 - Mayenne'), ('54', '54 - Meurthe-et-Moselle'), ('55', '55 - Meuse'), ('56', '56 - Morbihan'), ('57', '57 - Moselle'), ('58', '58 - Nièvre'), ('59', '59 - Nord'), ('60', '60 - Oise'), ('61', '61 - Orne'), ('62', '62 - Pas-de-Calais'), ('63', '63 - Puy-de-Dôme'), ('64', '64 - Pyrénées-Atlantiques'), ('65', '65 - Hautes-Pyrénées'), ('66', '66 - Pyrénées-Orientales'), ('67', '67 - Bas-Rhin'), ('68', '68 - Haut-Rhin'), ('69', '69 - Rhône'), ('70', '70 - Haute-Saône'), ('71', '71 - Saône-et-Loire'), ('72', '72 - Sarthe'), ('73', '73 - Savoie'), ('74', '74 - Haute-Savoie'), ('75', '75 - Paris'), ('76', '76 - Seine-Maritime'), ('77', '77 - Seine-et-Marne'), ('78', '78 - Yvelines'), ('79', '79 - Deux-Sèvres'), ('80', '80 - Somme'), ('81', '81 - Tarn'), ('82', '82 - Tarn-et-Garonne'), ('83', '83 - Var'), ('84', '84 - Vaucluse'), ('85', '85 - Vendée'), ('86', '86 - Vienne'), ('87', '87 - Haute-Vienne'), ('88', '88 - Vosges'), ('89', '89 - Yonne'), ('90', '90 - Territoire de Belfort'), ('91', '91 - Essonne'), ('92', '92 - Hauts-de-Seine'), ('93', '93 - Seine-Saint-Denis'), ('94', '94 - Val-de-Marne'), ('95', "95 - Val-d'oise"), ('971', '971 - Guadeloupe'), ('972', '972 - Martinique'), ('973', '973 - Guyane'), ('974', '974 - La Réunion'), ('975', '975 - Saint-Pierre-et-Miquelon'), ('976', '976 - Mayotte'), ('977', '977 - Saint-Barthélemy'), ('978', '978 - Saint-Martin'), ('984', '984 - Terres australes et antarctiques françaises'), ('986', '986 - Wallis-et-Futuna'), ('987', '987 - Polynésie Française'), ('988', '988 - Nouvelle Calédonie'), ('989', '989 - Île de Clipperton')], max_length=3, null=True, verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='department_lib',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nom du département'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='epci',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[common.utils.siret.validate_siren], verbose_name='Code EPCI'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='epci_lib',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nom EPCI'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='import_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Source de l'import de la cantine"),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='line_ministry',
            field=models.CharField(blank=True, choices=[('affaires_etrangeres', 'Affaires étrangères'), ('agriculture', 'Agriculture, Alimentation et Forêts'), ('armee', 'Armées'), ('territoires', 'Cohésion des territoires - Relations avec les collectivités territoriales'), ('culture', 'Culture'), ('economie', 'Économie et finances'), ('jeunesse', 'Éducation et Jeunesse'), ('enseignement_superieur', 'Enseignement supérieur et Recherche'), ('ecologie', 'Environnement'), ('transformation', 'Fonction Publiques'), ('interieur', 'Intérieur et Outre-mer'), ('justice', 'Justice'), ('mer', 'Mer'), ('administration_territoriale', "Préfecture - Administration Territoriale de l'État (ATE)"), ('autorites_independantes', 'Présidence de la république - Autorités indépendantes (AAI, API)'), ('premier_ministre', 'Services du Premier Ministre'), ('sante', 'Santé et Solidarités'), ('sport', 'Sport'), ('travail', 'Travail')], max_length=255, null=True, verbose_name='Ministère de tutelle'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='pat_lib_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='noms PAT'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='pat_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='codes PAT'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='region',
            field=models.CharField(blank=True, choices=[('01', '01 - Guadeloupe'), ('02', '02 - Martinique'), ('03', '03 - Guyane'), ('04', '04 - La Réunion'), ('06', '06 - Mayotte'), ('11', '11 - Île-de-France'), ('24', '24 - Centre-Val de Loire'), ('27', '27 - Bourgogne-Franche-Comté'), ('28', '28 - Normandie'), ('32', '32 - Hauts-de-France'), ('44', '44 - Grand Est'), ('52', '52 - Pays de la Loire'), ('53', '53 - Bretagne'), ('75', '75 - Nouvelle-Aquitaine'), ('76', '76 - Occitanie'), ('84', '84 - Auvergne-Rhône-Alpes'), ('93', "93 - Provence-Alpes-Côte d'Azur"), ('94', '94 - Corse'), ('975', '975 - Saint-Pierre-et-Miquelon'), ('977', '977 - Saint-Barthélemy'), ('978', '978 - Saint-Martin'), ('984', '984 - Terres australes et antarctiques françaises'), ('986', '986 - Wallis-et-Futuna'), ('987', '987 - Polynésie Française'), ('988', '988 - Nouvelle Calédonie'), ('989', '989 - Île de Clipperton')], max_length=3, null=True, verbose_name='région'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='region_lib',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nom de la région'),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='siren_unite_legale',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[common.utils.siret.validate_siren], verbose_name="siren de l'unité légale"),
        ),
        migrations.AlterField(
            model_name='historicalcanteen',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[common.utils.siret.validate_siret]),
        ),
    ]
