# Generated by Django 5.2.17 on 2026-09-28 10:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0276_alter_canteen_textfield_to_charfield_max_255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_autres_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Fermier"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boissons_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, Fermier'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_boulangerie_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Fermier'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_fruits_et_legumes_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, Fermier'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Fermier"),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='valeur_produits_de_la_mer_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Pêche durable"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_autres_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Autres produits frais, surgelés et d'épicerie, Fermier"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boissons_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boissons, Fermier'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_boulangerie_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Boulangerie / Pâtisserie fraîches, Fermier'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_fruits_et_legumes_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fruits et légumes frais et surgelés, Fermier'),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_fermier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Fermier"),
        ),
        migrations.AlterField(
            model_name='historicaldiagnostic',
            name='valeur_produits_de_la_mer_peche_durable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Poissons, produits de la mer et de l'aquaculture, Pêche durable"),
        ),
    ]
