# Generated by Django 5.2.17 on 2026-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0277_alter_diagnostic_complete_not_applicable_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='declaration_donnees_2026',
            field=models.BooleanField(default=False, verbose_name='a télédéclaré ses données de 2026'),
        ),
        migrations.AddField(
            model_name='historicalcanteen',
            name='declaration_donnees_2026',
            field=models.BooleanField(default=False, verbose_name='a télédéclaré ses données de 2026'),
        ),
    ]
