# Generated by Django 5.2.17 on 2026-10-01 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0278_canteen_declaration_donnees_2026_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='definition_local',
            field=models.CharField(blank=True, choices=[('PAT', 'Issu du Projet Alimentaire Territorial (PAT)'), ('COMMUNE', 'Commune et/ou intercommunalité'), ('DEPARTEMENT', 'Département'), ('REGION', 'Région'), ('KM', 'Distance en km')], max_length=255, null=True, verbose_name='définition de local'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='definition_local_km',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='définition de local (distance en km)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='definition_local',
            field=models.CharField(blank=True, choices=[('PAT', 'Issu du Projet Alimentaire Territorial (PAT)'), ('COMMUNE', 'Commune et/ou intercommunalité'), ('DEPARTEMENT', 'Département'), ('REGION', 'Région'), ('KM', 'Distance en km')], max_length=255, null=True, verbose_name='définition de local'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='definition_local_km',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='définition de local (distance en km)'),
        ),
    ]
