# Generated by Django 5.2.17 on 2026-09-30 20:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0278_canteen_declaration_donnees_2026_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_egalim_autres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage autres EGalim (champ calculé)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_externalites_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage externalités/performance (champ calculé)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_produits_de_la_mer_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale produits de la mer', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage produits de la mer EGalim (champ calculé)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_produits_de_la_mer_france',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale produits de la mer', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage produits de la mer origine France (champ calculé)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_siqo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage SIQO (champ calculé)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_viandes_volailles_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale viandes et volailles', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage viandes et volailles EGalim (champ calculé)'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='pourcentage_viandes_volailles_france',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale viandes et volailles', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage viandes et volailles origine France (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_egalim_autres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage autres EGalim (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_externalites_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage externalités/performance (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_produits_de_la_mer_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale produits de la mer', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage produits de la mer EGalim (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_produits_de_la_mer_france',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale produits de la mer', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage produits de la mer origine France (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_siqo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage SIQO (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_viandes_volailles_egalim',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale viandes et volailles', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage viandes et volailles EGalim (champ calculé)'),
        ),
        migrations.AddField(
            model_name='historicaldiagnostic',
            name='pourcentage_viandes_volailles_france',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='par rapport à la valeur totale viandes et volailles', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='pourcentage viandes et volailles origine France (champ calculé)'),
        ),
    ]
