# Generated by Django 5.2.17 on 2026-10-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0278_canteen_declaration_donnees_2026_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
