# Generated by Django 5.2.17 on 2026-10-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_oauth2_provider_application_extra(apps, schema_editor):
    Application = apps.get_model(settings.OAUTH2_PROVIDER_APPLICATION_MODEL)
    Oauth2ProviderApplicationExtra = apps.get_model("data", "Oauth2ProviderApplicationExtra")
    Oauth2ProviderApplicationExtra.objects.bulk_create(
        [
            Oauth2ProviderApplicationExtra(application=application)
            for application in Application.objects.filter(extra__isnull=True)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0280_diagnostic_pourcentage_appro_fields'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2ProviderApplicationExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name="nom de l'entreprise")),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Application Oauth2 (API)')),
            ],
            options={
                'verbose_name': 'Application Oauth2 (API) : informations complémentaires',
                'verbose_name_plural': 'Applications Oauth2 (API) : informations complémentaires',
            },
        ),
        migrations.RunPython(populate_oauth2_provider_application_extra, migrations.RunPython.noop),
    ]
