# Generated by Django 5.0.7 on 2025-07-11 13:34


from django.core.management import call_command
from django.db import migrations


def create_cache_table(apps, schema_editor):
    call_command("createcachetable")

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_cache_table, reverse_code=migrations.RunPython.noop),
    ]
