# Generated by Django 5.1.13 on 2025-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_create_cache_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cache",
            fields=[
                (
                    "cache_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("expires", models.DateTimeField()),
            ],
            options={
                "db_table": "cache",
                "managed": False,
            },
        ),
    ]
