# Generated by Django 5.1.15 on 2026-02-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_create_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'cache',
                'managed': False,
            },
        ),
    ]
