# Generated by Django 5.2.14 on 2026-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(db_index=True, max_length=255)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILURE', 'Échec')], default='SUCCESS', max_length=20)),
                ('output_data', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
