# Generated by Django 5.0.7 on 2024-07-22 09:07

import data.fields
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "modification_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de dernière modification"
                    ),
                ),
                ("title", models.TextField(verbose_name="Titre")),
                ("subtitle", models.TextField(verbose_name="Sous-titre")),
                (
                    "effort",
                    models.CharField(
                        choices=[
                            ("SMALL", "Petit pas"),
                            ("MEDIUM", "Moyen"),
                            ("LARGE", "Grand projet"),
                        ],
                        max_length=255,
                        verbose_name="Niveau d'effort",
                    ),
                ),
                (
                    "waste_origin",
                    data.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PREP", "Préparation"),
                                ("UNSERVED", "Non servi"),
                                ("PLATE", "Retour assiette"),
                            ],
                            max_length=255,
                        ),
                        size=None,
                        verbose_name="Origines du gaspillage",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        default="<h2>Description</h2><h2>Conseils pratiques</h2><ul><li></li></ul>",
                        verbose_name="Description",
                    ),
                ),
                (
                    "lead_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action anti-gaspi",
                "verbose_name_plural": "Actions anti-gaspi",
                "ordering": ["-modification_date"],
            },
        ),
    ]
