# Generated by Django 5.0.7 on 2024-07-22 12:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteaction",
            name="description",
            field=ckeditor.fields.RichTextField(
                default="<h2>Description</h2><h2>Conseils pratiques</h2><ul><li></li></ul>",
                verbose_name="Description",
            ),
        ),
    ]
