# Generated by Django 5.0.7 on 2024-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_rename_waste_origin_wasteaction_waste_origins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteaction",
            name="subtitle",
            field=models.TextField(blank=True, null=True, verbose_name="Sous-titre"),
        ),
    ]
