select
    id,
    creation_date,
    modification_date,
    year,
    status,
    applicant_id,
    declared_data -> 'applicant' ->> 'name' as applicant_name,
    declared_data -> 'applicant' ->> 'email' as applicant_email,
    canteen_id,
    canteen_siret,
    declared_data -> 'canteen' ->> 'name' as canteen_name,
    declared_data -> 'canteen' ->> 'daily_meal_count' as daily_meal_count,
    declared_data -> 'canteen' ->> 'yearly_meal_count' as yearly_meal_count,
    declared_data -> 'canteen' ->> 'economic_model' as economic_model,
    declared_data -> 'canteen' ->> 'city_insee_code' as city_insee_code,
    department,
    region,
    declared_data -> 'canteen' ->> 'management_type' as management_type,
    declared_data -> 'canteen' ->> 'production_type' as production_type,
    declared_data -> 'canteen' ->> 'central_producer_siret' as central_producer_siret,
    declared_data -> 'canteen' ->> 'satellite_canteens_count' as satellite_canteens_count,
    declared_data -> 'satellites' as satellites,
    declared_data -> 'canteen' ->> 'sectors' as sectors,
    declared_data -> 'canteen' ->> 'line_ministry' as line_ministry,
    -- meta fields
    teledeclaration_mode,
    declared_data -> 'teledeclaration' ->> 'central_kitchen_diagnostic_mode' as central_kitchen_diagnostic_mode,
    declared_data -> 'teledeclaration' ->> 'diagnostic_type' as diagnostic_type,
    -- appro
    declared_data -> 'teledeclaration' ->> 'value_total_ht' as value_total_ht,
    declared_data -> 'teledeclaration' ->> 'value_meat_poultry_ht' as value_meat_poultry_ht,
    declared_data -> 'teledeclaration' ->> 'value_fish_ht' as value_fish_ht,
    -- appro : simple fields
    declared_data -> 'teledeclaration' ->> 'value_bio_ht' as value_bio_ht,
    declared_data -> 'teledeclaration' ->> 'value_sustainable_ht' as value_sustainable_ht,
    declared_data -> 'teledeclaration' ->> 'value_externality_performance_ht' as value_externality_performance_ht,
    declared_data -> 'teledeclaration' ->> 'value_egalim_others_ht' as value_egalim_others_ht,
    declared_data -> 'teledeclaration' ->> 'value_meat_poultry_egalim_ht' as value_meat_poultry_egalim_ht,
    declared_data -> 'teledeclaration' ->> 'value_meat_poultry_france_ht' as value_meat_poultry_france_ht,
    declared_data -> 'teledeclaration' ->> 'value_fish_egalim_ht' as value_fish_egalim_ht,
    -- appro : complete fields
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_bio' as value_viandes_volailles_bio,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_bio' as value_produits_de_la_mer_bio,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_bio' as value_fruits_et_legumes_bio,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_bio' as value_charcuterie_bio,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_bio' as value_produits_laitiers_bio,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_bio' as value_boulangerie_bio,
    declared_data -> 'teledeclaration' ->> 'value_boissons_bio' as value_boissons_bio,
    declared_data -> 'teledeclaration' ->> 'value_autres_bio' as value_autres_bio,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_label_rouge' as value_viandes_volailles_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_label_rouge' as value_produits_de_la_mer_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_label_rouge' as value_fruits_et_legumes_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_label_rouge' as value_charcuterie_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_label_rouge' as value_produits_laitiers_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_label_rouge' as value_boulangerie_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_boissons_label_rouge' as value_boissons_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_autres_label_rouge' as value_autres_label_rouge,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_aocaop_igp_stg' as value_viandes_volailles_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_aocaop_igp_stg' as value_produits_de_la_mer_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_aocaop_igp_stg' as value_fruits_et_legumes_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_aocaop_igp_stg' as value_charcuterie_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_aocaop_igp_stg' as value_produits_laitiers_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_aocaop_igp_stg' as value_boulangerie_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_boissons_aocaop_igp_stg' as value_boissons_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_autres_aocaop_igp_stg' as value_autres_aocaop_igp_stg,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_hve' as value_viandes_volailles_hve,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_hve' as value_produits_de_la_mer_hve,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_hve' as value_fruits_et_legumes_hve,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_hve' as value_charcuterie_hve,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_hve' as value_produits_laitiers_hve,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_hve' as value_boulangerie_hve,
    declared_data -> 'teledeclaration' ->> 'value_boissons_hve' as value_boissons_hve,
    declared_data -> 'teledeclaration' ->> 'value_autres_hve' as value_autres_hve,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_peche_durable' as value_viandes_volailles_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_peche_durable' as value_produits_de_la_mer_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_peche_durable' as value_fruits_et_legumes_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_peche_durable' as value_charcuterie_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_peche_durable' as value_produits_laitiers_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_peche_durable' as value_boulangerie_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_boissons_peche_durable' as value_boissons_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_autres_peche_durable' as value_autres_peche_durable,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_rup' as value_viandes_volailles_rup,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_rup' as value_produits_de_la_mer_rup,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_rup' as value_fruits_et_legumes_rup,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_rup' as value_charcuterie_rup,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_rup' as value_produits_laitiers_rup,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_rup' as value_boulangerie_rup,
    declared_data -> 'teledeclaration' ->> 'value_boissons_rup' as value_boissons_rup,
    declared_data -> 'teledeclaration' ->> 'value_autres_rup' as value_autres_rup,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_fermier' as value_viandes_volailles_fermier,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_fermier' as value_produits_de_la_mer_fermier,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_fermier' as value_fruits_et_legumes_fermier,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_fermier' as value_charcuterie_fermier,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_fermier' as value_produits_laitiers_fermier,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_fermier' as value_boulangerie_fermier,
    declared_data -> 'teledeclaration' ->> 'value_boissons_fermier' as value_boissons_fermier,
    declared_data -> 'teledeclaration' ->> 'value_autres_fermier' as value_autres_fermier,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_externalites' as value_viandes_volailles_externalites,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_externalites' as value_produits_de_la_mer_externalites,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_externalites' as value_fruits_et_legumes_externalites,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_externalites' as value_charcuterie_externalites,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_externalites' as value_produits_laitiers_externalites,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_externalites' as value_boulangerie_externalites,
    declared_data -> 'teledeclaration' ->> 'value_boissons_externalites' as value_boissons_externalites,
    declared_data -> 'teledeclaration' ->> 'value_autres_externalites' as value_autres_externalites,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_commerce_equitable' as value_viandes_volailles_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_commerce_equitable' as value_produits_de_la_mer_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_commerce_equitable' as value_fruits_et_legumes_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_commerce_equitable' as value_charcuterie_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_commerce_equitable' as value_produits_laitiers_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_commerce_equitable' as value_boulangerie_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_boissons_commerce_equitable' as value_boissons_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_autres_commerce_equitable' as value_autres_commerce_equitable,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_performance' as value_viandes_volailles_performance,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_performance' as value_produits_de_la_mer_performance,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_performance' as value_fruits_et_legumes_performance,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_performance' as value_charcuterie_performance,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_performance' as value_produits_laitiers_performance,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_performance' as value_boulangerie_performance,
    declared_data -> 'teledeclaration' ->> 'value_boissons_performance' as value_boissons_performance,
    declared_data -> 'teledeclaration' ->> 'value_autres_performance' as value_autres_performance,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_non_egalim' as value_viandes_volailles_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_non_egalim' as value_produits_de_la_mer_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_non_egalim' as value_fruits_et_legumes_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_non_egalim' as value_charcuterie_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_non_egalim' as value_produits_laitiers_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_non_egalim' as value_boulangerie_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_boissons_non_egalim' as value_boissons_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_autres_non_egalim' as value_autres_non_egalim,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_france' as value_viandes_volailles_france,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_france' as value_produits_de_la_mer_france,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_france' as value_fruits_et_legumes_france,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_france' as value_charcuterie_france,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_france' as value_produits_laitiers_france,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_france' as value_boulangerie_france,
    declared_data -> 'teledeclaration' ->> 'value_boissons_france' as value_boissons_france,
    declared_data -> 'teledeclaration' ->> 'value_autres_france' as value_autres_france,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_short_distribution' as value_viandes_volailles_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_short_distribution' as value_produits_de_la_mer_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_short_distribution' as value_fruits_et_legumes_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_short_distribution' as value_charcuterie_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_short_distribution' as value_produits_laitiers_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_short_distribution' as value_boulangerie_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_boissons_short_distribution' as value_boissons_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_autres_short_distribution' as value_autres_short_distribution,
    declared_data -> 'teledeclaration' ->> 'value_viandes_volailles_local' as value_viandes_volailles_local,
    declared_data -> 'teledeclaration' ->> 'value_produits_de_la_mer_local' as value_produits_de_la_mer_local,
    declared_data -> 'teledeclaration' ->> 'value_fruits_et_legumes_local' as value_fruits_et_legumes_local,
    declared_data -> 'teledeclaration' ->> 'value_charcuterie_local' as value_charcuterie_local,
    declared_data -> 'teledeclaration' ->> 'value_produits_laitiers_local' as value_produits_laitiers_local,
    declared_data -> 'teledeclaration' ->> 'value_boulangerie_local' as value_boulangerie_local,
    declared_data -> 'teledeclaration' ->> 'value_boissons_local' as value_boissons_local,
    declared_data -> 'teledeclaration' ->> 'value_autres_local' as value_autres_local,
    -- non appro fields
    declared_data -> 'teledeclaration' ->> 'has_waste_diagnostic' as has_waste_diagnostic,
    declared_data -> 'teledeclaration' ->> 'has_waste_plan' as has_waste_plan,
    declared_data -> 'teledeclaration' ->> 'waste_actions' as waste_actions,
    declared_data -> 'teledeclaration' ->> 'other_waste_action' as other_waste_action,
    declared_data -> 'teledeclaration' ->> 'has_donation_agreement' as has_donation_agreement,
    declared_data -> 'teledeclaration' ->> 'has_waste_measures' as has_waste_measures,
    declared_data -> 'teledeclaration' ->> 'bread_leftovers' as bread_leftovers,
    declared_data -> 'teledeclaration' ->> 'served_leftovers' as served_leftovers,
    declared_data -> 'teledeclaration' ->> 'unserved_leftovers' as unserved_leftovers,
    declared_data -> 'teledeclaration' ->> 'side_leftovers' as side_leftovers,
    declared_data -> 'teledeclaration' ->> 'donation_frequency' as donation_frequency,
    declared_data -> 'teledeclaration' ->> 'donation_quantity' as donation_quantity,
    declared_data -> 'teledeclaration' ->> 'donation_food_type' as donation_food_type,
    declared_data -> 'teledeclaration' ->> 'other_waste_comments' as other_waste_comments,
    declared_data -> 'teledeclaration' ->> 'has_diversification_plan' as has_diversification_plan,
    declared_data -> 'teledeclaration' ->> 'diversification_plan_actions' as diversification_plan_actions,
    declared_data -> 'teledeclaration' ->> 'vegetarian_weekly_recurrence' as vegetarian_weekly_recurrence,
    declared_data -> 'teledeclaration' ->> 'vegetarian_menu_type' as vegetarian_menu_type,
    declared_data -> 'teledeclaration' ->> 'vegetarian_menu_bases' as vegetarian_menu_bases,
    declared_data -> 'teledeclaration' ->> 'cooking_plastic_substituted' as cooking_plastic_substituted,
    declared_data -> 'teledeclaration' ->> 'serving_plastic_substituted' as serving_plastic_substituted,
    declared_data -> 'teledeclaration' ->> 'plastic_bottles_substituted' as plastic_bottles_substituted,
    declared_data -> 'teledeclaration' ->> 'plastic_tableware_substituted' as plastic_tableware_substituted,
    declared_data -> 'teledeclaration' ->> 'communication_supports' as communication_supports,
    declared_data -> 'teledeclaration' ->> 'other_communication_support' as other_communication_support,
    declared_data -> 'teledeclaration' ->> 'communication_support_url' as communication_support_url,
    declared_data -> 'teledeclaration' ->> 'communicates_on_food_plan' as communicates_on_food_plan,
    declared_data -> 'teledeclaration' ->> 'communicates_on_food_quality' as communicates_on_food_quality,
    declared_data -> 'teledeclaration' ->> 'communication_frequency' as communication_frequency,
    declared_data
from data_teledeclaration
left join (
    select distinct city_insee_code, department, region from data_canteen
    where city_insee_code is not null and city_insee_code != '' and department is not null and department != ''
) as geo_data
on city_insee_code = declared_data -> 'canteen' ->> 'city_insee_code'
where {{snippet: filtre TDs actives en 2022}}
order by creation_date desc
