"""Compatibility imports for legacy diagnostic_import view path."""

from backend.imports.diagnostic import (
    DIAGNOSTICS_COMPLETE_SCHEMA_FILE_NAME,
    DIAGNOSTICS_COMPLETE_SCHEMA_FILE_PATH,
    DIAGNOSTICS_COMPLETE_SCHEMA_URL,
    DIAGNOSTICS_SIMPLE_ID_SCHEMA_FILE_NAME,
    DIAGNOSTICS_SIMPLE_ID_SCHEMA_FILE_PATH,
    DIAGNOSTICS_SIMPLE_ID_SCHEMA_URL,
    DIAGNOSTICS_SIMPLE_SIRET_SCHEMA_FILE_NAME,
    DIAGNOSTICS_SIMPLE_SIRET_SCHEMA_FILE_PATH,
    DIAGNOSTICS_SIMPLE_SIRET_SCHEMA_URL,
    DiagnosticsCompleteImportView,
    DiagnosticsImportView,
    DiagnosticsSimpleImportView,
)

__all__ = [
    "DIAGNOSTICS_COMPLETE_SCHEMA_FILE_NAME",
    "DIAGNOSTICS_COMPLETE_SCHEMA_FILE_PATH",
    "DIAGNOSTICS_COMPLETE_SCHEMA_URL",
    "DIAGNOSTICS_SIMPLE_ID_SCHEMA_FILE_NAME",
    "DIAGNOSTICS_SIMPLE_ID_SCHEMA_FILE_PATH",
    "DIAGNOSTICS_SIMPLE_ID_SCHEMA_URL",
    "DIAGNOSTICS_SIMPLE_SIRET_SCHEMA_FILE_NAME",
    "DIAGNOSTICS_SIMPLE_SIRET_SCHEMA_FILE_PATH",
    "DIAGNOSTICS_SIMPLE_SIRET_SCHEMA_URL",
    "DiagnosticsCompleteImportView",
    "DiagnosticsImportView",
    "DiagnosticsSimpleImportView",
]
