import logging
import time
from copy import deepcopy

from django.core.management.base import BaseCommand
from django.db.models import F, Func, Value
from django.db.utils import IntegrityError

from api.serializers import CanteenTeledeclarationSerializer
from data.models import Canteen, Diagnostic
from macantine.utils import (
    set_satellite_common_fields_from_groupe_diagnostic,
    set_satellite_diagnostic_appro_values_from_groupe_diagnostic,
)

logger = logging.getLogger(__name__)


class Command(BaseCommand):
    """
    Goal: Generate diagnostics for satellite canteens that are linked to a groupe (or groupe), based on the diagnostic of their groupe.

    Notes:
    - groupe vs central:
        - before 2025, satellites were linked to CENTRAL & CENTRAL_SERVING
        - in 2025, satellites are now linked to GROUPE (CENTRAL & CENTRAL_SERVING were migrated)
    - appro values distribution:
        - before 2025, we divide by the number of satellites
        - in 2025, we divide by the yearly_meal_count

    Usage:
    - python manage.py teledeclaration_generate_1td1site --year 2024
    - python manage.py teledeclaration_generate_1td1site --year 2024 --apply
    """

    help = "Generate diagnostics of CSAT by splitting diagnostics of their groups"

    def add_arguments(self, parser):
        parser.add_argument(
            "--year",
            dest="year",
            type=int,
            required=True,
            help="Year of the teledeclaration campaign to process",
        )
        parser.add_argument(
            "--apply",
            action="store_true",
            help="To apply changes, otherwise just show what would be done (dry run).",
            default=False,
        )

    def handle(self, *args, **options):  # noqa: C901
        year = options["year"]
        apply = options["apply"]
        start_time = time.time()

        logger.info(
            f"Starting task: generate diagnostics for satellite canteens using group's diagnostics, campaign {year}"
        )
        if not apply:
            logger.info("Dry run mode, no changes will be applied.")

        # Step 1: cleanup
        logger.info("Step 1: Cleanup existing diagnostics previously generated for this year")
        cleanup_before_task(year, apply=apply)

        # Step 2: queryset
        logger.info("Step 2: Fetch all groupe diagnostics teledeclared for the given year")
        diagnostic_qs = (
            Diagnostic.objects.teledeclared_for_year(year=year)
            .annotate(canteen_snapshot_production_type=F("canteen_snapshot__production_type"))
            .with_satellites_snapshot_stats()
            .filter(
                canteen_snapshot_production_type__in=[
                    Canteen.ProductionType.CENTRAL,
                    Canteen.ProductionType.CENTRAL_SERVING,
                    Canteen.ProductionType.GROUPE,
                ]
            )
        )
        logger.info(f"Found {diagnostic_qs.count()} diagnostics teledeclared of groupes to process")

        # Step 3: loop & create diagnostics for satellites
        logger.info(
            "Step 3: Loop on the diagnostics of the groupes, and generate diagnostics teledeclared for their satellites"
        )
        for index, diagnostic in enumerate(diagnostic_qs):
            process_groupe_diagnostic_teledeclared(diagnostic, apply=apply)
            if index % 100 == 0:
                logger.info(
                    f"Processed {index} / {diagnostic_qs.count()} groupe diagnostics teledeclared for the year {year}"
                )

        # Done!
        diagnostic_teledeclared_generated_qs = Diagnostic.all_objects.filter(
            generated_from_groupe_diagnostic=True, year=year
        )
        diagnostic_teledeclared_archived_qs = Diagnostic.objects.filter(
            year=year, invalid_reason_list__contains=[Diagnostic.InvalidReason.DOUBLON_1TD1SITE]
        )
        logger.info(
            f"Task completed. Generated {diagnostic_teledeclared_generated_qs.count()} diagnostics for {year} in {time.time() - start_time:.2f} seconds"
        )
        logger.info(
            f"Archived {diagnostic_teledeclared_archived_qs.count()} diagnostics of satellites that were overridden by their groupe's diagnostic for {year}"
        )


def cleanup_before_task(year, apply=False):
    # delete previously generated diagnostics
    diagnostic_csat_generated_existing_qs = Diagnostic.all_objects.filter(
        generated_from_groupe_diagnostic=True, year=year
    )
    logger.info(
        f"Found {diagnostic_csat_generated_existing_qs.count()} diagnostics to delete (already generated by the script for the year {year})"
    )
    if apply:
        diagnostic_csat_generated_existing_qs.delete()
        logger.info("They have been deleted")

    # unarchive diagnostics of satellites that were archived
    diagnostic_csat_to_unarchive_qs = Diagnostic.objects.filter(
        year=year, invalid_reason_list__contains=[Diagnostic.InvalidReason.DOUBLON_1TD1SITE]
    )
    logger.info(
        f"Found {diagnostic_csat_to_unarchive_qs.count()} diagnostics to unarchive (overridden by groupe for the year {year})"
    )
    if apply:
        diagnostic_csat_to_unarchive_qs.update(
            invalid_reason_list=Func(
                F("invalid_reason_list"),
                Value(Diagnostic.InvalidReason.DOUBLON_1TD1SITE),
                function="array_remove",
            )
        )
        logger.info("They have been unarchived")


def process_groupe_diagnostic_teledeclared(diagnostic, apply=False):
    """
    before 2025
    - central & central_serving (very similar to groups)
    - except that each satellite will have the same appro values
    - no distinction between central and central serving (following macantine/management/commands/canteen_migrate_central_to_groupe.py)

    2025
    - each satellite will have its own appro values based on its yearly_meal_count
    """
    # for each satellite, create a diagnostic (and archive any existing diagnostic)
    if diagnostic.satellites_snapshot_count_annotated:
        for satellite_dict in diagnostic.satellites_snapshot:
            create_diagnostic_teledeclared_for_satellite(diagnostic, satellite_dict, apply=apply)
            archive_existing_diagnostic_teledeclared_satellite(diagnostic, satellite_dict, apply=apply)
        update_generated_diagnostic_teledeclared_creation_date(diagnostic, apply=apply)


def create_diagnostic_teledeclared_for_satellite(diagnostic, satellite_dict, apply=False):
    """
    Create a new diagnostic for a satellite canteen, based on the groupe's diagnostic.
    """
    # keep most of the fields identical with the groupe's diagnostic
    diagnostic_satellite = deepcopy(diagnostic)

    # change the id (to create a new object)
    diagnostic_satellite.pk = None

    # change the canteen FK & canteen_snapshot
    diagnostic_satellite.canteen = None
    # we fetch the canteen satellite as of the creation date of the diagnostic, for accurate snapshot
    try:
        diagnostic_satellite.canteen = Canteen.history.as_of(diagnostic.teledeclaration_date).get(
            pk=satellite_dict["id"]
        )
    except Exception:
        try:
            diagnostic_satellite.canteen = Canteen.all_objects.get(pk=satellite_dict["id"])
        except Canteen.DoesNotExist:
            logger.warning(
                f"Task warning: The canteen {satellite_dict['id']} does not exist, thus we use the satellites_snapshot dict"
            )
    if diagnostic_satellite.canteen:
        diagnostic_satellite.canteen_snapshot = CanteenTeledeclarationSerializer(diagnostic_satellite.canteen).data
    else:
        diagnostic_satellite.canteen_snapshot = satellite_dict

    # override some canteen fields (from groupe)
    updated_common_fields = set_satellite_common_fields_from_groupe_diagnostic(diagnostic, satellite_dict)
    for field in updated_common_fields.keys():
        diagnostic_satellite.canteen_snapshot[field] = updated_common_fields[field]

    # update diagnostic appro fields (from groupe)
    updated_diagnostic_appro_fields = set_satellite_diagnostic_appro_values_from_groupe_diagnostic(
        diagnostic, satellite_dict
    )
    for field in updated_diagnostic_appro_fields.keys():
        setattr(diagnostic_satellite, field, updated_diagnostic_appro_fields[field])

    # change some last fields
    # diagnostic_satellite.creation_date = diagnostic.teledeclaration_date  # won't work. see update_generated_diagnostic_teledeclared_creation_date
    diagnostic_satellite.teledeclaration_mode = Diagnostic.TeledeclarationMode.SITE
    diagnostic_satellite.satellites_snapshot = None
    diagnostic_satellite.generated_from_groupe_diagnostic = True

    if apply:
        try:
            diagnostic_satellite.save()
        except IntegrityError:
            logger.error(
                f"Task error: Cannot save generated diagnostic as it would create a duplicate. Diagnostic: {diagnostic.id} / Canteen: {satellite_dict['id']}"
            )


def archive_existing_diagnostic_teledeclared_satellite(diagnostic, satellite_dict, apply=False):
    """
    Some satellite canteens may already have a submitted diagnostic for the given year.
    How come? If they had teledeclared individually before being linked to the groupe.
    We need to archive these diagnostics, as they are now overridden by the one generated from their groupe's diagnostic.
    """
    diagnostic_qs = Diagnostic.objects.teledeclared().filter(canteen__id=satellite_dict["id"], year=diagnostic.year)
    if diagnostic_qs.count() == 0:
        return
    elif diagnostic_qs.count() > 1:
        logger.warning(
            f"Task warning: Multiple diagnostics found for Canteen: {satellite_dict['id']} / Year: {diagnostic.year}. Only the first one will be archived."
        )
    else:  # diagnostic_qs.count() == 1
        if apply:
            diagnostic_qs.update(
                invalid_reason_list=Func(
                    F("invalid_reason_list"),
                    Value(Diagnostic.InvalidReason.DOUBLON_1TD1SITE),
                    function="array_append",
                )
            )


def update_generated_diagnostic_teledeclared_creation_date(diagnostic, apply=False):
    """
    To keep the creation_date of the diagnostic of the satellite aligned with the one of the groupe, we update it with the teledeclaration_date of the groupe's diagnostic.
    This way, if the groupe's diagnostic is created before the satellite teledeclares, the diagnostic of the satellite will have an older creation_date than its teledeclaration_date, which is coherent.
    """
    if apply:
        diagnostic_qs = Diagnostic.all_objects.filter(
            generated_from_groupe_diagnostic=True,
            year=diagnostic.year,
            teledeclaration_id=diagnostic.teledeclaration_id,
        )
        diagnostic_qs.update(creation_date=diagnostic.teledeclaration_date)
