import logging
import time
from copy import deepcopy

from django.core.management.base import BaseCommand
from django.db.utils import IntegrityError
from django.db.models import F, Func, IntegerField, Value

from api.serializers import CanteenTeledeclarationSerializer
from data.models import Canteen, Diagnostic
from macantine.utils import divide_appro_values

logger = logging.getLogger(__name__)


class Command(BaseCommand):
    """
    Goal: Generate diagnostics for satellite canteens that are linked to a groupe (or groupe), based on the diagnostic of their groupe.

    Notes:
    - groupe vs central:
        - before 2025, satellites were linked to CENTRAL & CENTRAL_SERVING
        - in 2025, CENTRAL & CENTRAL_SERVING were migrated to GROUPE
    - appro values distribution:
        - in 2024 (and before), we divide by the number of satellites
        - in 2025, we divide by the yearly_meal_count

    Usage:
    - python manage.py teledeclaration_generate_1td1site --year 2024
    - python manage.py teledeclaration_generate_1td1site --year 2024 --apply
    """

    help = "Generate diagnostics of CSAT by splitting diagnostics of their groups"

    def add_arguments(self, parser):
        parser.add_argument(
            "--year",
            dest="year",
            type=int,
            required=True,
            help="Year of the teledeclaration campaign to process",
        )
        parser.add_argument(
            "--apply",
            action="store_true",
            help="To apply changes, otherwise just show what would be done (dry run).",
            default=False,
        )

    def handle(self, *args, **options):  # noqa: C901
        year = options["year"]
        apply = options["apply"]
        start_time = time.time()

        logger.info(
            f"Starting task: generate diagnostics for satellite canteens using group's diagnostics, campaign {year}"
        )
        if not apply:
            logger.info("Dry run mode, no changes will be applied.")

        # Step 1: cleanup
        logger.info("Step 1: Cleanup existing diagnostics previously generated for this year")
        cleanup_before_task(year, apply=apply)

        # Step 2: queryset
        logger.info("Step 2: Fetch all groupe diagnostics teledeclared for the given year")
        diagnostic_qs = (
            Diagnostic.objects.teledeclared_for_year(year=year)
            .annotate(canteen_snapshot_production_type=F("canteen_snapshot__production_type"))
            .annotate(
                satellites_count=Func(
                    "satellites_snapshot", function="jsonb_array_length", output_field=IntegerField()
                )
            )
            .filter(
                canteen_snapshot_production_type__in=[
                    Canteen.ProductionType.CENTRAL,
                    Canteen.ProductionType.CENTRAL_SERVING,
                    Canteen.ProductionType.GROUPE,
                ]
            )
        )
        logger.info(f"Found {diagnostic_qs.count()} diagnostics teledeclared of groupes to process")

        # Step 3: loop & create diagnostics for satellites
        logger.info(
            "Step 3: Loop on the diagnostics of the groupes, and generate diagnostics teledeclared for their satellites"
        )
        for index, diagnostic in enumerate(diagnostic_qs):
            process_groupe_diagnostic_teledeclared(diagnostic, apply=apply)
            if index % 100 == 0:
                logger.info(
                    f"Processed {index} / {diagnostic_qs.count()} groupe diagnostics teledeclared for the year {year}"
                )

        # Done!
        diagnostic_teledeclared_generated_qs = Diagnostic.objects.filter(
            generated_from_groupe_diagnostic=True, year=year
        )
        diagnostic_teledeclared_archived_qs = Diagnostic.objects.filter(
            year=year, invalid_reason_list__contains=[Diagnostic.InvalidReason.DOUBLON_1TD1SITE]
        )
        logger.info(
            f"Task completed. Generated {diagnostic_teledeclared_generated_qs.count()} diagnostics for {year} in {time.time() - start_time:.2f} seconds"
        )
        logger.info(
            f"Archived {diagnostic_teledeclared_archived_qs.count()} diagnostics of satellites that were overriden by their groupe's diagnostic for {year}"
        )


def cleanup_before_task(year, apply=False):
    # delete previously generated diagnostics
    diagnostic_csat_generated_existing_qs = Diagnostic.objects.filter(generated_from_groupe_diagnostic=True, year=year)
    logger.info(
        f"Found {diagnostic_csat_generated_existing_qs.count()} diagnostics to delete (already generated by the script for the year {year})"
    )
    if apply:
        diagnostic_csat_generated_existing_qs.delete()
        logger.info("They have been deleted")

    # unarchive diagnostics of satellites that were archived
    diagnostic_csat_to_unarchive_qs = Diagnostic.objects.filter(
        year=year, invalid_reason_list__contains=[Diagnostic.InvalidReason.DOUBLON_1TD1SITE]
    )
    logger.info(
        f"Found {diagnostic_csat_to_unarchive_qs.count()} diagnostics to unarchive (overriden by groupe for the year {year})"
    )
    if apply:
        diagnostic_csat_to_unarchive_qs.update(
            invalid_reason_list=Func(
                F("invalid_reason_list"),
                Value(Diagnostic.InvalidReason.DOUBLON_1TD1SITE),
                function="array_remove",
            )
        )
        logger.info("They have been unarchived")


def process_groupe_diagnostic_teledeclared(diagnostic, apply=False):
    """
    2024 and before
    - central & central_serving (very similar to groups)
    - except that each satellite will have the same appro values
    - no distinction between central and central serving (following macantine/management/commands/canteen_migrate_central_to_groupe.py)

    2025
    - each satellite will have its own appro values based on its yearly_meal_count
    """
    # for each satellite, create a diagnostic (and archive any existing diagnostic)
    if diagnostic.satellites_count:
        for satellite in diagnostic.satellites_snapshot:
            updated_appro_fields = divide_appro_values(diagnostic, satellite)
            create_diagnostic_teledeclared_for_satellite(
                diagnostic, satellite["id"], updated_appro_fields, apply=apply
            )
            archive_existing_diagnostic_teledeclared_satellite(satellite["id"], diagnostic.year, apply=apply)


def create_diagnostic_teledeclared_for_satellite(diagnostic, canteen_id, updated_appro_fields, apply=False):
    """
    Create a new diagnostic for a satellite canteen, based on the groupe's diagnostic.
    """
    # keep most of the fields identical with the groupe's diagnostic
    diagnostic_satellite = deepcopy(diagnostic)

    # change the id (to create a new object)
    diagnostic_satellite.pk = None

    # change the canteen FK
    # we fetch the canteen satellite as of the creation date of the diagnostic, for accurate snapshot
    try:
        canteen_asof_date_extraction = Canteen.history.as_of(diagnostic.teledeclaration_date).get(pk=canteen_id)
        diagnostic_satellite.canteen = canteen_asof_date_extraction
    except Exception:
        try:
            canteen_asof_date_extraction = Canteen.all_objects.get(pk=canteen_id)
            diagnostic_satellite.canteen = canteen_asof_date_extraction
        except Canteen.DoesNotExist:
            # TODO: use satellite snapshot, instead of exiting
            logger.warning(
                f"Task warning: The canteen {canteen_id} does not exist anymore, thus the diagnostic cannot be generated"
            )
            return

    # change the appro fields
    for field in updated_appro_fields.keys():
        setattr(diagnostic_satellite, field, updated_appro_fields[field])

    # change other fields: yearly_meal_count ?

    # change the snapshots
    diagnostic_satellite.canteen_snapshot = CanteenTeledeclarationSerializer(diagnostic_satellite.canteen).data
    diagnostic_satellite.satellites_snapshot = None

    # change some metadata fields
    diagnostic_satellite.generated_from_groupe_diagnostic = True

    if apply:
        try:
            diagnostic_satellite.save()
        except IntegrityError:
            logger.error(
                f"Task error: Cannot save generated diagnostic as it would create a duplicate. Diagnostic: {diagnostic.id} / Canteen: {canteen_id}"
            )


def archive_existing_diagnostic_teledeclared_satellite(canteen_id, year, apply=False):
    """
    Some satellite canteens may already have a submitted diagnostic for the given year.
    How come? If they had teledeclared individually before being linked to the groupe.
    We need to archive these diagnostics, as they are now overriden by the one generated from their groupe's diagnostic.
    """
    diagnostic_qs = Diagnostic.objects.teledeclared().filter(
        canteen__id=canteen_id, year=year, generated_from_groupe_diagnostic=False
    )
    if diagnostic_qs.count() == 0:
        return
    elif diagnostic_qs.count() > 1:
        logger.warning(
            f"Task warning: Multiple diagnostics found for Canteen: {canteen_id} / Year: {year}. Only the first one will be archived."
        )
    else:  # diagnostic_qs.count() == 1
        if apply:
            diagnostic_qs.update(
                invalid_reason_list=Func(
                    F("invalid_reason_list"),
                    Value(Diagnostic.InvalidReason.DOUBLON_1TD1SITE),
                    function="array_append",
                )
            )
