export default Object.freeze({
  LoadingStatus: {
    LOADING: 1,
    SUCCESS: 2,
    ERROR: 3,
    IDLE: 4,
  },
  DefaultDiagnostics: {
    id: null,
    year: null,
    valueBioHt: null,
    valueSustainableHt: null,
    valueTotalHt: null,
    hasWasteDiagnostic: null,
    hasWastePlan: null,
    wasteActions: [],
    hasDonationAgreement: null,
    hasDiversificationPlan: null,
    vegetarianWeeklyRecurrence: null,
    vegetarianMenuType: null,
    vegetarianMenuBases: [],
    cookingPlasticSubstituted: null,
    servingPlasticSubstituted: null,
    plasticBottlesSubstituted: null,
    plasticTablewareSubstituted: null,
    communicationSupports: [],
    communicationSupportUrl: null,
    communicatesOnFoodPlan: null,
  },
  ManagementTypes: [
    {
      text: "Directe",
      value: "direct",
    },
    {
      text: "Concédée",
      value: "conceded",
    },
  ],
  Categories: {
    VIANDES_VOLAILLES: { text: "Viandes, volailles", color: "red darken-4" },
    PRODUITS_DE_LA_MER: { text: "Produits de la mer", color: "pink darken-4" },
    FRUITS_ET_LEGUMES: {
      text: "Fruits, légumes, légumineuses et oléagineux",
      color: "purple darken-4",
    },
    PRODUITS_CEREALIERS: { text: "Produits céréaliers", color: "deep-purple darken-4" },
    ENTREES: { text: "Entrées et plats composés", color: "indigo darken-4" },
    PRODUITS_LAITIERS: { text: "Lait et produits laitiers", color: "blue darken-4" },
    BOISSONS: { text: "Boissons", color: "light-blue darken-4" },
    AIDES: { text: "Aides culinaires et ingrédients divers", color: "cyan darken-4" },
    BEURRE_OEUF_FROMAGE: { text: "Beurre, oeuf, fromage", color: "teal darken-4" },
    PRODUITS_SUCRES: { text: "Produits sucrés", color: "green darken-4" },
    ALIMENTS_INFANTILES: { text: "Aliments infantiles", color: "light-green darken-4" },
    GLACES_SORBETS: { text: "Glaces et sorbets", color: "blue-grey darken-4" },
    AUTRES: { text: "Autres", color: "brown darken-4" },
  },
  Characteristics: {
    BIO: { text: "Bio" },
    CONVERSION_BIO: { text: "En conversion bio" },
    LABEL_ROUGE: { text: "Label rouge" },
    AOCAOP: { text: "AOC / AOP" },
    ICP: { text: "IGP" },
    STG: { text: "STG" },
    HVE: { text: "HVE" },
    PECHE_DURABLE: { text: "Pêche durable" },
    RUP: { text: "RUP" },
    FERMIER: { text: "Fermier" },
    EXTERNALITES: { text: "Externalités environnementales" },
    COMMERCE_EQUITABLE: { text: "Commerce équitable" },
    PERFORMANCE: { text: "Performance environnementale" },
    EQUIVALENTS: { text: "Produits équivalents" },
    FRANCE: { text: "Provenance France" },
    SHORT_DISTRIBUTION: { text: "Circuit-court" },
    LOCAL: { text: "Local" },
  },
})
