---
title: "Bilan statistique de la campagne ma-cantine portant sur l'année 2023 (travail en cours)"
author:
  - "Quentin Loridant"
  - "Valérie Merle"
format:
  html:
    embed-resources: true       
    code-fold: true
    theme:
      - cosmo
    toc: true
    toc-depth: 5
execute:
  warning: false
  cache: false
---

# Introduction

## Contexte

Le bilan statistique annuel de l’application des objectifs d’approvisionnement fixés à la restauration collective donne lieu à un rapport du gouvernement qui est remis au parlement chaque année.
Celui-ci contient une analyse des données de la campagne de télédéclaration. Le premier bilan est disponible pour la [campagne portant sur les données 2022](https://1648047458-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MSCF7Mdc8yfeIjMxMZr%2Fuploads%2F6RxGNr0aJ4BPSzFsDQGs%2FBilan%20statistique%20EGAlim_achats2022.pdf?alt=media&token=).

Dans ce document nous créons et documentons les statistiques nécessaires pour la campagne ayant eu lieu sur le premier semestre 2023 et portant sur les données de l'année 2023.


```{python import}
# | echo: false
import pandas as pd
import numpy as np
import ast
import datetime
from ydata_profiling import ProfileReport
import psycopg2
import plotly.express as px
import matplotlib.pyplot as plt
from matplotlib import dates as mdates
import locale
import utils
```

<!-- Afin de récupérer les données, il vous faut un TOKEN metabase :
`curl -X POST -H "Content-Type: application/json" -d '{"username": <USERNAME>, "password": <PASSWORD>}' https://ma-cantine-metabase.cleverapps.io/api/session` -->

Les données sont extraites de la base de données de ma-cantine. Plusieurs filtres sont appliqués :

1. date : les télédéclarations doivent être comprises dans les dates de campagne: `creation_date ENTRE 13 février au 30 juin 2023`
2. statut : la télédéclaration doit avoir été validée par son éditeur. `status="SUBMITTED"`
3. année 2023 : `year==2023`
4. `teledeclaration.value_total_ht` non vide*
5. Filtrage des TD dont les montants télédacalrés sont aberrants > 


Vous pouvez retrouver l'intégralité du code utilisé sur la page [github de ma-cantine](https://github.com/betagouv/ma-cantine/tree/staging/stats).

```{python Main}
# | echo: false

cache=True

if not cache:
    tds = utils.load_td()
    
    for year in utils.CAMPAGNES.keys():
        # Saving the file 
        tds[year].to_csv(f"data/export_dataset_stats_campagne_{year}.csv", sep=';', index=False)
        
        # Application de la stratégie Je Ne Sais pas
        tds[f"Campagne {year}"] = tds[year].dropna(
            how="any",
            subset=[
                "teledeclaration.value_total_ht",
                "teledeclaration.value_bio_ht",
            ],
        )
        utils.TUNNEL_DATA_ENG[year]['Après application stratégie Je Ne Sais Pas'] = len(tds[f'Campagne {year}'])

        tds[f"strat_max_{year}"] = tds[year].dropna(
            how="any",
            subset=[
            "teledeclaration.value_bio_ht",
            "teledeclaration.value_total_ht",
            "teledeclaration.value_egalim_others_ht",
            "teledeclaration.value_sustainable_ht",
            "teledeclaration.value_externality_performance_ht",
            ],
        )
        tds[f"{year}_strat_hist"] = tds[year].dropna(
            how="all",
            subset=utils.APPRO_SIMPLIFIED,
        )

        # Saving the file stratégie Je Ne Sais Pas
        tds[f"Campagne {year}"].to_csv(f"data/export_dataset_stats_campagne_clean_{year}.csv", sep=';', index=False)

        # Saving the file stratégie Historique
        tds[f"{year}_strat_hist"].to_csv(f"data/export_dataset_stats_campagne_hist_{year}.csv", sep=';', index=False)

        # Saving the file stratégie Max
        tds[f"strat_max_{year}"].to_csv(f"data/export_dataset_stats_campagne_max_{year}.csv", sep=';', index=False)


# Whether we use cache or ot, we re-read the file to have consistency in the dataframe
tds={}
for year in utils.CAMPAGNES.keys():
    tds[year] = pd.read_csv(f"data/export_dataset_stats_campagne_{year}.csv", sep=";")
    tds[f"Campagne {year}"] = pd.read_csv(f"data/export_dataset_stats_campagne_clean_{year}.csv", sep=";")
    tds[f"{year}_strat_hist"] = pd.read_csv(f"data/export_dataset_stats_campagne_hist_{year}.csv", sep=";")
    tds[f"strat_max_{year}"] = pd.read_csv(f"data/export_dataset_stats_campagne_max_{year}.csv", sep=";")


# Définition des populations assidus, entrantes et sortantes
td_pop = {}
td_pop['2023'] = list(set(tds['Campagne 2023']['canteen.id'].values.tolist())) 
td_pop['2022'] = list(set(tds['Campagne 2022']['canteen.id'].values.tolist())) 
# Télédeclarants présents dans les siret 2023 mais non 2022
entrants = list(set([item for item in td_pop['2023'] if item not in td_pop['2022']]))
tds['Campagne 2023'][tds['Campagne 2023']['canteen.id'].isin(entrants)].to_csv('data/entrants.csv', sep=';', index=False)

# Télédeclarants présents dans les siret 2022 mais non 2023
sortants = list(set([item for item in td_pop['2022'] if item not in td_pop['2023']]))
tds['Campagne 2022'][tds['Campagne 2022']['canteen.id'].isin(sortants)].to_csv('data/sortants.csv', sep=';', index=False)

# Télédéclarants présents lors des deux campagnes
restants = [item for item in td_pop['2022'] if item in td_pop['2023']]

tds_commun = {}
for year in ['2022', '2023', 'Campagne 2022', 'Campagne 2023', '2022_strat_hist', '2023_strat_hist']:
    tds_commun[year] = tds[year][tds[year]["canteen.id"].isin(restants)]
    tds_commun[year] = tds_commun[year].drop_duplicates('canteen.id')

if not cache:
    utils.TUNNEL_DATA_ENG['2023']['Après séléction des assidus'] = len(tds_commun['2023'])


# Filtrage des assidus dont les montants déclarés entre les 2 campganes sont trop différents
iso = tds_commun['Campagne 2023'].merge(tds_commun['Campagne 2022'], on='canteen.id', suffixes=('_2023', '_2022'))
iso['evo_montant_achats'] = iso['teledeclaration.value_total_ht_2023'] / iso['teledeclaration.value_total_ht_2022']
iso = iso[iso['evo_montant_achats'] < 2]
iso = iso[iso['evo_montant_achats'] > 0.5]
asssidus_clean = list(iso['canteen.id'])

for year in ['2022', '2023', 'Campagne 2022', 'Campagne 2023', '2022_strat_hist', '2023_strat_hist']:
    tds_commun[year] = tds_commun[year][tds_commun[year]['canteen.id'].isin(asssidus_clean)]
    tds_commun[year].to_csv(f'data/assidus_{year}.csv', sep=';', index=False)

if not cache:
    utils.TUNNEL_DATA_ENG['2023']['Après filtrage des assidus'] = len(tds_commun['2023'])

```


## Qualité des données

Avant d'étudier les chiffres clés de la télédéclaration, nous vous présentons des informations sur la disponibilité des données. Ces informations sont importantes pour saisir au mieux la portée des indicateurs.

### Traitements sur les TD 2023
```{python}
if not cache:
    df = pd.DataFrame(utils.TUNNEL_DATA_ENG['2023'].values(), index=utils.TUNNEL_DATA_ENG['2023'].keys(), columns=['values'])

    with plt.style.context("fivethirtyeight"):
        fig = plt.figure(figsize=(3, 9))

        # y_values = [11, 9, 7, 5, 3, 1]  # Adjust these values for your desired positioning
        y_values = [1, 3, 5, 7, 9, 11, 13]  # Adjust these values for your desired positioning
        
        x1 = 18  # Adjust the starting x1 position
        x2 = 0   # Adjust the starting x2 position
        offset = 1
        for i in range(len(y_values)):
            if i == 0 or i == 2:
                color = "dodgerblue"
            else:
                color = "purple"

            plt.fill_betweenx(y=[y_values[i], y_values[i] - 1], x1=[x1, x1], x2=[x2, x2], color=color)
            plt.fill_betweenx(y=[y_values[i] - 1, y_values[i] - 2], x1=[x1, x1 - offset], x2=[x2, x2 + offset], color=color, alpha=0.5)
            offset = 1 if i !=1 else 6
            x1 += offset  # Adjust the next x1 position
            x2 += - offset  # Adjust the next x2 position

        plt.yticks([y_values[i] - 0.5 for i in range(len(y_values))], df.index[::-1])
        plt.xticks([], [])

        for i, val in enumerate(df["values"][::-1]):
            plt.text(9, y_values[i] - 0.5, val, ha="center", fontsize=16, fontweight="bold", color="white")

        plt.grid(visible=False)
        plt.title("Traitement des télédéclarations", loc="right", fontsize=25, fontweight="bold")
        plt.show()

```


### 📷 Campagne 2022

```{python Vérification du taux de présence de la donnée repas par an}
# | echo: false
# | output: asis

utils.assert_quality(tds)

utils.display_data_coverage(
    tds,
    sub_columns=utils.APPRO_SIMPLIFIED,
    years=["2022"],
)
```

### 📷 Campagne 2023

```{python Vérification du taux de présence de la donnée repas par an}
# | echo: false
# | output: asis

utils.assert_quality(tds)

utils.display_data_coverage(
    tds,
    sub_columns=utils.APPRO_SIMPLIFIED,
    years=["2023"],
)
```

### ⚖️ Comparaison isopérimètre

```{python Vérification du taux de présence de la donnée repas par an}
# | echo: false
# | output: asis

utils.assert_quality(tds)

utils.display_data_coverage(
    tds_commun,
    sub_columns=utils.APPRO_SIMPLIFIED,
    years=["2022", "2023"],
)
```

Observons la distribution des valeurs d'achats totaux et des achats bio. Les valeurs étant très différentes entre les différents acteurs (de 0€ à plusieurs millions d'euros déclarés), nous visualisons le logarithme des achats.

```{python}
# | echo: false

import seaborn as sns

col_achats = [
    "teledeclaration.value_bio_ht",
    "teledeclaration.value_total_ht",
]

year = "2023"
for col in col_achats:
    tds[year][col + "_log"] = np.log10(tds[year][[col]].replace(0, 1))

g = sns.displot(tds[year][["teledeclaration.value_bio_ht_log",
    "teledeclaration.value_total_ht_log"]], kde=True)

# Iterate thorugh each axis
for ax in g.axes.flat:
    ax.set_title('Distribution des valeurs d\'achats en € totales et bio', fontsize='large')
    ax.set_ylabel('Nombre de TD', fontsize='large')
    ax.set_xlabel('Valeurs d\'achats en € (en log)', fontsize='large')
g
```

Nous observons une loi log-normale pour les deux valeurs d'achats (une variable peut être modélisée par une loi log-normale si elle est le résultat de la multiplication d'un grand nombre de petits facteurs indépendants).  

A la vue des ces graphiques, nous prenons une **première hypothèse** : *étant possible de réaliser une modélisation, nous estimons que la qualité globale des données de ces champs est bonne. Il existe cependant une légère sur-déclaration de valeurs très faibles (par exemple, nous pouvons nous interroger sur la déclaration de moins de 100€ d'achats bio).*


## Traitement des valeurs manquantes

Nous avons traité de 2 façons différentes les valeurs manquantes : **stratégie historique** et **stratégie Je Ne Sais Pas**.

Ces deux stratégies se concentrent sur les cinq champs de la télédéclaration simplifiée: 

1. `value_bio_ht`
2. `value_total_ht`
3. `value_egalim_others_ht`
4. `value_externality_performance_ht`
5. `value_sustainable_ht`


### Stratégie Historique

La **"stratégie Historique"** (qui a été appliquée sur le premier bilan) : nous remplaçons les valeurs manquantes par la valeur 0, sauf si les 5 champs d'une même déclaration sont vides, auquel cas nous ne prenons pas en compte la ligne

```{python}
# | output: asis
# | echo : false


valeurs_manquantes = {}
valeurs_manquantes_iso_perim = {}
for year in utils.CAMPAGNES.keys():
    valeurs_manquantes[year] = {}
    valeurs_manquantes_iso_perim[year] = {}
    for col in utils.APPRO_SIMPLIFIED:
        valeurs_manquantes[year][col.replace('teledeclaration.', '')] = tds[f"{year}_strat_hist"][col].isna().sum()    
        valeurs_manquantes_iso_perim[year][col.replace('teledeclaration.', '')] = tds_commun[f"{year}_strat_hist"][col].isna().sum()    


def display_data_coverage(year):
    print(f'Après filtrage des lignes dont les 5 champs sont manquants, nous avons gardé **{len(tds[f"{year}_strat_hist"])}** télédéclarations sur les **{len(tds[year])}** télédéclarations totales.\n Ensuite nous avons remplaçé par 0 les valeurs manquantes : \n')
    utils.display_indicateurs(pd.DataFrame.from_dict(valeurs_manquantes[year], orient="index").rename(columns={0: "Nombre de valeurs manquantes, remplaçées par 0"}))
```

#### 📷 2022

```{python}
# | output: asis
# | echo : false
display_data_coverage('2022')
```

#### 📷 2023
```{python}
# | output: asis
# | echo : false
display_data_coverage('2023')
```

#### ⚖️ Comparaison isopérimètre
```{python}
# | output: asis
# | echo : false
utils.display_indicateurs(pd.DataFrame.from_dict(valeurs_manquantes_iso_perim).rename(columns={'2022': "2022 : Nombre de valeurs manquantes, remplaçées par 0", '2023': '2023 : Nombre de valeurs manquantes, remplaçées par 0'}))
```
### Stratégie 'Je Ne Sais Pas'

La **"stratégie Je Ne Sais Pas"** : afin de minimiser l'impact des valeurs manquantes, nous supprimons toutes les lignes dès que le champ `teledeclaration.value_bio_ht` est vide. 

Dans les autres cas, comme dans la stratégie 'Historique', nous remplaçons les champs vides par 0.

#### 📷 2022
```{python}
# | output: asis
# | echo: false

year = '2022'
print(f'Nous supprimons {len(tds[year]) - len(tds[f"Campagne {year}"])} lignes car le champ `teledeclaration.value_bio_ht` est vide. \n')
```

#### 📷 2023
```{python}
# | output: asis
# | echo: false

year = '2023'
print(f'Nous supprimons {len(tds[year]) - len(tds[f"Campagne {year}"])} lignes car le champ `teledeclaration.value_bio_ht` est vide. \n')
```
#### ⚖️ Comparaison isopérimètre
```{python}
# | output: asis
# | echo: false

indic = {}
for year in utils.CAMPAGNES.keys():
    indic[year] = len(tds_commun[year]) - len(tds_commun[f"Campagne {year}"])

utils.display_indicateurs(pd.DataFrame.from_dict(indic, orient='index').rename(columns={0: 'teledeclaration.value_bio_ht'}).T.rename(columns={'2022': "2022 : Nombre de valeurs manquantes, remplaçées par 0", '2023': '2023 : Nombre de valeurs manquantes, remplaçées par 0'}))
```

### Stratégie Maximale
La stratégie maximale permet d'établir le haut de la fourchette pour le taux d'achats EGALIM.
Pour ce faire,  nous avons gardé uniquement les TD dont tous les champs appros ont été remplis.


# Chiffres clés

## 📷 2022
### Chiffre généraux
```{python Nombre de sites de restauration concernés par la télédéclaration}
# | echo: false
# | output: asis

indic_divers, indic_appro = utils.calcul_indicateur(tds, years=["Campagne 2022", "2022_strat_hist", "Campagne 2023", "2023_strat_hist", "strat_max_2023"])

indic_divers = indic_divers.rename(columns={'Campagne 2022': 'Campagne 2022 - Stratégie "Je Ne Sais Pas"', '2022_strat_hist': 'Campagne 2022 - Stratégie "Historique"', 'Campagne 2023': 'Campagne 2023 - Stratégie "Je Ne Sais Pas"', '2023_strat_hist': 'Campagne 2023 - Stratégie "Historique"', 'strat_max_2023': 'Campagne 2023 - Stratégie Maximale'})

utils.display_indicateurs(indic_divers[['Campagne 2022 - Stratégie "Je Ne Sais Pas"', 'Campagne 2022 - Stratégie "Historique"']])
```

### Chiffres appro
```{python Nombre de sites de restauration concernés par la télédéclaration}
# | echo: false
# | output: asis
indic_appro = indic_appro.rename(columns={'Campagne 2022': 'Campagne 2022 - Stratégie "Je Ne Sais Pas"', '2022_strat_hist': 'Campagne 2022 - Stratégie "Historique"', 'Campagne 2023': 'Campagne 2023 - Stratégie "Je Ne Sais Pas"', '2023_strat_hist': 'Campagne 2023 - Stratégie "Historique"', 'strat_max_2023': 'Campagne 2023 - Stratégie Maximale'})
utils.display_indicateurs(indic_appro[['Campagne 2022 - Stratégie "Je Ne Sais Pas"', 'Campagne 2022 - Stratégie "Historique"']])
```

## 📷 2023
### Chiffre généraux
```{python Nombre de sites de restauration concernés par la télédéclaration}
# | echo: false
# | output: asis

utils.display_indicateurs(indic_divers[['Campagne 2023 - Stratégie "Je Ne Sais Pas"', 'Campagne 2023 - Stratégie "Historique"', "Campagne 2023 - Stratégie Maximale"]])
```

### Chiffres appro
```{python Nombre de sites de restauration concernés par la télédéclaration}
# | echo: false
# | output: asis

utils.display_indicateurs(indic_appro[['Campagne 2023 - Stratégie "Je Ne Sais Pas"', 'Campagne 2023 - Stratégie "Historique"', "Campagne 2023 - Stratégie Maximale"]])
```

## ⚖️ Comparaison isopérimètre

### Chiffres généraux

```{python}
# | echo: false
# | output: asis


indic_divers, indic_appro = utils.calcul_indicateur(tds_commun, years=["Campagne 2022", "Campagne 2023"])

# Table view
utils.display_indicateurs(indic_divers)

# Graph view
df_indic_divers = pd.DataFrame(indic_divers)
df_indic_appro = pd.DataFrame(indic_appro)

# Isolate the values with numbers
divers_colonnes_nombre = ['Nombre de cantines centrales',  'Nombre de cantines sur place (sites et satellites)', 'Nombre de Télédéclarations']

utils.display_stacked_bars(df_indic_divers.T[divers_colonnes_nombre].T, title='Comparaison des profils',  fmt=utils.nombre_formatter)

# Isolate the values with ratios
divers_colonnes_ratios = ['Taux de TD détaillées']

utils.display_stacked_bars(df_indic_divers.T[divers_colonnes_ratios].T, title='Comparaison des profils', fmt=utils.taux_formatter)
```

### Chiffres appro
```{python}
# | echo: false
# | output: asis

# Isolate the values with numbers
appro_colonnes_montants = ['Montant d\'achat alimentaires bio', 'Montant d\'achat alimentaires EGALIM (bio inclus)', 'Montant d\'achat alimentaires total', "Montant des achats alimentaires cuisines centrales", "Montant des achats alimentaires cantines satellites"]
utils.display_indicateurs(indic_appro)
utils.display_stacked_bars(df_indic_appro.T[appro_colonnes_montants].T, title='Comparaison des montants alimentaires dépensés',  fmt=utils.montant_formatter)

# Isolate the values with ratios
appro_colonnes_taux = ['Taux global des achats en bio',  'Taux global des achats EGALIM (bio inclus)']
utils.display_stacked_bars(df_indic_appro.T[appro_colonnes_taux].T, title='Comparaison des ratios sur les montants',  fmt=utils.taux_formatter)
```

::: {.callout-note}
Pour la suite de l'étude, nous utiliserons uniquement la stratégie "**Je Ne Sais Pas**"" afin de minimiser les hypothèses que nous prenons sur les données.
:::

# Chiffres par famille de produits
::: {.callout-warning}
Pour le moment, ces chiffres ne décrivent que les télédéclarations de type simplifiées. L'ajout de télédéclaration complètes est en cours. A priori, les ratio devraient cependant rester sembables.
:::

::: {.callout-note}
:::
## 📷 2023

```{python Nombre de sites de restauration concernés par la télédéclaration}
# | echo: false
# | output: asis
col_order = [
    "Nombre de TD prises en compte",
    "Nombre de TD ayant déclaré pour la famille Viande/Volaille 🥩",
    "Nombre de TD ayant déclaré la valeur 0€ pour la famille Viande/Volaille 🥩",
    "Montant des achats alimentaires totaux pour la famille Viande/Volaille 🥩",
    "Taux d'achat alimentaires de la famille Viande/Volaille 🥩",
    "Montant d'achat alimentaires Viande/Volaille 🥩",
    "Taux d'achat alimentaires Egalim au sein de la famille Viande/Volaille 🥩",
    "Montant d'achat alimentaires Egalim Viande/Volaille 🥩",
    "Taux d'achat alimentaires origine France 🇫🇷 au sein de la famille Viande/Volaille 🥩",
    "Montant d'achat alimentaires origine France 🇫🇷 Viande/Volaille 🥩",
    "Nombre de TD ayant déclaré pour la famille Poissons/Produits de la mer 🐟",
    "Nombre de TD ayant déclaré la valeur 0€ pour la famille Poissons/Produits de la mer 🐟",
    "Montant des achats alimentaires totaux pour la famille Poissons/Produits de la mer 🐟",
    "Taux d'achat alimentaires de la famille Poissons/Produits de la mer 🐟",
    "Taux d'achat alimentaires Egalim au sein de la famille Poissons/Produits de la mer 🐟",
    "Montant d'achat alimentaires Poissons/Produits de la mer 🐟",
    "Montant d'achat alimentaires Egalim Poissons/Produits de la mer 🐟"
]

indic_famille = utils.calcul_indicateur_famille(tds, years=["Campagne 2023"])
utils.display_indicateurs(indic_famille['Campagne 2023'][col_order])
indic_famille['Campagne 2023'][col_order].to_excel('data/Photo-2023-familles.xlsx')
```

## Comparaison isopérimetrique

```{python Nombre de sites de restauration concernés par la télédéclaration}
# | echo: false
# | output: asis
indic_famille = utils.calcul_indicateur_famille(tds_commun, years=["Campagne 2022", "Campagne 2023"])
indic_famille = utils.ajout_col_comparaison(indic_famille)
utils.display_indicateurs(indic_famille)
indic_famille['Campagne 2023'].to_excel('data/isoperimetre-familles.xlsx')

```

# Répartition des télédéclarants par taille de cantines
## 📷 2023
```{python}

def categorisation_taille(x):
    if x <= 200:
        return 'Inférieur ou égal à 200'
    elif 200 < x <= 700:
        return 'De 200 à 700'
    elif 700 < x <= 1500:
        return 'De 700 à 1500'
    elif x > 1500:
        return 'Supérieur à 1500'
    else: 
        return 'Taille inconnue'

year = 'Campagne 2023'
df_taille = tds[year].copy()[['canteen.id', 'canteen.daily_meal_count']]
df_taille = df_taille.sort_values('canteen.daily_meal_count')
df_taille['Taille'] = df_taille['canteen.daily_meal_count'].apply(lambda x: categorisation_taille(x))
ax = sns.histplot(df_taille['Taille'])
plt.xticks(rotation=60)
ax.patches[-1].set_facecolor('salmon')   
ax.set_ylabel('Nombre de télédéclarations',)
ax.set_title('Distribution des télédéclarants en fonction de la taille des cantines \n(basé sur le nombre de repas servis par jour)')
   
df_taille = df_taille.groupby('Taille').count()[['canteen.id']].rename(columns={'canteen.id': 'Nombre'})
taille_totale = len(tds[year])
df_taille['Pourcentage'] = df_taille.apply(lambda x: utils.taux_formatter(x['Nombre']/taille_totale), axis=1)
```

```{python Coût denrées}
# | echo: false
# | output: asis

# Cout denrées - Données Aberrantes
df = tds['Campagne 2023'].copy()
errors = df[(df['teledeclaration.cout_denrees'] > 10) | (((df['teledeclaration.cout_denrees'] > 0) & (df['teledeclaration.cout_denrees'] < 1.5)))]
errors = errors.sort_values('teledeclaration.cout_denrees', ascending=False)
errors.to_csv('data/cout_denrees_errors.csv', sep=';', index=False)
errors.to_html()
```

{{< include _secteurs.qmd >}}
{{< include _populations.qmd >}}
{{< include _geo.qmd >}}


# Evolution des télédéclaration lors de la campagne 2023
```{python}
df = tds['Campagne 2023']
def categorize_taux_bio(row):
    taux = 100 * row['teledeclaration.value_bio_ht'] / row['teledeclaration.value_total_ht']
    return taux

def categorize_taux_egalim(row):
    taux = 100 * (row["teledeclaration.value_egalim_others_ht"]
            + row["teledeclaration.value_externality_performance_ht"]
            + row["teledeclaration.value_bio_ht"]
            + row["teledeclaration.value_sustainable_ht"]) / row['teledeclaration.value_total_ht']
    return taux
df['Distribution des taux Bio'] = df.apply(categorize_taux_bio , axis=1)
df['Distribution des taux Egalim'] = df.apply(categorize_taux_egalim , axis=1)


g = sns.displot(df, x='Distribution des taux Bio', bins=20)
for i, ax in enumerate(g.axes[:, 0]):
    ax.set_ylabel('Nombre de télédéclarations',)
    ax.axvline(x = 20,      # Line on x = 2
           ymin = 0, # Bottom of the plot
           ymax = 0.8,
           color='green',
           linestyle = "dashed",
           lw=4) # Top of the plot
    ax.text(25,1300,'Objectif : 20%', color='green')
g = sns.displot(df, x='Distribution des taux Egalim', bins=20)
for i, ax in enumerate(g.axes[:, 0]):
    ax.set_ylabel('Nombre de télédéclarations',)
    ax.axvline(x = 50,      # Line on x = 2
        ymin = 0, # Bottom of the plot
        ymax = 0.8,
        color='purple',
        linestyle = "dashed", lw=4) # Top of the plot
    ax.text(55,150,'Objectif : 50%', color='purple')
```

## Nombre de télédéclarations ayant rempli les objectifs bio et Egalim

```{python}
# | echo: false
# | output: asis
df = tds['Campagne 2023'].copy()
df = df[df['Distribution des taux Bio'] >= 20]
print(f'{len(df)} télédéclarants remplissent les objectifs Bio\n')
df = tds['Campagne 2023'].copy()
df = df[df['Distribution des taux Egalim'] >= 50]
print(f'{len(df)} télédéclarants remplissent les objectifs Egalim\n')
df = tds['Campagne 2023'].copy()
df = df[df['Distribution des taux Bio'] >= 20]
df = df[df['Distribution des taux Egalim'] >= 50]
print(f'{len(df)} télédéclarants remplissent les objectifs Bio et Egalim')
```