from rest_framework import serializers
from data.models import VegetarianExpe


class VegetarianExpeSerializer(serializers.ModelSerializer):
    class Meta:
        model = VegetarianExpe
        fields = (
            "id",
            "has_daily_vegetarian_offer",
            "daily_vegetarian_offer_start_date",
            "experimentation_start_date",
            "vegetarian_menu_percentage_t0",
            "eggs_composition_t0",
            "cheese_composition_t0",
            "soy_composition_home_made_t0",
            "soy_composition_ready_t0",
            "soyless_composition_home_made_t0",
            "soyless_composition_ready_t0",
            "cereal_legume_composition_t0",
            "waste_evolution_t0",
            "waste_evolution_percentage_t0",
            "waste_vegetarian_not_served_t0",
            "waste_vegetarian_components_t0",
            "waste_non_vegetarian_not_served_t0",
            "waste_non_vegetarian_components_t0",
            "attendance_evolution_t0",
            "attendance_evolution_percentage_t0",
            "vegetarian_cost_t0",
            "non_vegetarian_cost_t0",
            "cost_evolution_t0",
            "cost_evolution_percentage_t0",
            "satisfaction_guests_t0",
            "satisfaction_guests_reasons_t0",
            "satisfaction_staff_t0",
            "satisfaction_staff_reasons_t0",
            "has_used_recipee_documents_t0",
            "training_t0",
            "vegetarian_menu_percentage_t1",
            "eggs_composition_t1",
            "cheese_composition_t1",
            "soy_composition_home_made_t1",
            "soy_composition_ready_t1",
            "soyless_composition_home_made_t1",
            "soyless_composition_ready_t1",
            "cereal_legume_composition_t1",
            "waste_evolution_t1",
            "waste_evolution_percentage_t1",
            "waste_vegetarian_not_served_t1",
            "waste_vegetarian_components_t1",
            "waste_non_vegetarian_not_served_t1",
            "waste_non_vegetarian_components_t1",
            "attendance_evolution_t1",
            "attendance_evolution_percentage_t1",
            "vegetarian_cost_t1",
            "non_vegetarian_cost_t1",
            "cost_evolution_t1",
            "cost_evolution_percentage_t1",
            "satisfaction_guests_t1",
            "satisfaction_guests_reasons_t1",
            "satisfaction_staff_t1",
            "satisfaction_staff_reasons_t1",
            "has_used_recipee_documents_t1",
            "training_t1",
        )
        read_only_fields = ("id",)
