from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from api.views import (  # ImportCompleteCentralKitchenView,; ImportCompleteDiagnosticsView,; ImportSimpleCentralKitchenView,; ImportSimpleDiagnosticsView,
    ActionableCanteenRetrieveView,
    ActionableCanteensListView,
    AddManagerView,
    BlogPostsView,
    BlogPostView,
    CanteenGroupeSatellitesListView,
    CanteenGroupeSatelliteLinkView,
    CanteenGroupeSatelliteUnlinkView,
    CanteenMinistriesView,
    CanteenPurchasesPercentageSummaryView,
    CanteenPurchasesSummaryView,
    CanteensImportView,
    CanteenStatisticsView,
    CanteenStatusBySirenView,
    CanteenStatusBySiretView,
    CanteenWasteMeasurementsView,
    CanteenWasteMeasurementView,
    ChangePasswordView,
    ClaimCanteenView,
    CommunityEventsView,
    DiagnosticCreateView,
    DiagnosticsFromPurchasesView,
    DiagnosticsSimpleImportView,
    DiagnosticsToTeledeclareListView,
    DiagnosticTeledeclarationCancelView,
    DiagnosticTeledeclarationCreateView,
    DiagnosticTeledeclarationPdfView,
    DiagnosticUpdateView,
    EmailDiagnosticImportFileView,
    InitialDataView,
    InquiryView,
    LoggedUserView,
    MessageCreateView,
    PartnersView,
    PartnerTypeListView,
    PartnerView,
    PublicCanteenPreviewView,
    PublishedCanteenSingleView,
    PublishedCanteensView,
    PurchaseListCreateView,
    UserCanteenListExportView,
    PurchaseListExportView,
    PurchaseOptionsView,
    PurchaseRetrieveUpdateDestroyView,
    PurchasesDeleteView,
    PurchasesImportView,
    PurchasesRestoreView,
    RemoveManagerView,
    ReservationExpeView,
    ResourceActionView,
    RetrieveUpdateUserCanteenView,
    ReviewView,
    SectorListView,
    SendCanteenNotFoundEmail,
    SubscribeNewsletter,
    TeamJoinRequestView,
    TeledeclarationCampaignDatesListView,
    TeledeclarationCampaignDatesRetrieveView,
    TerritoryCanteensListView,
    UndoClaimCanteenView,
    UpdateUserView,
    UserCanteenActions,
    UserCanteenPreviews,
    UserCanteenSummaries,
    UserCanteensView,
    UserInfoView,
    UsernameSuggestionView,
    VegetarianExpeView,
    VideoTutorialListView,
    WasteActionsView,
    WasteActionView,
)

urlpatterns = {
    path("loggedUser/", LoggedUserView.as_view(), name="logged_user"),
    path("userInfo/", UserInfoView.as_view(), name="user_info"),
    path("user/<int:pk>", UpdateUserView.as_view(), name="update_user"),
    path("publishedCanteens/", PublishedCanteensView.as_view(), name="published_canteens"),
    path(
        "publicCanteenPreviews/<int:pk>",
        PublicCanteenPreviewView.as_view(),
        name="single_public_canteen_preview",
    ),
    path(
        "publishedCanteens/<int:pk>",
        PublishedCanteenSingleView.as_view(),
        name="single_published_canteen",
    ),
    path("canteenActions/<int:year>", UserCanteenActions.as_view(), name="user_canteens_actions"),
    path("canteenPreviews/", UserCanteenPreviews.as_view(), name="user_canteen_previews"),
    path("canteenSummaries/", UserCanteenSummaries.as_view(), name="user_canteens_summaries"),
    path("canteens/", UserCanteensView.as_view(), name="user_canteens"),
    path(
        "export-cantines.xlsx",  # breaking from URL conventions for nicer filename
        UserCanteenListExportView.as_view(),
        name="user_canteen_list_export",
    ),
    path("canteens/<int:pk>", RetrieveUpdateUserCanteenView.as_view(), name="single_canteen"),
    path(
        "canteens/<int:canteen_pk>/diagnostics/",
        DiagnosticCreateView.as_view(),
        name="diagnostic_creation",
    ),
    path(
        "canteens/<int:canteen_pk>/diagnostics/<int:pk>",
        DiagnosticUpdateView.as_view(),
        name="diagnostic_update",
    ),
    path(
        "canteens/<int:canteen_pk>/diagnostics/<int:pk>/teledeclaration/create",
        DiagnosticTeledeclarationCreateView.as_view(),
        name="diagnostic_teledeclaration_create",
    ),
    path(
        "canteens/<int:canteen_pk>/diagnostics/<int:pk>/teledeclaration/cancel",
        DiagnosticTeledeclarationCancelView.as_view(),
        name="diagnostic_teledeclaration_cancel",
    ),
    path(
        "canteens/<int:canteen_pk>/diagnostics/<int:pk>/teledeclaration/pdf",
        DiagnosticTeledeclarationPdfView.as_view(),
        name="diagnostic_teledeclaration_pdf",
    ),
    path(
        "canteens/<int:canteen_pk>/wasteMeasurements/",
        CanteenWasteMeasurementsView.as_view(),
        name="canteen_waste_measurements_list",
    ),
    path(
        "canteens/<int:canteen_pk>/wasteMeasurements/<int:pk>",
        CanteenWasteMeasurementView.as_view(),
        name="canteen_waste_measurement_detail",
    ),
    path(
        "canteens/<int:canteen_pk>/satellites/",
        CanteenGroupeSatellitesListView.as_view(),
        name="canteen_groupe_satellites_list",
    ),
    path(
        "canteens/<int:canteen_pk>/satellites/<int:satellite_pk>/link/",
        CanteenGroupeSatelliteLinkView.as_view(),
        name="canteen_groupe_satellite_link",
    ),
    path(
        "canteens/<int:canteen_pk>/satellites/<int:satellite_pk>/unlink/",
        CanteenGroupeSatelliteUnlinkView.as_view(),
        name="canteen_groupe_satellite_unlink",
    ),
    path("canteenStatistics/", CanteenStatisticsView.as_view(), name="canteen_statistics"),
    path("sectors/", SectorListView.as_view(), name="sectors_list"),
    path("ministries/", CanteenMinistriesView.as_view(), name="ministries_list"),
    path("partnerTypes/", PartnerTypeListView.as_view(), name="partner_types_list"),
    path("blogPosts/", BlogPostsView.as_view(), name="blog_posts_list"),
    path("blogPosts/<int:pk>", BlogPostView.as_view(), name="single_blog_post"),
    path("partners/", PartnersView.as_view(), name="partners_list"),
    path("partners/<int:pk>", PartnerView.as_view(), name="single_partner"),
    path(
        "subscribeNewsletter/",
        SubscribeNewsletter.as_view(),
        name="subscribe_newsletter",
    ),
    path("passwordChange/", ChangePasswordView.as_view(), name="change_password"),
    path(
        "addManager/",
        AddManagerView.as_view(),
        name="add_manager",
    ),
    path(
        "canteenNotFoundMessage/",
        SendCanteenNotFoundEmail.as_view(),
        name="canteen_not_found",
    ),
    path(
        "removeManager/",
        RemoveManagerView.as_view(),
        name="remove_manager",
    ),
    path("importPurchases/", PurchasesImportView.as_view(), name="purchases_import"),
    path("importCanteens/", CanteensImportView.as_view(), name="canteens_import"),
    path("importDiagnostics/simple/", DiagnosticsSimpleImportView.as_view(), name="diagnostics_simple_import"),
    # path("importDiagnostics/simple/", ImportSimpleDiagnosticsView.as_view(), name="import_diagnostics"),
    # path("importDiagnostics/complete/", ImportCompleteDiagnosticsView.as_view(), name="import_complete_diagnostics"),
    # path("importDiagnostics/ccSimple/", ImportSimpleCentralKitchenView.as_view(), name="import_cc_diagnostics"),
    # path(
    #     "importDiagnostics/ccComplete/",
    #     ImportCompleteCentralKitchenView.as_view(),
    #     name="import_cc_complete_diagnostics",
    # ),
    path("emailDiagnosticImportFile/", EmailDiagnosticImportFileView.as_view(), name="email_diagnostic_file"),
    path("campaignDates/", TeledeclarationCampaignDatesListView.as_view(), name="list_teledeclaration_campaign_dates"),
    path(
        "campaignDates/<int:year>/",
        TeledeclarationCampaignDatesRetrieveView.as_view(),
        name="retrieve_teledeclaration_campaign_dates",
    ),
    path("inquiry/", InquiryView.as_view(), name="inquiry"),
    path(
        "purchases/",
        PurchaseListCreateView.as_view(),
        name="purchase_list_create",
    ),
    path(
        "export-achats.xlsx",  # breaking from URL conventions for nicer filename
        PurchaseListExportView.as_view(),
        name="purchase_list_export",
    ),
    path(
        "purchases/<int:pk>",
        PurchaseRetrieveUpdateDestroyView.as_view(),
        name="purchase_retrieve_update_destroy",
    ),
    path(
        "purchases/delete/",
        PurchasesDeleteView.as_view(),
        name="delete_purchases",
    ),
    path(
        "purchases/restore/",
        PurchasesRestoreView.as_view(),
        name="restore_purchases",
    ),
    path(
        "canteenPurchasesSummary/<int:canteen_pk>",
        CanteenPurchasesSummaryView.as_view(),
        name="canteen_purchases_summary",
    ),
    path(
        "canteenPurchasesPercentageSummary/<int:canteen_pk>",
        CanteenPurchasesPercentageSummaryView.as_view(),
        name="canteen_purchases_percentage_summary",
    ),
    path(
        "createDiagnosticsFromPurchases/<int:year>",
        DiagnosticsFromPurchasesView.as_view(),
        name="diagnostics_from_purchases",
    ),
    path("purchaseOptions/", PurchaseOptionsView.as_view(), name="purchase_options"),
    path("canteen/<int:canteen_pk>/reservationExpe/", ReservationExpeView.as_view(), name="canteen_reservation_expe"),
    path("canteen/<int:canteen_pk>/vegetarianExpe/", VegetarianExpeView.as_view(), name="canteen_vegetarian_expe"),
    path("message/", MessageCreateView.as_view(), name="message_create"),
    path("teamJoinRequest/<int:pk>/", TeamJoinRequestView.as_view(), name="canteen_team_request"),
    path("usernameSuggestion/", UsernameSuggestionView.as_view(), name="username_suggestion"),
    path("reviews/", ReviewView.as_view(), name="create_review"),
    path("communityEvents/", CommunityEventsView.as_view(), name="community_event_list"),
    path("canteens/<int:canteen_pk>/claim/", ClaimCanteenView.as_view(), name="claim_canteen"),
    path("canteens/<int:canteen_pk>/undoClaim/", UndoClaimCanteenView.as_view(), name="undo_claim_canteen"),
    path("actionableCanteens/<int:year>", ActionableCanteensListView.as_view(), name="list_actionable_canteens"),
    path(
        "actionableCanteens/<int:pk>/<int:year>",
        ActionableCanteenRetrieveView.as_view(),
        name="retrieve_actionable_canteen",
    ),
    path(
        "diagnosticsToTeledeclare/<int:year>",
        DiagnosticsToTeledeclareListView.as_view(),
        name="diagnostics_to_teledeclare",
    ),
    path("canteenStatus/siret/<str:siret>", CanteenStatusBySiretView.as_view(), name="canteen_status_by_siret"),
    path("canteenStatus/siren/<str:siren>", CanteenStatusBySirenView.as_view(), name="canteen_status_by_siren"),
    path("videoTutorials/", VideoTutorialListView.as_view(), name="video_tutorials"),
    path("initialData/", InitialDataView.as_view(), name="initial_data"),
    path("territoryCanteens/", TerritoryCanteensListView.as_view(), name="territory_canteens"),
    path("wasteActions/", WasteActionsView.as_view(), name="waste_actions_list"),
    path("wasteActions/<int:pk>", WasteActionView.as_view(), name="waste_action_detail"),
    path(
        "wasteActions/<int:resource_pk>/actions", ResourceActionView.as_view(), name="resource_action_create_or_update"
    ),
}

urlpatterns = format_suffix_patterns(urlpatterns)
